include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#development]
=== Development

////
Also see the following additional note:

* <<#jsc-SLE-16764>>
////

// Release notes for development tool/library features:
//   JVM, Python, GCC, ...


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

==== Python

[#jsc-PED-3800]
===== Python 3.10 modules, Reduced Python Stack

* Add Python 3.10 interpreter and modules
** We have added an additional long-term supported Python 3.10 interpreter and modules needed to be able to get python modules from PyPI (`python-setuptools`, `python-pip`, `python-virtenv`) via the __Python{nbsp}3__ Module.
It will be regularly updated to the latest patch version.
* Add Python Reduced Stack
** A reduced subset of what we provide today in {productnameshort} {this-version} has been added as modules.
* Keep Python 3.6
** The current Python 3.6 interpreter and packages stay intact.
** Renaming of Python packages would be done only to avoid source name conflicts.
* Life-cycle & support
** Python Reduced Stack will be supported until 2026, which is the upstream end-of-life date for Python 3.10.
The interpreter will be updated regularly to the latest patch version but modules will stay stable as much as possible.
** We will continue delivering new interpreters (along with the respective `setuptools`/`wheel`/`pip`) with each new service pack.
These are short-term supported for each Service Pack.


[#jsc-SLE-18038]
===== Python 3.10 has been added, replaces Python 3.9

Python 3.9 that had been available in {slea} {previous-version} has been replaced with Python 3.10 in {slea} {this-version}.


[#jsc-SLE-21167]
===== All Python packages have been updated

All `python-*` packages have been updated to their most recent versions.
Combined with the removal of Python{nbsp}2 described in <<jsc-SLE-16747>>, using external packages from the Python Package Index (PyPI) should now be easier due to less compatibility problems.


// also: FATE#327577
// also: SLE-16746
[#jsc-SLE-16747]
===== Python 2 has been removed

With {product} 15{nbsp}SP1, {suse} has started to phase out support for Python{nbsp}2 in {slea}.

In {product} {this-version}, standard Python 2 (executable names `python2` and `python`), and the temporarily available __Python{nbsp}2__ module  have been removed.
Only Python{nbsp}3 (executable name `python3`) is now available.

Python scripts usually expect the `python` executable (without a version number) to refer to the Python{nbsp}2.x interpreter.
If the Python{nbsp}3 interpreter is started instead, this can lead to applications failing or misbehaving.
For this reason, {suse} has decided _not_ to ship a symbolic link `/usr/bin/python` pointing to the Python{nbsp}3 executable.

[#jsc-SLE-23605]
===== Alternative Python 3 development interpreter moved to a separate module
// tag::python3module[]

{slea} 15 SP4 introduces a new __Python{nbsp}3__ Module, which includes the alternatively available development Python interpreter, formerly included in the __Basesystem__ Module.
This new module will allow for more flexibility for the lifecycle of the packages provided within it and a clean separation between the system and development interpreter.

As the `python39` package was part of the __Basesystem__ Module on {slea} 15 SP3, the introduction of this new module will require some changes when migrating to {slea} {this-version}.
If you are using `python39` and migrate from {slea} 15 SP3, you will have to add the __Python{nbsp}3__ module after migration via {suseconnect} to receive updates for this alternative interpreter.
Otherwise the package will remain orphaned and without security updates.

Packages inside this module can have differing support level and support lifecycle. For more information, see documentation.
// end::python3module[]

==== Node

[#jsc-SLE-21779]
===== `nodejs16` has been added

The `nodejs16` package has been added.
This is the new default NodeJS version.


[#jsc-SLE-21233]
===== `nodejs-common` has been changed

Previously, `nodejs-common` pointed to `nodejs14` as this was the default version.
With the addition of `nodejs16`, `nodejs-common` now points to `nodejs-default` instead.


==== Other

[#jsc-SLE-17951]
===== `debuginfod` packages have been added

The following packages were added to the _Basesystem Module_:

* `debuginfod-client`
* `libdebuginfod1`

We do not provide any `debuginfod` service but the packages enable creation of one.

See https://sourceware.org/elfutils/Debuginfod.html for more information.


[#jsc-SLE-23458]
===== Prometheus has been updated

The `golang-github-prometheus-prometheus` package has been updated to version 2.32.1.
See the link:https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2321%2d%2d2021-12-17[full changelog] for more information.


[#jsc-SLE-21017]
===== `tcl` has been updated

The `tcl` package has been updated to version 8.6.12.
See the http://www.tcl-lang.org/software/tcltk/8.6.html[full changelog] for more information.


[#jsc-SLE-21914]
===== `bzr` has been replaced with `breezy`

The `bzr` package has been removed from {productnameshort} because it requires the removed Python 2.
As a replacement, the `breezy` package has been added.
`breezy` is a Python 3 implementation of the Bazaar VCS.


[#jsc-SLE-21037]
===== 'subversion' has been updated

The `subversion` package has been updated to version 1.14.1.

Among others, this version includes:

* Python 3.x support
* breaking change for the experimental shelving feature

See https://subversion.apache.org/docs/release-notes/1.14[the full changelog] for more information.


[#jsc-SLE-22290]
===== `sccache` and `rustup` have been added

`sccache` is a compiler caching tool for Rust, C, and C++, with optional cloud storage.
`rustup` is a tool for managing user Rust toolchains.
These two tools have been added in an effort to improve Rust developer tools.

[#jsc-SLE-22289]
===== Squid has been updated

The `squid` package has been updated from version 4.17 to version 5.2.

See the http://www.squid-cache.org/Versions/v5/RELEASENOTES.html[full changelog] for more information.


[#jsc-SLE-20308]
===== TCK compliance testing in {sle}

We run the TCK test suite provided by Oracle to ensure that our version of OpenJDK is in compliance with the Java specification.


[#jsc-SLE-18816]
===== PHP 8 has been added, replacing PHP 7

PHP version 8.0.10 has been added.
There are many improvements in this version, some of which are:

* Union Types
* Named Arguments
* Match Expressions
* Attributes
* Constructor Property Promotion
* Nullsafe Operator
* Weak Maps
* Just In Time Compilation

For the full changelog, see https://www.php.net/ChangeLog-8.php#8.0.0 and https://www.php.net/ChangeLog-8.php#8.0.10.

.Removal of PHP 7
[NOTE]
====
// bsc#1203461
PHP 8 has replaced PHP 7, which has moved to the _Legacy Module_.
After upgrading, make sure that all needed packages, including extension modules, are installed for PHP 8.
Additionally, the current version of the package `apparmor-profiles` includes the `php-fpm` profile that was absent before.
This profile effectively blocks PHP-FPM processes from accessing the socket file (if its name differs from the template in this file) as well as to directories with PHP scripts (for example, the standard directory `/srv/www/htdocs` and its subdirectories).
====

// !STICKY
[#java-version]
==== Supported Java versions

The following Java implementations are available in {product} {this-version}:

// relevant source: https://confluence.suse.com/display/SLE/Java
//             and: bsc#1171541

[cols="33%,17%,17%,33%" options="header"]
|===
|Name (Package Name)
|Version
|Module
|Support

|OpenJDK +
(`java-11-openjdk`)
|11
|Base System
|SUSE, L3, until 2026-12-31

|OpenJDK +
(`java-17-openjdk`)
|17
|Base System
|SUSE, L3, until 2027-12-31

|OpenJDK +
(`java-1_8_0-openjdk`)
|1.8.0
|Legacy
|SUSE, L3, until 2026-12-31

|IBM Java +
(`java-1_8_0-ibm`)
|1.8.0
|Legacy
|External, until 2025-04-30
|===
