include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#ibm-z]
== {ibmz}-specific changes (s390x)

Information in this section applies to {z-product} {this-version}.
For more information, see https://www.ibm.com/docs/en/linux-on-systems?topic=distributions-suse-linux-enterprise-server

[#ibm-z-hardware]
=== Hardware

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

There were the following hardware-related changes:

// SLE-18639
* support has been added for IBM z15 instructions in Valgrind
// SLE-18638, SLE-18637
* support has been added for IBM z16 instructions in `glibc`, `gdb`, and `binutils`
// SLE-18634
* support has been added for IBM z16 in kernel
// SLE-21645
* added the zDNN library that provides a user space API for exploitation of the Neural Network Processing Assist Facility of the IBM z16


[#ibm-z-network]
=== Networking

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-18324]
==== `zdsfs`: transparent dataset conversion

Enabled zdsfs to read and write EBCDIC-encoded data sets as ASCII and read data sets in the same format as resulting from an FTP transfer from z/OS to Linux (including record translations).

// SLE-18324
==== `zipl`: implemented environment block

Introduces new tool zipl-editenv that allows a Linux on Z user to specify persistent configuration information that is evaluated during boot without the need to rewrite IPL records.

// SLE-18324
==== PCI auto-activate for Dynamic Partition Manager

Allows a Linux on Z user to automatically use any PCI function defined for an LPAR on Dynamic Partition Manager without the need to manually configure the PCI function online.

[#jsc-SLE-18521]
==== SMC-Rv2 support

Lifts the restriction of traffic limited to be within a single IP subnet only.

[#jsc-SLE-18520]
==== SMC: statistics support

Adds statistics for traffic run across RoCE (RDMA) and ISM devices.

[#jsc-SLE-18518]
==== SMC: user-defined EID (Enterprise ID) support

Adds a tool to display and set EIDs (SMC Enterprise IDs).

[#jsc-SLE-18517]
==== wireshark: updated to include SMC-D support

Provides support for SMC-R, SMC-D and SMC-Dv2 in wireshark.

[#jsc-SLE-18516]
==== HSCI (HiperSockets Converged Interface): multi-MAC support

Enhances HSCI to support multiple MAC Addresses as required by Open vSwitch, as well as the corresponding tool for exploitation.

// also SLE-18514
[#jsc-SLE-18515]
==== RoCE: predictable interface names

Up to {slesa} {previous-version}:

* Interface names for RoCE Express adapters were very hard to predict
* Interface names could change between re-boots, invalidating any previously stored network card configuration
To fix this, changes were made in the Linux kernel to indicate whether UIDs are unique to have systemd generate easy to predict interface names on (preferably) UID or FID.

[#ibm-z-performance]
=== Performance

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

// SLE-18132
* Nettle-Community contributions improved the performance of the AES-GCM algorithm for POWER9 and Power10.


[#jsc-SLE-22496]
==== Improved performance on RoCE ConnectX-4 hardware

Fixed performance problem for which the workaround was described in the Release Notes of earlier {slesa} {this-ga} service packs.


[#ibm-z-security]
=== Security

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

// also SLE-18641
[#jsc-SLE-18323]
==== `zcrypt`

There were the following `zcrypt`-related changes:

* provide indications to early exploiters of crypto adapters (e.g. `dm-crypt` root devices using the PAES cipher) that ap bus initialization and DD bindings are complete
* AP bus and `zcrypt` device driver uevent extensions that provide uevents for the following AP bus events: online state change, config state change, add crypto mode events
* toleration for new IBM Z crypto hardware

// also SLE-18326
[#jsc-SLE-22853]
==== openCryptoki

There were the following openCryptoki-related changes:

* ep11 token: support generation of attribute bound keys and operations with attribute bound keys
* ep11 token: protected key support
* event notification support
* cca token: support the interchange of CCA secure key objects (as generated by the CCA library) between code using the CCA library and openCryptoki
* p11sak: extended to display vendor specific boolean attributes in the long listing and enablement for configuration to learn about additional (boolean) key attributes

// SLE-18324
==== `zkey`

There were the following `zkey`-related changes (`s390-tools`):
- extended LUKS2 functionality
- integration of the `zkey` repository into an enterprise key mangement system with a KMIP interface

[#jsc-SLE-18454]
==== `libica`

Eliminated implementations of software fallback functions and replaced them by calls to openSSL/libcrypto.

[#jsc-SLE-18453]
==== `openssl-ibmca`

Made `openssl-ibmca` engine call libica w/o software fallbacks.
Only register `openssl-ibmca` functions if `libica` signals the existence of a hardware function.

==== `pkey`

Add protected key support for private ECDSA/EdDSA keys.

[#jsc-SLE-18746]
==== `libzpc`

Added new library to support protected key cryptography: `libzpc` - IBM Z Protected-key Cryptography

[#ibm-z-storage]
=== Storage

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-18513]
==== `zfcp`: handling of firmware update notifications

Enhanced user information of the FCP device driver about HBA firmware version to improve handling of firmware update notifications.

// SLE-18324
==== Multi-path re-IPL

List-Directed IPL (for FCP etc.) was restricted to a single FCP-WWPN-LUN path.
If this path is unavailable, (re)-IPL fails.
This change implements a solution to keep the path to re-IPL up to date, and therefore work around transient path failures in many cases.

[#ibmz-virtualization]
=== Virtualization

The following new features are supported in {product} {this-version} under KVM:


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#bsc-1200422]
==== Fix for "Host does not support any virtualization options"

When attempting to run `virt-install` on {product} {this-version} for {ibmz}
the command may fail with the error "Host does not support any virtualization options".
Install the latest qemu package from the update repository to fix this
problem.

==== Provide persistent `vfio-ccw` device assignments

Establish persistent information about CCW devices intended to be passed through to KVM guests.

==== Added CPU model for IBM z16

Enable architectural features of the IBM z16 for KVM guests.

==== Change Secure Execution header defaults for Plaintext Control Flags (PCF)

To improve usability the default SE header PCF settings are now set to allow all PCKMO types.
An explicit option has been added to enable/disable PCKMO, so that clients have no need to use the "experimental/expert" flags.

==== Secure guest indication

Provides an indication in the guest that it is running securely.
Cannot replace a real attestation and does not really provide additional security (or could even create the false impression of security), but has been frequently requested by customers.

[#jsc-SLE-20855]
==== Enabled `vfio-ccw` and `vfio-ap` in `virt-*` tools in `virt-manager`

The tools in the `virt-manager` package, most prominently `virt-install` and `virt-xml`, are now aware of the IBM Z specific `virtio` types.
Therefore, it's now possible to install a VM with passed-through DASDs or APQNs.

[#ibm-z-misc]
=== Miscellaneous


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-18635]
==== SCLP (Service-Call Logical Processor) extended length SCCBs

Enable support for machines with more then 256 CPUs.

// SLE-18324
==== Improved CPU-MF counter set extraction performance

Performance improvement through reading out complete counter sets with a single instruction and export them to user space without sampling involved.
