
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#intro]
== {product}

{product} is a highly scalable, high performance open-source operating system designed to utilize the power of parallel computing for modeling, simulation and advanced analytics workloads.

{product} {this-version} provides tools and libraries related to High Performance Computing. This includes:

* Workload manager
* Remote and parallel shells
* Performance monitoring and measuring tools
* Serial console monitoring tool
* Cluster power management tool
* A tool for discovering the machine hardware topology
* System monitoring
* A tool for monitoring memory errors
* A tool for determining the CPU model and its capabilities (x86-64 only)
* User-extensible heap manager capable of distinguishing between different kinds of memory (x86-64 only)
* Serial and parallel computational libraries providing the common standards BLAS, LAPACK, ...
* Various MPI implementations
* Serial and parallel libraries for the HDF5 file format 

[#intro-availability]
=== Hardware Platform Support
{product} {this-version} is available for the Intel 64/AMD64 (x86-64) and AArch64 platforms.


[#intro-important]
=== Important Sections of This Document
If you are upgrading from a previous {product} release, you should review at least the following sections:

* <<intro-support>>
// * <<upgrade>>


[#intro-lifecycle]
=== Support and life cycle

{product} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.

// bnc#821338, bnc#828478, bnc#882262
{product}{nbsp}{this-ga} has a 13-year life cycle, with 10 years of General Support and 3 years of Extended Support.
The current version ({this-sp}) will be fully maintained and supported until 6 months after the release of {product}{nbsp}{this-ga}{nbsp}{next-sp}.

Any release package is fully maintained and supported until the availability of the next release.

Extended Service Pack Overlay Support (ESPOS) and Long Term Service Pack Support (LTSS) are also available for this product. If you need additional time to design, validate and test your upgrade plans, Long Term Service Pack Support (LTSS) can extend the support you get by an additional 12 to 36 months in 12-month increments, providing a total of 3 to 5 years of support on any given Service Pack.

For more information, see:

* The support policy at https://www.suse.com/support/policy.html
* Long Term Service Pack Support page at https://www.suse.com/support/programs/long-term-service-pack-support.html 


[#intro-support]
=== Support statement for {product}

To receive support, you need an appropriate subscription with {suse}.
For more information, see {support-url}.

The following definitions apply:

L1::
Problem determination, which means technical support designed to provide compatibility information, usage support, ongoing maintenance, information gathering and basic troubleshooting using available documentation.
L2::
Problem isolation, which means technical support designed to analyze data, reproduce customer problems, isolate problem area and provide a resolution for problems not resolved by Level{nbsp}1 or prepare for Level{nbsp}3.
L3::
Problem resolution, which means technical support designed to resolve problems by engaging engineering to resolve product defects which have been identified by Level{nbsp}2 Support.

For contracted customers and partners, {product} is delivered with L3 support for all packages, except for the following:

* Technology Previews, see <<intro-techpreview>>
* Sound, graphics, fonts and artwork
* Packages that require an additional customer contract, see <<intro-support-external>>


{suse} will only support the usage of original packages. That is, packages that are unchanged and not recompiled.



// see fate#316990, bsc#1161529
[#intro-support-external]
==== Software requiring specific contracts

Certain software delivered as part of {product} may require an external contract.
Check the support status of individual packages using the RPM metadata that can be viewed with `rpm`, `zypper`, or {yast}.


// see jsc#SLE-7191
[#intro-license-agpl]
==== Software under GNU AGPL

////
How to create a list:
1. Go to https://scc.suse.com/packages
2. Choose product, version, pick x86_64 architecture, click Search
3. Download as CSV
4. Open in LibreOffice
5. Select entire table, Data > Pivot Table > Insert or Edit, click OK
6. Drag all column headers to Row Fields, OK
7. In License header, search for "agpl", pick all of those; in Module header, select everything but Package Hub
////

{product} {this-version} (and the {sle} modules) includes the following software that is shipped __only__ under a GNU AGPL software license:

* Ghostscript (including subpackages)

{product} {this-version} (and the {sle} modules) includes the following software that is shipped under multiple licenses that include a GNU AGPL software license:

* MySpell dictionaries and LightProof
* ArgyllCMS

include::about-documentation.adoc[]