include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#aarch64]
== {arm} 64-bit-specific changes (AArch64)

Information in this section applies to {arm-product} {this-version}.


[#arm64-soc]
=== System-on-Chip driver enablement

{arm-product} {this-version} includes driver enablement for the following
System-on-Chip (SoC) chipsets:

* {amdreg} {opteronreg} A1100
* {amperereg} {xgenereg}, {emagreg}, {altrareg}, _{altramax}_, {ampereonereg}
* {awsreg} Graviton, Graviton2, Graviton3
* {brcmreg} BCM2837/BCM2710, BCM2711
* {fujitsureg} A64FX
* {huaweireg} {kunpengreg} 916, {kunpeng} 920
* {marvellreg} {thunderxreg}, {thunderx2reg}; {octeon-txreg}; {armadareg} 7040, {armada} 8040
* {nvidiareg} {grace}; {tegrareg}{nbsp}X1, Tegra{nbsp}X2, {xavierreg}, {orin}; {bluefieldreg}, _{bluefield2}_
// jsc#SLE-12251 (LS1012A), jsc#SLE-11914 (i.MX 8MM)
* {nxpreg} {imx} 8M, 8M{nbsp}Mini; {layerscapereg} LS1012A, LS1027A/LS1017A, LS1028A/LS1018A, LS1043A, LS1046A, LS1088A, LS2080A/LS2040A, LS2088A, LX2160A
* {qcomreg} {centriqreg} 2400
* Rockchip RK3399
* {socionextreg} {synquacerreg} SC2A11
* {xilinxreg} {zynqreg} {ultrascalereg}{nbzwsp}+ MPSoC

NOTE: Driver enablement is done as far as available and requested.
Refer to the following sections for any known limitations.

Some systems might need additional drivers for external chips, such as a
Power Management Integrated Chip (PMIC), which may differ between systems
with the same SoC chipset.

For booting, systems need to fulfill either the Server Base Boot Requirements (SBBR)
or the Embedded Base Boot Requirements (EBBR),
that is, the Unified Extensible Firmware Interface (UEFI) either
implementing the Advanced Configuration and Power Interface (ACPI) or
providing a Flat Device Tree (FDT) table. If both are implemented, the kernel
will default to the Device Tree; the kernel command line argument `acpi=force` can
override this default behavior.

Check for {suse} _YES!_ certified systems,
which have undergone compatibility testing.


[#aarch64-new]
=== New features

[#jsc-PED-7310]
==== Memory Tagging in GNU C Library

{arm-product} {this-ga}{nbsp}SP4 and SP5 prepared their kernels for the
{armv8}.5 Memory Tagging Extension (`FEAT_MTE`).
Their `glibc` packages were based on version 2.31 and did not yet support
Memory Tagging.

{arm-product} {this-version} updates `glibc` base version to 2.38
and enables Memory Tagging in the GNU C Library as well.


[#jsc-PED-7600-arm64]
=== Changed kernel `CONFIG_HZ` value

{arm-product} {previous-version} and earlier kernels have used a `CONFIG_HZ` value of
100{nbsp}Hz.

The {arm-product} {this-version} kernel instead uses a value of 250{nbsp}Hz.
This matches the latest default and the value for x86-64 architecture
(<<jsc-PED-7600>>).


[#jsc-PED-7009]
=== Changed kernel I/O MMU default

{arm-product} {previous-version} and earlier kernels have defaulted the
I/O MMU (Input/Output Memory Management Unit) to **passthrough** mode.
This was the most performant setting, but did not work on all machines.
It then required the user to override the default via `iommu.passthrough=0`
kernel command line option.

{arm-product} {this-version} kernel instead defaults to **translated** mode.
This achieves a greater hardware compatibility.

To force the previous behavior, use the kernel command line option
`iommu.passthrough=1`.


[#jsc-PED-4489]
=== 64K page size kernel flavor is supported

{arm-product} 12{nbsp}SP2 and later kernels have used a page size of 4K.
This offers the widest compatibility also for small systems with little RAM,
allowing to use Transparent Huge Pages (THP) where large pages make sense.

As a technology preview, {arm-product} {this-ga}{nbsp}SP3 added a kernel flavor
`64kb`, offering a page size of 64{nbsp}KiB and physical/virtual address size
of 52 bits.
Same as the `default` kernel flavor, it does not use preemption.

{arm-product} {previous-version} largely removed this technology preview status,
offering support for `kernel-64kb` on select platforms, such as
{nvidiagracereg}.
KVM virtualization remains a technology preview on this `64kb` kernel flavor
(<<jsc-PED-4489-kvm>>).

[NOTE]
.Default file system no longer needs to be changed
====
{arm-product} {this-version}{nbsp}SP4 and later allow the use of Btrfs based file systems
with 4{nbsp}KiB block size also with 64{nbsp}KiB page size kernels.

// See <<jsc-SLE-17674>> for details and known limitations.
====

[IMPORTANT]
.Swap needs to be re-initialized
====
After booting the 64K kernel, any swap partitions need to re-initialized to be usable.
To do this, run the `swapon` command with the `--fixpgsz` parameter on the swap partition.
Note that this process deletes data present in the swap partition (for example, suspend data).
In this example, the swap partition is on `/dev/sdc1`:
[source,bash]
swapon --fixpgsz /dev/sdc1
====

// jsc#SLE-14841
// jsc#SLE-20728
[WARNING]
.RAID{nbsp}5 uses page size as stripe size
====
It is currently possible to configure stripe size by setting the following kernel parameter:
[source,bash]
echo 16384 > /sys/block/md1/md/stripe_size

Keep in mind that `stripe_size` must be in multiples of 4KB and not bigger than `PAGE_SIZE`. Also, it is only supported on systems where `PAGE_SIZE` is not 4096, such as arm64.

Avoid RAID{nbsp}5 volumes when benchmarking 64K vs. 4K page size kernels.

See the __Storage Guide__ for more information on software RAID.
====

[NOTE]
.Cross-architecture compatibility considerations
====
The {productname} {this-version} kernels on x86-64 use 4K page size.

The {power-product} {this-version} kernel uses 64K page size.
====


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
=== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#aarch64-known]
=== Known limitations

[#jsc-PED-4564-drm]
==== No graphics drivers on {nvidiagracehopper}

The {nvidiagracehopperreg} System-on-Chip contains an integrated,
_Hopper_ microarchitecture-based Graphics Processor Unit (GPU).

{arm-product} {this-version} maintenance updates currently provide packages
`nvidia-open-driver-G06-signed-kmp-default` and `kernel-firmware-nvidia-gspx-G06`
in version `535.104.05`, which does not yet enable {nvidiagracehopper} GH200.

// bsc#1216872 for lack of -kmp-64kb packages

Check for maintenance updates of those packages with version `545.29.02` or later,
or contact the system vendor or chip vendor {nvidia} for whether third-party
graphics drivers are available for {arm-product} {this-version}.

[NOTE]
.PCIe GPUs not affected
====
Discrete GPU cards with _Hopper_ microarchitecture, such as {nvidia} H100,
are already enabled in shipping package versions.
====


[#jsc-PED-1763-drm]
==== No graphics drivers on {nvidia} {jetson}

The {nvidiareg} {tegrareg} System-on-Chip chipsets include an integrated
Graphics Processor Unit (GPU).

{arm-product} {this-version} does not include graphics drivers for any of the
{nvidia} {jetsonreg}, {nvidia} IGX or {nvidiadrivereg} platforms.

Contact the chip vendor {nvidia} for whether third-party graphics drivers are
available for {arm-product} {this-version}.


[#jsc-SLE-9263-hdp]
==== No {displayport} graphics output on {nxp} LS1028A and LS1018A

The {nxpreg} {layerscapereg} LS1028A/LS1018A System-on-Chip contains
an {armreg} {malireg}-DP500 Display Processor, whose output is connected to a
{displayportreg} TX{nbsp}Controller (HDP-TX) based on
{cadencereg} High Definition (HD) Display Intellectual Property (IP).

A Display Rendering Manager (DRM) driver for the {arm} {mali}-DP500
Display Processor is available as technology preview (<<#jsc-SLE-9263-malidp>>).

However, there was no HDP-TX physical-layer (PHY) controller driver ready yet.
Therefore no graphics output will be available, for example, on the
{displayportreg} connector of the {nxp} LS1028A Reference Design Board (RDB).

Contact the chip vendor {nxp} for whether third-party graphics drivers are
available for {arm-product} {this-version}.

Alternatively, contact your hardware vendor for whether a bootloader update
is available that implements graphics output, allowing to instead use `efifb`
framebuffer graphics in {arm-product} {this-version}.

NOTE: The {vivante} GC7000UL GPU driver (`etnaviv`) is available as a
technology preview (<<jsc-SLE-9263-etnaviv>>).

// [#arm64-rpi3-known]

// [#arm64-rpi4-known]
