== Juridisk information

Upphovsrätt © {copyright-begin}-{copyright-end} openSUSE-bidragsgivare och SUSE LLC. Alla rättigheter förbehållna.

Tillstånd beviljas att kopiera, distribuera och/eller modifiera detta dokument
enligt villkoren i GNU fri dokumentationslicens, version 1.2 eller
(efter ditt val) version 1.3; där den oföränderliga sektionen av detta
copyrightmeddelande och licens. En kopia av licensversion 1.2
finns i avsnittet med titeln "GNU fri dokumentationslicens.

Detta dokument innehåller innehåll anpassat från SUSE Linux Enterprise
versionsinformation, bidragit till av SUSE dokumentationsteamet. Delar av
innehållet underhålls av openSUSE-gemenskapen.

För SUSE-varumärken, se https://www.suse.com/company/legal/.
För openSUSE-varumärken, se
https://en.opensuse.org/openSUSE:Trademark_guidelines.
Alla andra varumärken från tredje part tillhör sina respektive
ägare. Varumärkessymboler (®, ™, etc.) betecknar varumärken som tillhör SUSE, openSUSE och deras dotterbolag. Asterisker (*) betecknar varumärken från tredje part.

Även om alla ansträngningar har gjorts för att säkerställa noggrannhet, tar openSUSE-bidragsgivarna, SUSE-dokumentationsteamet och författarna inget
ansvar för fel eller utelämnanden, eller för skador som uppstår till följd av
användningen av informationen här.