
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#intro]
== {product}

{product}{nbsp}{this-version} is the leading Linux platform for {hana}, {nw}, and {s4hana} applications that provides optimized performance, reduced downtime, and faster {sap} landscape deployments.
It includes features to secure {hana} systems and ease the transition to {s4hana} for systems administrators.
{product} combines {sles} and {sleha} with additional software specifically meant to simplify running and managing {sap} applications. This document provides an overview of high-level general features, capabilities, and limitations of {product}{nbsp}{this-version} and important product updates.

include::whats-new.adoc[]

[#intro-important]
=== Important Sections of This Document

If you are upgrading from a previous {product} release, you should review at least the following sections:

* <<intro-support>>


[#intro-certification]
=== Security, Standards, and Certification

{product}{nbsp}{this-version} has been submitted to the certification bodies for:

* Common Criteria Certification, see https://www.commoncriteriaportal.org/
* FIPS 140-2 validation, see http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140InProcess.pdf

For more information about certification, see https://www.suse.com/security/certificates.html.

include::about-documentation.adoc[]


[#intro-lifecycle]
=== Support and life cycle

{product} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.

// bsc#1222560
{product} includes Extended Service Pack Overlay Support (ESPOS).
This provides an additional 3 years of support for each SP following the end of general support.
Combined with the standard 6 months overlay, it offers a total of 3.5 years of overlay support after the launch of the next Service Pack.

For more information, check our Support Policy page https://www.suse.com/support/policy.html or the Long Term Service Pack Support Page https://www.suse.com/support/programs/long-term-service-pack-support.html.


[#intro-support]
=== Support statement for {product}

To receive support, you need an appropriate subscription with {suse}.
For more information, see {support-url}.

The following definitions apply:

L1::
Problem determination, which means technical support designed to provide compatibility information, usage support, ongoing maintenance, information gathering and basic troubleshooting using available documentation.
L2::
Problem isolation, which means technical support designed to analyze data, reproduce customer problems, isolate problem area and provide a resolution for problems not resolved by Level{nbsp}1 or prepare for Level{nbsp}3.
L3::
Problem resolution, which means technical support designed to resolve problems by engaging engineering to resolve product defects which have been identified by Level{nbsp}2 Support.

For contracted customers and partners, {product} is delivered with L3 support for all packages, except for the following:

* Technology Previews, see <<intro-techpreview>>
* Sound, graphics, fonts and artwork
// * Packages that require an additional customer contract, see <<intro-support-external>>
* Some packages shipped as part of the module _Workstation Extension_ are L2-supported only
* Packages with names ending in `-devel` (containing header files and similar developer resources) will only be supported together with their main packages.

{suse} will only support the usage of original packages. That is, packages that are unchanged and not recompiled.

[#intro-support-general]
==== General support

To learn about supported features and limitations, refer to the following
sections in this document:

* <<changes>>
* <<known-issues>>
// * <<kernel>>
// * <<virtualization>>
// * <<filesystems>>
* <<removed-deprecated>>

// see fate#316990, bsc#1161529
[#intro-support-external]
==== Software requiring specific contracts

Certain software delivered as part of {product} may require an external contract.
Check the support status of individual packages using the RPM metadata that can be viewed with `rpm`, `zypper`, or {yast}.

Major packages and groups of packages affected by this are:

* PostgreSQL (all versions, including all subpackages)


==== SAP Support Statement

Make sure to also review the https://apps.support.sap.com/sap/support/pam[SAP Product Availability Matrix] and/or https://launchpad.support.sap.com/#/notes/2235581[SAP Note 2235581 - SAP HANA: Supported Operating Systems] for official SAP support and certification statements.

// see jsc#SLE-7191
[#intro-license-agpl]
==== Software under GNU AGPL

////
How to create a list:
1. Go to https://scc.suse.com/packages
2. Choose product, version, pick x86_64 architecture, click Search
3. Download as CSV
4. Open in LibreOffice
5. Select entire table, Data > Pivot Table > Insert or Edit, click OK
6. Drag all column headers to Row Fields, OK
7. In License header, search for "agpl", pick all of those; in Module header, select everything but Package Hub
////

{product} {this-version} (and the {sle} modules) includes the following software that is shipped __only__ under a GNU AGPL software license:

* Ghostscript (including subpackages)

{product} {this-version} (and the {sle} modules) includes the following software that is shipped under multiple licenses that include a GNU AGPL software license:

* MySpell dictionaries and LightProof
* ArgyllCMS

include::tech-previews.adoc[]
