tag::60[]
tag::61[]
tag::62[]
// jsc#SMO-485
= Helm has been added

Helm has been added to {productname} {this-version}.

[#jsc-SMO-564]
= `podmansh` added

The `podmansh` package has been added.
It provides a confined login and user shell with access to volumes and capabilities specified in user quadlets.
end::62[]
end::61[]
end::60[]

tag::60[]
tag::61[]

= LTTng is deprecated

{productname} {this-version} provides support for LTTng (Linux Trace Toolkit: next generation). Support for LTTng will however be removed in a later {productname} version in favor of alternative solutions for tracing like bpftrace.
end::61[]
end::60[]

tag::60[]
tag::61[]
tag::62[]
tag::63[]
[#jsc-PED-14646]
= BPF tooling updated to the latest upstream versions

This release updates BPF (Berkeley Packet Filter) tooling to the latest upstream versions.
The following packages are updated:

* `libbpf` to version 1.6.2
* `bpftool` to version 7.6.0
* `bpftrace` to version 0.24.1

These updates provide new features and bug fixes.

[#jsc-PED-7936]
= Extras channel

A new channel called "SUSE Linux Micro Extras" has been added.
It includes testing, development and certifications packages and components that are not normally included with the OS itself.
These packages are not supported.
end::63[]
end::62[]
end::61[]
end::60[]
