:this-version: 6.1
:idprefix: v61_
:doc-url: https://documentation.suse.com/sle-micro/{this-version}
:previous-version: 6.0
:this-version: 6.1
:next-version: 6.2

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures

==== Installation media

// jsc#PED-8578
On top of the images described above with {productname} {this-version} we are adding PXE boot images (network boot .tar) for all architectures except ppc64le.

==== Supported Architectures

// jsc#PED-8466
{productname} {this-version}  adds general support for the IBM Power platform (ppc64le) to the product. It requires at least IBM Power9. IBM Power8 is not supported.

==== Upgrade Path

An online migration of existing SUSE Linux Enterprise Micro 5.5 or {productname} 6.0 installations to {productname} {this-version} is possible and is fully supported.

[#bsc-1230402]
==== Release numbering change

In {productname} 6.1, the package release numbers start with `slfo.1.1`, while there was no such prefix in {productname} 6.0.
Due to this, the release numbers of {productname} 6.1 are lower than the ones on {productname} 6.0 (as the above translates to `0.1.1`).
This is a known issue and will not happen in future releases.
The standard migration tooling will handle this correctly.

[#jsc-SMO-405]
==== Password-based remote root login not allowed

For enhanced security, new installations of {productname} {this-version} do not allow password-based remote root login anymore, which also affects Cockpit.
The login to Cockpit now requires to create and use an unprivileged user and to optionally set up 2-factor authentication with one-time passwords.
The `firstboot-installer` as well as `ignition` and the online tool `fuel-ignition` support this setup.

ifeval::["{lifecycle}" == "beta"]
For more information about the procedure and other options see https://susedoc.github.io/doc-modular/main/html/Micro-cockpit/index.html#cockpit-authentication-basics.
endif::[]
ifeval::["{lifecycle}" == "maintained"]
For more information about the procedure and other options see https://documentation.suse.com/en-us/sle-micro/6.1/html/Micro-6.1-cockpit/index.html#cockpit-authentication-basics.
endif::[]

[#jsc-PED-8686]
==== Soft-Reboot support

Ability to activate SW changes without the need to reboot. Support for soft-reboot is fully integrated in transactional-update and rebootmgr. It only reboots the userland, not the hardware or kernel. This reduces the downtime of {productname} dramatically, if the changes don't contain an updated kernel or bootloader, as you don't have to go through the full boot cycle to enable the new root subvolume. The behavior of reboot depends on the configuration and changes performed to the system. If soft-reboot is enabled, only the user  space may be restarted without rebooting the hardware and kernel. To enable and configure soft-reboot functionality please refer to the documentation.

[#jsc-SMO-422]
==== RAM Compressor (Z-RAM)

ZRAM allows users to both compress main memory and therefore gain more compute resources on smaller systems, but also allows users to use a compressed area of main memory as a swap device, with the added option to back that by a block device. That allows the system to support more complex setups with limited resources available. Key benefits of zram are fast I/O operations and memory savings.

[#jsc-SMO-291]
==== Active Directory

{productname} supports integration with Active Directory environments based on `sssd` since {productname} {previous-version}.

// https://github.com/SUSE/release-notes/issues/1
==== Build Host and Build Date Metadata

The RPM packages that {productname} uses are built with reproducible builds in mind.
This is also reflected in the package metadata.
For example, Build Host is now unified, and the package's Build Date corresponds to the latest change in the package sources.
In contrast, regular packages's Build Date refers to the date when the package was built instead.


=== Removed and deprecated features and packages

// This section is intended as a quick-to-consume list of deprecations/removals
// Do not add longer notes to this section. Instead:
//   * Add one list item per removed/deprecated feature/package
//   * Optionally, add a longer note to the appropriate section in #all-architecture.
//     Cross-reference the longer note in this section with <<note-id>>.

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.


// [NOTE]
// .Package and module changes in {this-version}
// For more information about all package and module changes since the last version, see <<intro-package-changes>>.


[#removed]
==== Removed features and packages

// The following features and packages have been removed in this release.

////
// jsc#EX-0000
* Example Removed Feature has been removed.
Use Replacement Feature instead.

// jsc#EX-0000
* Example Removed Feature 2 has been removed.
For more information, see <<jsc-SLE-0000>>.
////

// jsc#DOCTEAM-1622
* `busybox`
* `salt-master`
* `k3s`

// [#deprecated]
// === Deprecated features and packages

// ////
// 1. Deprecations that will be removed in an upcoming service pack of current SLE major version:
// 2. Deprecations that will be removed in the next SLE major version:
// 3. Deprecations that will be removed later or where removal timing is unclear:
// ////

// The following features and packages are deprecated and will be removed in a future version of {productname}.



// ===================================================================

