
include::entities_all.adoc[]
include::entities15.adoc[]

[#intro]
== {product}

{product}is the leading Linux platform for {hana}, {nw}, and {s4hana} applications that provides optimized performance, reduced downtime, and faster {sap} landscape deployments.
It includes features to secure {hana} systems and ease the transition to {s4hana} for systems administrators.
{product} combines {sles} and {sleha} with additional software specifically meant to simplify running and managing {sap} applications. This document provides an overview of high-level general features, capabilities, and limitations of {product}{nbsp}{this-version} and important product updates.

include::whats_new.adoc[]

[#intro-important]
=== Important Sections of This Document

If you are upgrading from a previous {product} release, you should review at least the following sections:

* <<intro-support>>

// * FIXME


[#intro-certification]
=== Security, Standards, and Certification

{product}{nbsp}{this-version} has been submitted to the certification bodies for:

* Common Criteria Certification, see https://www.commoncriteriaportal.org/
* FIPS 140-2 validation, see http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140InProcess.pdf

For more information about certification, see https://www.suse.com/security/certificates.html.


[#intro-documentation]
=== Documentation and Other Information

// Rethink use of the word media here. There is just one installation medium. - sknorr, 2017-10-20

[#intro-documentation-media]
==== Available on the Installation Media

* Read the READMEs on the media.
* Get the detailed change log information about a particular package from the RPM (where `_FILENAME_.rpm` is the name of the RPM):
+
----
rpm --changelog -qp _FILENAME_.rpm
----
* Check the `ChangeLog` file in the top level of the media for a chronological log of all changes made to the updated packages.
* Find more information in the `docu` directory of the media of {product}{nbsp}{this-version}.
  This directory includes PDF versions of the {product}{nbsp}{this-version} Installation Quick Start Guide.

[#intro-documentation-external]
==== Online Documentation

// beta
ifeval::["{lifecycle}" == "beta"]
* For the most up-to-date version of the documentation for {product}{nbsp}{this-version}, see {doc-url-beta} (draft version).
endif::[]
// maintained/unmaintained
ifeval::["{lifecycle}" != "beta"]
* For the most up-to-date version of the documentation for {product}{nbsp}{this-version}, see {doc-url}.
endif::[]
* Find a collection of White Papers in the {product} Resource Library at https://www.suse.com/products/sles-for-sap/#resources.

[#intro-documentation-baseproduct]
==== Identifying the Base Product
To identify and distinguish {suse} products, use one of the following files:

`/etc/os-release`::
    A text file with key-value pairs, similar to shell-compatible variable assignments. Each key is on a separate line.
+
    You can search for the `CPE_NAME` key; however, between different releases and service packs, the value has been changed. If you need further details, refer to the article at https://www.suse.com/support/kb/doc/?id=7023490. 

`/etc/product.d/baseproduct`::
    A link to an XML file. The /etc/product.d/ directory contains different `.prod` files.
+
    Depending on which products you have purchased and how you installed your system, the link `/etc/product.d/baseproduct` can point to a different `.prod` file, for example, `sle-module-sap-applications.prod`.
    The same information as in `CPE_NAME` is also stored in the tag `<cpeid>`. 


[#intro-lifecycle]
=== Support and Life Cycle


{product} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.

// bsc#1222560
{product} includes Extended Service Pack Overlay Support (ESPOS).
This provides an additional 3 years of support for each SP following the end of general support.
Combined with the standard 6 months overlay, it offers a total of 3.5 years of overlay support after the launch of the next Service Pack.

For more information, check our Support Policy page https://www.suse.com/support/policy.html or the Long Term Service Pack Support Page https://www.suse.com/support/programs/long-term-service-pack-support.html.


[#intro-support]
=== Support Statement for {product}

To receive support, you need an appropriate subscription with {suse}.
For more information, see {support-url}.

The following definitions apply:

L1::
Problem determination, which means technical support designed to provide compatibility information, usage support, ongoing maintenance, information gathering and basic troubleshooting using available documentation.
L2::
Problem isolation, which means technical support designed to analyze data, reproduce customer problems, isolate problem area and provide a resolution for problems not resolved by Level{nbsp}1 or prepare for Level{nbsp}3.
L3::
Problem resolution, which means technical support designed to resolve problems by engaging engineering to resolve product defects which have been identified by Level{nbsp}2 Support.

For contracted customers and partners, {product} is delivered with L3 support for all packages, except for the following:

* Technology Previews, see <<intro-techpreview>>
* Sound, graphics, fonts and artwork
// * Packages that require an additional customer contract, see <<intro-support-external>>
* Some packages shipped as part of the module _Workstation Extension_ are L2-supported only
* Packages with names ending in `-devel` (containing header files and similar developer resources) will only be supported together with their main packages.

{suse} will only support the usage of original packages. That is, packages that are unchanged and not recompiled.

[#intro-support-general]
==== General Support

To learn about supported features and limitations, refer to the following
sections in this document:

* <<changes>>
* <<knownIssues>>
// * <<removedDeprecated>>

// see fate#316990
//[#intro-support-external]
//==== Software Requiring Specific Contracts
//
// FIXME

==== SAP Support Statement

Make sure to also review the https://apps.support.sap.com/sap/support/pam[SAP Product Availability Matrix] and/or https://launchpad.support.sap.com/#/notes/2235581[SAP Note 2235581 - SAP HANA: Supported Operating Systems] for official SAP support and certification statements.


include::tech_previews.adoc[]
