[#changes]
== New Features, Changes & Fixes

Information in this section applies to all architectures supported by
{product} {this-version} unless noted otherwise.

[#jsc-SLE-4031]
=== Salt Automation

Salt automation for the deployment of {hana}, {nw} and DRBD was previously available as a technology preview from PackageHub.
In {slesap} {this-version}, this feature is now officially supported and has been added to the official repository.
This includes the following packages:

* `salt-shaptools`
* `python-shaptools`
* `saphanabootstrap-formula`
* `sapnwbootstrap-formula`
* `habootstrap-formula`
* `drbd-formula`

// TODO: add link to documentation, presentation and videos
For more information about deployment automation, see the official documentation at https://documentation.suse.com/sles-sap-15/.

[#new-packages-SAP]
=== Added Packages

The following packages have been added to {slesap} with {this-version}:

* `salt-shaptools`
* `python-shaptools`
* `saphanabootstrap-formula`
* `sapnwbootstrap-formula`
* `habootstrap-formula`
* `drbd-formula`

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
=== Example Entry

Issue explanation
	
////

[#bsc-1197511]
=== SAP native systemd support

In the past for Linux the systemV init service `sapinit` was starting the SAP Host Agent and all the `sapstartsrv` processes listed in `/usr/sap/sapservices`.
A real systemd integration was not available.

Now the native integration of SAP Host Agent is started via the `saphostagent.service` unit.
Adaptations to the `saphostagent.service` unit must be done by adding a so-called drop-in file.

For any native integrated SAP instance a systemd unit with name schema `SAP<SID>_<INO>` (for example, `SAPEN1_10`) is added.
Adaptations should be done using a drop-in file.
It is highly recommended to still use the `sapcontrol` functions which guarantees also the functionality of cluster integration like the `sap-suse-cluster-connector`.

Before you start your new installation or update to the native systemd integration, make sure you update the resource agent packages to the newest available versions.
The native SAP systemd integration is supported starting with the following package versions for {product} {this-ga}:

* resource-agents 4.4.0+git57.70549516-3.36.1
* sapstartsrv-resource-agents 0.9.0+git.1645795466.55a8cca-1.12.1
* SAPHanaSR 0.155.0
* SAPHanaSR-ScaleOut 0.181.0

For details please refer to the manual pages `ocf_suse_SAPStartSrv(7)`, `SAPHanaSR(7)`, and `SAPHanaSR-ScaleOut(7)`.