include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#development]
=== Development

// Release notes for development tool/library features:
//   JVM, Python, GCC, ...


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-PED-13352]
==== Support for Ansible interpreter

The Ansible packages (`ansible-core`) are included in {productname} 15 SP6 and newer.
Support is limited to any Ansible playbooks or roles that are provided by {suse} as part of {sles} or {smlm} products, whether supplied directly (for example, via packages, ISO images, ready-to-run images) or dynamically generated by integrated tools within these products.


[#bsc-1224313]
==== Python 3 packages staying in Basesystem

The `python311-base` and `libpython3_11-1_0` packages have been moved to the _Basesystem Module_ for technical reasons.
These two packages still follow the lifecycle of the _Python 3 Module_ and that is reflected in the metadata as well.


[#bsc-1220966]
==== `glibc` 2.38

The `glibc` package has been updated to version 2.38.

* A couple of internal `glibc` interfaces has changed; if an application uses these internal interfaces, the application needs fixing (note that internal interfaces should never be used)
* Split deprecated library `libnsl1` into separate package


// !STICKY
[#java-version]
==== Supported Java versions

The following Java implementations are available in {productname} {this-version}:

[WARNING]
IBM Java will be removed in {next-version}.

// relevant source: https://confluence.suse.com/display/SLE/Java
//                  https://confluence.suse.com/display/~msvec/Java+lifecycle+update
//             and: bsc#1171541

[cols="33%,17%,17%,33%" options="header"]
|===
|Name (Package Name)
|Version
|Module
|Support

|IBM Java +
(`java-1_8_0-ibm`)
|1.8.0
|Legacy
|External, until 2025-04-30

|OpenJDK +
(`java-1_8_0-openjdk`)
|1.8.0
|Legacy
|SUSE, L3, until 2026-12-31

|OpenJDK +
(`java-11-openjdk`)
|11
|Legacy
|SUSE, L3, until 2026-12-31

|OpenJDK +
(`java-17-openjdk`)
|17
|Legacy
|SUSE, L3, until 2027-12-31

|OpenJDK +
(`java-21-openjdk`)
|21
|Base System
|SUSE, L3, until 2031-06-30, pending upstream release
|===
