:this-version: 16.1
:idprefix: v161_
:doc-url: https://documentation.suse.com/sle-ha/16.1

:power-productname: {productname} {this-version} for POWER
:z-productname: {productname} {this-version} for {ibmz}


== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

// jsc#PED-13609
// jsc#PED-15556
[#jsc-PED-15556]
== Included packages and quarterly updates

Both the online medium and the full medium are the same for all SUSE Linux {this-version} products and only need to be downloaded once.
As the full medium includes all packages of the whole SUSE Linux {this-version} family, be aware that depending on your subscription the list of packages supported by {suse} varies.
You can check packages included in products on https://scc.suse.com.

Installation media, VM images and public cloud images are usually refreshed every 3 months (Quarterly Updates).


=== Changes affecting all architectures

// jsc#PED-14688
include::../shared.adoc[tags=jscped-14688,leveloffset=+3]

==== `csync2` requires separate initialization

Previously, csync2 was configured automatically during initial cluster bootstrap.
Customers who use csync2 can now run `crm cluster init csync2 -y` to set it up separately.


[#removed-deprecated]
=== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.

*  `sctp` support has been deprecated in `kronosnet` and to be removed upstream in 2.x
