:this-version: 16.0
:idprefix: v160_
:doc-url: https://documentation.suse.com/sle-ha/16.0

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures

// removed resource agents
include::../shared.adoc[tags=jscped-12354,leveloffset=+3]

[#bsc-1243146]
==== Changing when Home directory is created by default

Previously, creating a Home directory for an user when using the `useradd` command required the `-m` argument.

In {this-version}, this has been changed and the Home directory is created by default without using any additionalk arguments.

// simplified sbd management
include::../shared.adoc[tags=jscped-8258,leveloffset=+3]

[#jsc-PED-10881]
==== GSF2 available, OCFS2 removed

GFS2 (Global File System 2) is a native, shared-disk cluster filesystem for Linux, allowing multiple servers to concurrently read and write to the same block storage.
It uses a Distributed Lock Manager (DLM), typically integrated with Corosync and Pacemaker, to coordinate metadata access and prevent data corruption.

At the same time, the the support for OCFS2 has been removed.


=== Changes affecting all architectures (Beta2)

This section contains information specific to Beta2.
We are working on fixing the problems mentioned here.
The content of this section will be removed for the final released product.

[#bsc-1239436]
==== Unable to add `drbd_passive`

Attempting to add a `drbd_passive` resource into a pacemaker cluster results in several error messages.
This is due to a missing SELinux policy module.

As a workaround, set SELinux for the `drbd_t` domain to permissive mode via `semanage permissive -a drbd_t`.
After this bug has been fixed, switch it back enforcing mode via `semanage permissive -d drbd_t`.


[#bsc-1239084]
==== Cluster cannot be initialized

Running the `crm cluster init` command results in a Python error.

To resolve this, create home directory for the `hacluster` user:

[source,shell]
usermod -d /var/lib/pacemaker hacluster

[#removed-deprecated]
=== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.

// bsc-1252732
* Geo Clustering is not part of {productname} {this-version}.
Reach out to your sales contact to discuss your needs with the product team.
*  `sctp` support has been deprecated in `kronosnet` and to be removed upstream in 2.x
* <<jsc-PED-10881>>

