:this-version: 16.0
:idprefix: v160_
:doc-url: https://documentation.suse.com/sle-ha/16.0

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures (Beta2)

This section contains information specific to Beta2.
We are working on fixing the problems mentioned here.
The content of this section will be removed for the final released product.

[#bsc-1239436]
==== Unable to add `drbd_passive`

Attempting to add a `drbd_passive` resource into a pacemaker cluster results in several error messages.
This is due to a missing SELinux policy module.

As a workaround, set SELinux for the `drbd_t` domain to permissive mode via `semanage permissive -a drbd_t`.
After this bug has been fixed, switch it back enforcing mode via `semanage permissive -d drbd_t`.


[#bsc-1239084]
==== Cluster cannot be initialized

Running the `crm cluster init` command results in a Python error.

To resolve this, create home directory for the `hacluster` user:

[source,shell]
usermod -d /var/lib/pacemaker hacluster
