= Apptainer

* Update to version 1.3.6
** Avoid using kernel overlayfs when the lower layer is a sandbox on an
incompatible filesystem type such as GPFS or Lustre. For those cases use
fuse-overlayfs instead. This fixes a regression introduced in 1.3.0. The
regression didn’t much impact Lustre because kernel overlayfs refused to
try to use it and Apptainer proceeded to use fuse-overlayfs anyway, but
with GPFS the kernel overlayfs allowed mounting but returned stale file
handle errors.
* Version 1.3.5
** Fix a regression introduced in 1.3.4 that overwrote existing standard
`+/.singularity.d+` files such as `+runscript+` in container images even
if they had been modified.
** Skip attempting to bind inaccessible mount points when handling the
`+mount hostfs = yes+` configuration option.
** Support parsing nested variables defined inside `+%arguments+`
section of definition files.
** Ignore invalid environment variables when pulling oci/docker
containers.
* Version 1.3.4
** Fixed sif-embedded overlay partitions for containers that are larger
than 2 gigabytes.
** Fixed the failure when starting apptainer with
`+instance --fakeroot+`.
** `+apptainer build -B ...+` can now be used to mount custom
resolv.conf and hosts files from non-standard outside locations. This
can be used to run `+apptainer build+` in a nix-build sandbox that has
no `+/etc/resolv.conf+`.
** Fixed failing builds from local images that have symbolic links for
paths that are part of the base container environment (e.g. /var/tmp ->
/tmp).
** Show info messages suggesting to use `+enable underlay = preferred+`
or the `+--underlay+` flag when overlay is implied for bind mounts but
the kernel is too old to support fuse mounts in user namespaces and so
tries to use fusermount.
** When someone uses a `+yum+` bootstrap to build a container without
using subuid-based fakeroot or root, warn that it is unlikely to work.
** Allow a writable `+--overlay+` to be used with `+--nvccli+` instead
of `+--writable-tmpfs+`.
** If an error "`no descriptor found for reference`" is seen while
getting an oci container, retry the operation up to five times.
** Make fakeroot Recommended for SUSE rpms instead of Required.
** Allow bind mounts onto existing files on r/o NFS filesystems.
** If an error is seen in the %post section when building a container
using fakeroot mode 3 (with the fakeroot command) then show a message
suggesting using `+--ignore-fakeroot-command+` and referring to the
documentation about how to install and use it inside the container
definition file.
** Show a more helpful error message when using fakeroot in suid mode
and there’s an `+/etc/subuid+` mapping even though user namespaces are
not available (user namespaces are required for `+/etc/subuid+`
mapping).
* Version 1.3.3
** Added libcudadebugger.so to nvliblist.conf to support cuda-gdb in
CUDA 12+.
** Ensure opened/kept file descriptors in stage 1 are not closed during
the Go garbage collection to avoid "`bad file descriptor`" errors at
startup.
** Fixed a segmentation violation issue when running Apptainer
checkpoint.
** Fixed an issue that Apptainer won’t read default docker credentials.
* Version 1.3.2
** Fix for
https://bugzilla.suse.com/show_bug.cgi?id=1224114[CVE-2024-3727] in a
dependent library which describes a flaw that can allow attackers to
trigger unexpected authenticated registry accesses due to object digest
values not being validated in all cases.
** Fixed the issue when nesting `+apptainer instance start+` inside a
container on cgroups-v2 capable host.
** Fixed the issue that oras download progress bar gets stuck when
downloading large images.
* Version 1.3.1
** Make '`apptainer build`' work with signed Docker containers.
** Fixed regression introduced in 1.3.0 that prevented closing
cryptsetup and the corresponding loop device after running an encrypted
sif container file in suid mode.
** Stopped binding over the default timezone in the container with the
host’s timezone, which led to unexpected behavior if the application
changed timezones.
** Added progress bars for `+oras://+` push and pull.
** Hide `+Instance stats will not be available+` message under
`+--sharens+` mode.
** Fix problem where credentials locally stored with `+registry login+`
command were not usable in some execution flows. Run `+registry login+`
again with latest version to ensure credentials are stored correctly.
** Make runscript timeout configurable.
** Return invalid bind path mount options during bind path parsing.
** Make the INFO message more helpful when a running background process
at exit time causes a FUSE mount to not shut down cleanly.
** Fixed the wrong mediaType in the oras push manifest.
* Use go-jose version with fix for
https://bugzilla.suse.com/show_bug.cgi?id=1235211[CVE-2024-28180].