include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#removedDeprecated]
== Removed and Deprecated Features and Packages

This section lists features and packages that were removed from {product} or
will be removed in upcoming versions.

[NOTE]
.Package changes in {this-version}
For more information about all package changes since the last version, see <<intro-package-changes>>.


[#removedDeprecated-removed]
=== Removed Features and Packages

The following features and packages were removed from {product} {this-version}.

* <<bsc-1198973>>

// jsc#SLE-17839
* The `imgen` package, containing Mellanox firmware generator, has been removed in {product} {this-version}.


[#removedDeprecated-deprecated]
=== Deprecated Features and Packages

The following features and packages are deprecated and will be removed with a future service pack of {product}.

// bsc#1197374
* `gnome-documents` has been deprecated and will be removed from the media in the next release

////
[#<jsc-SLE-10978>]
==== Example Entry

NodeJS 8 will be discontinued in SUSE Linux Enterprise 15 SP3
////

