include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#rnotes]
= {rnotes}

include::abstract.adoc[]

include::about-rn.adoc[]

include::about-product.adoc[]

include::related.adoc[]

include::technology-previews.adoc[]

include::modules.adoc[]

// ===================================================================

// START ARCH-INDEPENDENT
[#all-architecture]
== Changes affecting all architectures

Information in this section applies to all architectures supported by {product} {this-version}.

[#jsc-PED-7684]
=== {producta} no longer a separate product

As of {this-version}, {product} is no longer a separate product. As a result:

* the HPC Module can now be enabled in {sles}
* when migrating from {product} 15 SP3, SP4, and SP5, only {sles} 15 SP6 will be available as migration target.
The result of such a migration will be an installation of {sles} with all the previously enabled modules.


[#jsc-SLE-24988]
=== Enriched system visibility in the {sccfull}

{suse} is committed to helping provide better insights into the consumption of {suse} subscriptions regardless of where they are running or how they are managed; physical or virtual, on-prem or in the cloud, connected to SCC or {rmtfull}, or managed by {suma}.
To help you identify or filter out systems in SCC that are no longer running or decommissioned, {suseconnect} now features a daily “ping”, which will update system information automatically.

For more details see the documentation at https://documentation.suse.com/subscription/suseconnect/single-html/SLE-suseconnect-visibility/.


[#jsc-SLE-22743]
=== Automatically opened ports

Installing the following packages automatically opens the following ports:

* `dolly` - TCP ports 9997 and 9998
* `slurm` - TCP ports 6817, 6818, and 6819


// updated packages
include::updated-packages.adoc[]

// Removed & deprecated packages & features
include::removed-deprecated.adoc[]

// END ARCH INDEPENDENT

// ===================================================================
include::source-code.adoc[]

include::legal.adoc[]

[appendix]
include::changelog.adoc[]
