:this-version: 16.0
:idprefix: v160_
:doc-url: https://documentation.suse.com/sles/16-GA

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures

[#bsc-1236813]
==== Non-functioning `zypper` after installation

There is currently a known issue that adds a non-functioning `zypper` repository which prevents `zypper` from working correctly.

To fix this issue, remove the repository in question and add the installation medium repository manually:

1. Remove repository with `zypper rr`, for example to remove the first repository: `zypper rr 1`
2. Add the installation medium as repository. For a DVD, do `zypper ar dvd:/`, for USB stick do `zypper ar hd:/`, for example: `zypper ar dvd:/?dvd=/dev/disk/by-label/agama-installer dvd` (the `dvd` at the end is a name you want to give the repository)
3. Do `zypper refresh` to refresh the added repository.


[#jsc-PED-6311]
==== systemd uses cgroup v2 by default

{productname} {this-version} uses cgroup v2 by default and v1 is unsupported.
If you need to use cgroup v1, {slesa} 15 SP6 can be switched to hybrid mode using a boot parameter.


[#removed-deprecated]
=== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.


// [NOTE]
// .Package and module changes in {this-version}
// For more information about all package and module changes since the last version, see <<intro-package-changes>>.


[#removed]
==== Removed features and packages

The following features and packages have been removed in this release.

* `netiucv` and `lcs` drivers


// [#deprecated]
// === Deprecated features and packages

////
1. Deprecations that will be removed in an upcoming service pack of current SLE major version:
2. Deprecations that will be removed in the next SLE major version:
3. Deprecations that will be removed later or where removal timing is unclear:
////

// The following features and packages are deprecated and will be removed in a future version of {product}.

// ===================================================================
