:this-version: 16.0
:next-version: 16.1
:idprefix: v160_
:doc-url: https://documentation.suse.com/sles/16-GA

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures

[#jsc-PED-12715]
==== Removal of 32-bit support

{productname} {this-version} only supports 64-bit binaries.
Support for 32-bit binaries (or 31-bit binaries on {ibmz}) has been removed.

This means that statically-linked 32-bit binaries (or 31-bit binaries on {ibmz}) and container images cannot be run anymore.
32-bit syscalls are still enabled by default on arm64, and can be enabled on x86_64 via the kernel parameter `ia32_emulation`.
On other architectures it's disabled without any option to enable it.


[#jsc-PED-12734]
==== Compiling kernel uses non-default compiler

Customers who need to build kernel modules or rebuild the kernel must use the same compiler version the kernel was built with.
The kernel is built with `gcc` version 13, which is not the default compiler.
Install the gcc version 13 compiler using the `gcc13` package and invoke it with the command `gcc-13`.
This specific compiler version is only supported for building kernel modules and the kernel.


[#jsc-PED-12297]
==== Optimized libraries for newer hardware architectures

We have added support for the glibc-HWCAPS feature which loads optimized versions of libraries for specific newer CPUs automatically.

The build infrastructure for this feature is enabled for the following libraries:

* `blosc2`
* `boost`
* `brotli`
* `bzip2`
* `flac`
* `jsoncpp`
* `lame`
* `leveldb`
* `libdb-4_8`
* `libgcrypt`
* `libiscsi`
* `libjpeg-turbo`
* `libjxl`
* `libmng`
* `libnettle`
* `libpng16`
* `libvorbis`
* `libxmlb`
* `lz4`
* `lzo`
* `openjpeg2`
* `openssl-3`
* `python311`
* `python313`
* `sqlite3`
* `talloc`
* `tree-sitter`
* `wavpack`
* `xxhash`
* `xz`
* `zlib`
* `zopfli`
* `zstd`


[#bsc-1240889]
==== No remote `root` login with password

[WARNING]
If you install the system using only a `root` password and do not provide an SSH key for the root user, `sshd` will not be enabled automatically after installation.
You will not be able to log in remotely as root using the password.

By default, remote password-based `root` login is disabled.
The installer enables the `sshd` service only when an SSH key for root is configured during setup.
To allow remote `root` login, configure an SSH key for root during installation.

include::../shared.adoc[tags=bsc1240989,leveloffset=+3]

[#jsc-PED-12156]
==== SysV init.d scripts support

SysV init.d scripts have been https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/index.html#jsc-SLE-7690[deprecated since {productnameshort} 15 SP2].

In {productnameshort} {this-version}, support of SysV init.d scripts has been removed.


=== Changes affecting all architectures (RC1)

[#jsc-PED-12189]
==== `/etc/services` removal

The `/etc/services` file is just a dummy file that will be removed in the future.
Software that appends to it without creating it should have its behavior changed.


=== Changes affecting all architectures (Beta4)

[#jsc-DOCTEAM-1848]
==== Configuring network interfaces during installation

Currently, the installer does not allow for setting up network interfaces using the UI.
However, in the meantime you can use dracut-like command-line options, for example:

[source]
ifname=<interface>:<MAC>
ip=<interface>:dhcp

Additionally, the `inst.copy_network` is not available in Beta4.


[#jsc-DOCTEAM-1829]
==== {sap} workloads on {productnameshort} {this-version}

For running {sap} workloads on {productname} {this-version}, do the following:

1. Run these commands after system installation:
[source,bash]
semanage boolean -m --on selinuxuser_execmod
semanage boolean -m --on unconfined_service_transition_to_unconfined_user
semanage permissive -a snapper_grub_plugin_t
restorecon -R /
2. Install {sap} workload or {hana}
3. Run `restorecon -R /`.

==== FIPS 140-3 not working properly

FIPS 140-3 installation has not been fully validated and may cause unexpected software failure or crashes. Therefore, we discourage you from using it on Beta4.

=== Changes affecting all architectures (Beta3)

[#jsc-DOCTEAM-1849]
==== Missing `libnsl.so.1` library

The `libnsl.so.1` library has been deprecated in {slesa} 15 and finally removed in {productname} {this-version}.

As a workaround for applications that cannot be installed without it (but presumaly do not use it for anything), we provide the `libnsl-stub1` package that includes ABI-compatible but otherwise function-less stub of the library file.


[#jsc-DOCTEAM-1767]
==== `firewalld` not usable with many interfaces

Due to an upstream bug, `firewalld` might take a long time or time out when adding many interfaces.
The error occurs when `firewalld` is restarted after applying such a configuration.
The following message appears in the system logs:
[source]
ERROR:dbus.proxies:Introspect error on :1.18:/org/fedoraproject/FirewallD1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply.
Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

See https://github.com/firewalld/firewalld/issues/1399 for more information.


=== Changes affecting all architectures (Beta2)

[#bsc-1237605]
==== Switch from YaST to Cockpit

{productname} {this-version} has switched from {yast} to Cockpit for manual system administration.
We have enhanced Cockpit with new modules with the intention to upstream them later.
Despite being functional, bugs might appear and features might be missing.

*New modules*

* `cockpit-subscriptions`: register, de-register and view {sle} registrations.
Does not work for unprivileged users yet.
* `cockpit-repositories`: add, remove, view repositories, change settings and refresh them.
Does not work for unprivileged users yet.
* `cockpit-packages`: show installed packages, search available repositories, install and uninstall packages.
Requires administrative access.
Be aware that there are no safety measures implemented as far as system usability goes.

*Enhanced modules*

* `cockpit-packagekit`: update packages from available repositories.
The module now allows to individually select packages to update.

*Upstream modules*

`cockpit`, `cockpit-bridge`, `cockpit-kdump`, `cockpit-machines`, `cockpit-networkmanager`, `cockpit-podman`, `cockpit-selinux`, `cockpit-storaged`, `cockpit-system`, `cockpit-ws`: these modules are updated to the recent stable base version 332 (or their respective).

*Default selection*

Installation of the pattern `cockpit` will pull in the following modules: `cockpit`, `cockpit-bridge`, `cockpit-networkmanager`, `cockpit-packagekit`, `cockpit-packages`, `cockpit-repos`, `cockpit-selinux`, `cockpit-storaged`, `cockpit-subscriptions`, `cockpit-system`, `cockpit-ws`.


[#jsc-DOCTEAM-1714]
==== `dovecot` 2.4 configuration upgrade

In {productname} {this-version} `dovecot` has been upgraded to version 2.4.
The configuration of this version is incompatible with the previous versions.

Configuration has to be updated manually.
For more information see https://doc.dovecot.org/2.4.0/installation/upgrade/2.3-to-2.4.html.


=== Changes affecting all architectures (Beta1)

ifeval::[{omit_sles_specific} == "true"]
[#jsc-DOCTEAM-1700]
==== What images are part of Beta1

===== Online installer based on Agama (same for SLES & SLES SAP):
- `agama-installer.aarch64-11.0.0-SLE-Beta1.iso`
- `agama-installer.ppc64le-11.0.0-SLE-Beta1.iso`
- `agama-installer.s390x-11.0.0-SLE-Beta1.iso`
- `agama-installer.x86_64-11.0.0-SLE-Beta1.iso`

===== Offline installer based on Agama
* SLES 16.0
- `SLES-16.0-ppc64le-Beta1.install.iso`
- `SLES-16.0-s390x-Beta1.install.iso`
- `SLES-16.0-x86_64-Beta1.install.iso`
* SLES SAP 16.0
- `SLES-SAP-Packages-16.0-ppc64le-Beta1.install.iso`
- `SLES-SAP-Packages-16.0-x86_64-Beta1.install.iso`

===== {minvm} and {minimg} images
- `SLES16-Minimal-Image.aarch64-RaspberryPi-Beta1.raw.xz`
- `SLES16-Minimal-Image.s390x-s390x-dasd-Beta1.raw.xz`
- `SLES16-Minimal-Image.s390x-s390x-dasd-Cloud-Beta1.raw.xz`
- `SLES16-Minimal-Image.s390x-s390x-fba-Beta1.raw.xz`
- `SLES16-Minimal-Image.s390x-s390x-fba-Cloud-Beta1.raw.xz`
- `SLES16-Minimal-VM.aarch64-Cloud-Beta1.qcow2`
- `SLES16-Minimal-VM.aarch64-kvm-Beta1.qcow2`
- `SLES16-Minimal-VM.s390x-s390x-Cloud-Beta1.qcow2`
- `SLES16-Minimal-VM.s390x-s390x-kvm-Beta1.qcow2`
- `SLES16-Minimal-VM.x86_64-Cloud-Beta1.qcow2`
- `SLES16-Minimal-VM.x86_64-kvm-and-xen-Beta1.qcow2`
- `SLES16-Minimal-VM.x86_64-MS-HyperV-Beta1.vhdx.xz`
- `SLES16-Minimal-VM.x86_64-VMware-Beta1.vmdk`
- `SLES16-Minimal-VM.x86_64-VMware-Beta1.vmx`

===== Packages images
- `SLES-HA-16.0-aarch64-Beta1-Debug.iso`
- `SLES-HA-16.0-aarch64-Beta1.iso`
- `SLES-HA-16.0-aarch64-Beta1-Source.iso`
- `SLES-HA-16.0-ppc64le-Beta1-Debug.iso`
- `SLES-HA-16.0-ppc64le-Beta1.iso`
- `SLES-HA-16.0-ppc64le-Beta1-Source.iso`
- `SLES-HA-16.0-s390x-Beta1-Debug.iso`
- `SLES-HA-16.0-s390x-Beta1.iso`
- `SLES-HA-16.0-s390x-Beta1-Source.iso`
- `SLES-HA-16.0-x86_64-Beta1-Debug.iso`
- `SLES-HA-16.0-x86_64-Beta1.iso`
- `SLES-HA-16.0-x86_64-Beta1-Source.iso`
- `SLES-Packages-16.0-aarch64-Beta1-Debug.iso`
- `SLES-Packages-16.0-aarch64-Beta1.iso`
- `SLES-Packages-16.0-aarch64-Beta1-Source.iso`
- `SLES-Packages-16.0-ppc64le-Beta1-Debug.iso`
- `SLES-Packages-16.0-ppc64le-Beta1.iso`
- `SLES-Packages-16.0-ppc64le-Beta1-Source.iso`
- `SLES-Packages-16.0-s390x-Beta1-Debug.iso`
- `SLES-Packages-16.0-s390x-Beta1.iso`
- `SLES-Packages-16.0-s390x-Beta1-Source.iso`
- `SLES-Packages-16.0-x86_64-Beta1-Debug.iso`
- `SLES-Packages-16.0-x86_64-Beta1.iso`
- `SLES-Packages-16.0-x86_64-Beta1-Source.iso`
- `SLES-SAP-Packages-16.0-ppc64le-Beta1-Debug.iso`
- `SLES-SAP-Packages-16.0-ppc64le-Beta1.iso`
- `SLES-SAP-Packages-16.0-ppc64le-Beta1-Source.iso`
- `SLES-SAP-Packages-16.0-x86_64-Beta1-Debug.iso`
- `SLES-SAP-Packages-16.0-x86_64-Beta1.iso`
- `SLES-SAP-Packages-16.0-x86_64-Beta1-Source.iso`
endif::[]

[#bsc-1235855]
==== Disk configuration UI during installation

Currently, choosing disk configurations other than "An existing disk" (installation to a single disk) suffer from poor usability.
This is expected to change in a future update.


[#bsc-1236813]
==== Non-functioning `zypper` after installation

There is currently a known issue that adds a non-functioning `zypper` repository which prevents `zypper` from working correctly.

To fix this issue, remove the repository in question and add the installation medium repository manually:

1. Remove repository with `zypper rr`. To remove the first repository, for example, run: `zypper rr 1`.
2. Add the installation medium as repository by running `zypper ar hd:/install?device=/dev/disk/by-label/agama-installer  medium` (the `medium` at the end is a name you want to give the repository).
3. Run `zypper refresh` to refresh the added repository.


[#jsc-PED-6311]
==== systemd uses cgroup v2 by default

{productname} {this-version} uses cgroup v2 by default and v1 is unsupported.
If you need to use cgroup v1, {slesa} 15 SP6 can be switched to hybrid mode using a boot parameter.

[#ibm-z]
=== IBM Z-specific changes (s390x)

[#bsc-1235858]
==== `parmfile` now points to ISO

Previously, `parmfile` would point to a directory of unpacked files.

Now it need to point to a loop-mounted ISO via FTP.
For example:

[source]
root=live:ftp://$SERVER_URL/install/agama-online.iso
agama.install_url=ftp://$SERVER_URL/install/agama

For more information see https://agama-project.github.io/docs/user/boot_options.


[#bsc-1235857]
==== Disk selection UI problems during installation

If you want to enable a disk, click on _Storage_ in the left panel, then _Install new system on_ and choose "storage techs".
Then you can choose a type of disk.
This can be avoided if you have defined your `parmfile` as described in <<bsc-1235858>>.

If you choose DASD, you should see disks based on your `parmfile` and `cio_ignore` configuration.
Then choose a disk and activate it by clicking _Perform an action_ and then _Activate_.
This can take a moment.
If it is not visible, then you need to click on Storage or refresh the page.

In the _zFCP_ section, after activating a disk a gray line will appear.
This is just a visual bug, the disk will activate correctly.


==== Installation failure on zVM

Due to a change from `linuxrc` to `dracut`, the `parmfile` needs to define not only installation source but also a network and disks.

The `parmfile` needs to be filled with a `dracut`-like options, for example:

[source]
root=live:ftp://$SERVER_URL/install/online.iso
ip=$IP_address::$IP_gateway:24:SLE16-Beta4:$NETWORK_DEVICE:none
rd.zdev=qeth,0.0.0800:0.0.0801:0.0.0802,layer2=1,portno=0
cio_ignore=all,!condev,!0.0.0160 nameserver=$NAMEserverIP
live.password=linux rd.zdev=dasd,0.0.0160

[#power]
=== POWER-specific changes (ppc64le)

Information in this section applies to {power-productname} {this-version}.

[#jsc-PED-12179]
==== KVM guests in LPAR

The ability to run KVM Guests in an LPAR is a new feature in PowerVM Firmware 1060.10 release and supported in {productname} {this-version}.
This enables users to run KVM guests in a PowerVM LPAR bringing industry standard Linux KVM virtualization stack to IBM PowerVM, which easily integrates with existing Linux virtualization ecosystem.
This enables a lot of interesting usecases which were earlier difficult to realize in a PowerVM LPAR.

KVM in a PowerVM LPAR is a new type of LPAR (logical partition) that allows the {productname} {this-version} kernel to host KVM guests inside an LPAR on PowerVM.
A KVM enabled LPAR allows standard Linux KVM tools (for example, `virsh`) to create and manage lightweight Linux Virtual Machines (VM).
A KVM Linux LPAR uses dedicated cores which enables Linux to have full control of when Linux VMs are scheduled to run, just like KVM on other platforms.

[#aarch64]
=== {arm}-specific changes ({aarch64})

include::../kernel-160-aarch64.adoc[leveloffset=+3]

[#virtualization]
=== Virtualization

// Release notes for virtualization:
//    KVM, libvirt, ...

[#virtualization-qemu]
//jsc-PED-8908
==== QEMU

QEMU has been updated to version 10.0.2, full list of changes are available at https://wiki.qemu.org/ChangeLog/10.0

Highlights include:
* Removed features: https://qemu-project.gitlab.io/qemu/about/removed-features.html
* Deprecated features: https://qemu-project.gitlab.io/qemu/about/deprecated.html

[#virtualization-libvirt]
// jsc-PED-8909
==== libvirt

`libvirt` has been updated to version 11.4.0, this include many incremental improvements and bug fixes, see https://libvirt.org/news.html#v11-4-0-2025-06-02.

`libvirt` provides now a modular daemons.

[#virtualization-vmware]
==== VMware

===== open-vm-tools

`open-vm-tools` has been updated to version 13.0.0 that addresses a few critical problems and bug fixes. See https://github.com/vmware/open-vm-tools/blob/stable-13.0.0/ReleaseNotes.md.

[#virtualization-other]
//jsc-PED-8910
==== Others

===== numatop

`numatop` is available in version 2.5, adding support for Intel GNR and SRF platforms.

===== numactl

`numactl` is shipped in version 2.0.19. Full changes at: https://github.com/numactl/numactl/releases/tag/v2.0.19

===== libguestfs

`libguestfs` has been updated to version 1.55.13.

===== virt-v2v

Update to version 2.7.16. While there are no dedicated release notes, you can review the code changes in Github: https://github.com/libguestfs/virt-v2v/tree/v2.7.16

- Implement --parallel=N for parallel disk copies
- Update Translations
- Various fixes

===== `sevctl`

The `sevctl` package has been updated to version 0.6.0.

===== `snpguest`

The `snpguest` package has been updated to version 0.9.1. Full list of changes is available at: https://github.com/virtee/snpguest/compare/v0.7.1...v0.9.1

===== `snphost`

The `snphost` packages has been added in version 0.6.0.

===== `virtiofsd`

The `virtiofsd` has been updated to 1.12.0.

===== `virt-manager`

`virt-manager` is now shipped in version 5.0.0. Its preferable to setup VNC for remote viewing and do all the XML editing using the `virsh` command.
Full list of changes is available at https://github.com/virt-manager/virt-manager/releases/tag/v5.0.0

===== virt-bridge-setup

virt-bridge-setup is a script designed to simplify network bridge creation on a specified interface using nmcli. It was developed as a replacement for the automatic "yast2 virtualization" bridge creation and is particularly useful for setting up virtualization environments.

Important considerations:
* It supports IPv4 only.
* This is a simple script not intended for complex network scenarios; manual bridge setup is recommended for intricate configurations.
* The script should be run immediately after post-installation and before any custom network configurations.

//jsc#PED-5824
===== Intel TDX Confidential Computing

We are pleased to announce that Kernel shipped in this release now incorporates the latest upstream Intel Trust Domain Extensions (TDX) patches. This significant update prepares the virtualization toolstack for Intel TDX confidential computing capabilities.

With these patches, the kernel is now ready to support the foundational requirements for creating and managing trust domains, a crucial step towards enabling confidential computing environments on Intel TDX-enabled hardware.

Important Note: While the kernel is now ready, the full Intel TDX confidential computing experience is not yet complete. Integration work is still in progress for the QEMU and Libvirt components. These elements are necessary to fully leverage and orchestrate Intel TDX features within your virtualized environments. We anticipate further updates in upcoming releases as these integrations are finalized.

[#removed-deprecated]
=== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.


// [NOTE]
// .Package and module changes in {this-version}
// For more information about all package and module changes since the last version, see <<intro-package-changes>>.


[#removed]
==== Removed features and packages

The following features and packages have been removed in this release.

* `netiucv` and `lcs` drivers
* `ansible-9` and `ansible-core-2.16`
* `criu`
* <<jsc-PED-12156>>


[#deprecated]
=== Deprecated features and packages

////
1. Deprecations that will be removed in an upcoming service pack of current SLE major version:
2. Deprecations that will be removed in the next SLE major version:
3. Deprecations that will be removed later or where removal timing is unclear:
////

The following features and packages are deprecated and will be removed in a future version of {productname}.

// jsc-PED-12744
* The 2MB OVMF image will be deprecated and removed in {productname} 16.1.
// * <<jsc-PED-12189>>

// ===================================================================
