== What's new?

=== Comparison with {productname} 15 SP7

To read more about the differences and high-level changes between {productname} 16.0 and {productname} 15 SP7, see these documents:

* https://documentation.suse.com/sles/16.0/html/SLE-differences-faq/
* https://documentation.suse.com/sles/16.0/html/SLE-comparison/


== Support and lifecycle

{productname} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.

The current version ({this-version}) will be fully maintained and supported until 31 Jul 2034.

If you need additional time to design, validate and test your upgrade plans, Long Term Service Pack Support can extend the support duration.
You can buy an additional 12 to 36 months in twelve month increments.
This means that you can receive support up to Dec 2037.

For more information, see the pages link:https://www.suse.com/support/policy.html[Support Policy], link:https://www.suse.com/support/programs/long-term-service-pack-support.html[Long Term Service Pack Support], and link:https://documentation.suse.com/sles/16.0/html/SLE-packages-lifecycle/index.html[Lifecycles of SUSE Linux Enterprise Components
].


=== Support statement for {productname}

To receive support, you need an appropriate subscription with {suse}.
For more information, see {support-url}.

The following definitions apply:

L1::
Problem determination, which means technical support designed to provide compatibility information, usage support, ongoing maintenance, information gathering, and basic troubleshooting using the documentation.
L2::
Problem isolation, which means technical support designed to analyze data, reproduce customer problems, isolate the problem area, and provide a resolution for problems not resolved by Level{nbsp}1 or prepare for Level{nbsp}3.
L3::
Problem resolution, which means technical support designed to resolve problems by engaging engineering to resolve product defects which have been identified by Level{nbsp}2 Support.

For contracted customers and partners, {productname} is delivered with L3 support for all packages, except for the following:

* Technology Previews, see <<technology-preview>>
* Sound, graphics, fonts and artwork
* Packages that require an additional customer contract, see <<intro-support-external>>
* Some packages shipped as part of the module _Workstation Extension_ are L2-supported only
* Packages with names ending in `-devel` (containing header files and similar developer resources) will only be supported together with their main packages.

{suse} will only support the usage of original packages. That is, packages that are unchanged and not recompiled.

=== General support

To learn about supported features and limitations, refer to the following
sections in this document:

// * <<kernel>>
// * <<storage>>
// * <<virtualization>>
* <<removed-deprecated>>

[#intro-support-external]
// see fate#316990, bsc#1161529
==== Software requiring specific contracts

Certain software delivered as part of {productname} may require an external contract.
Check the support status of individual packages using the RPM metadata that can be viewed with `rpm` or `zypper`.

Currently, there are no major packages and groups of packages affected by this.


// see jsc#SLE-7191
==== Software under GNU AGPL

////
How to create a list:
1. Go to https://scc.suse.com/packages
2. Choose product, version, pick x86_64 architecture, click Search
3. Download as CSV
4. Open in LibreOffice
5. Select entire table, Data > Pivot Table > Insert or Edit, click OK
6. Drag all column headers to Row Fields, OK
7. In License header, search for "agpl", pick all of those; in Module header, select everything but Package Hub
////

{productname} {this-version} (and the {sle} modules) includes the following software that is shipped __only__ under a GNU AGPL software license:

* Ghostscript (including subpackages)
* `velociraptor` and `velociraptor-client`
* `zypp-boot-plugin`

{productname} {this-version} (and the {sle} modules) includes the following software that is shipped under multiple licenses that include a GNU AGPL software license:

* MySpell dictionaries and LightProof
* ArgyllCMS

[#technology-preview]
=== Technology previews

Technology previews are packages, stacks, or features delivered by SUSE to provide glimpses into upcoming innovations. Technology previews are included for your convenience to give you a chance to test new technologies within your environment. We would appreciate your feedback! If you test a technology preview, contact your SUSE representative and let them know about your experience and use cases. Your input is helpful for future development.

Technology previews come with the following limitations:

* Technology previews are still in development. Therefore, they may be functionally incomplete, unstable, or in other ways not suitable for production use.
* Technology previews are not supported.
* Technology previews may only be available for specific hardware architectures. Details and functionality of technology previews are subject to change. As a result, upgrading to subsequent releases of a technology preview may be impossible and require a fresh installation.
* Technology previews can be removed from a product at any time. This may be the case, for example, if SUSE discovers that a preview does not meet the customer or market needs, or does not comply with enterprise standards.

[#jsc-PED-10703]
=== Boot Loader Specification (BLS) support with systemd-boot (technology preview)

{productname} {this-version} includes systemd-boot as a technology preview for Boot Loader Specification (BLS) support on UEFI systems.

The following limitations apply to this technology preview:

* Available only for UEFI-based {x64} and {aarch64} architectures.
* Not available for {ibmz}, POWER, or BIOS-based systems.
* Switching from the traditional grub2 bootloader to systemd-boot is not supported during an upgrade.
* A fresh installation is required to use systemd-boot.

Full support is planned for a future release.

// jsc#PED-13609
// jsc#PED-15556
[#jsc-PED-15556]
== Included packages and quarterly updates

Both the online medium and the full medium are the same for all SUSE Linux {this-version} products and only need to be downloaded once.
As the full medium includes all packages of the whole SUSE Linux {this-version} family, be aware that depending on your subscription the list of packages supported by {suse} varies.
You can check packages included in products on https://scc.suse.com.

Installation media, VM images and public cloud images are usually refreshed every 3 months (Quarterly Updates).

[#upgrade-checklist]
== Upgrade & Migration Quick Checklist

Before upgrading to {productname} {this-version}, review the following checklist of potential migration issues and preparation steps.

=== Before upgrading

* *Immutable Mode:* Immutable mode is unsupported for SAP workloads.
+
See <<jsc-PED-14664>>.

=== During upgrade

* *Installer Configuration:* Combustion tool is now included in the live installer image.
+
See <<jsc-PED-16271>>.

=== After upgrading

* *Database Migration:* The `update-alternatives` mechanism is no longer used for PostgreSQL.
+
See <<jsc-PED-16106>>.


== Changes affecting all architectures

// jsc#PED-12658
* `rasdaemon` has been updated to version 0.8.4. This version supports machine checks related to CXL memory. Since Intel® Optane™ Memory products have reached End of Life (EOL), {productname} {this-version} does not support them either.

// jsc#PED-15435
include::../shared.adoc[tags=jscped-15435,leveloffset=+2]

// jsc#PED-15454
include::../shared.adoc[tags=jscped-15454,leveloffset=+2]

// jsc#PED-15282
include::../shared.adoc[tags=jscped-15282,leveloffset=+2]

// bsc#1271333
include::../shared.adoc[tags=bsc1271333,leveloffset=+2]

[#jsc-PED-15707]
=== Login hint when attempting root login to {cockpit}

Direct root login to the {cockpit} web interface is disabled by default.
A login hint is now displayed upon a failed root login attempt to clarify that root access is disabled.
The hint also provides instructions on logging in with a regular account, elevating privileges, or enabling root access via `/etc/cockpit/disallowed-users`.


[#jsc-PED-15693]
=== Curated set of Ansible development and testing tools

Currently, {productname} ships only the Ansible runtime (`ansible-core` and `ansible`).
{productname} {this-version} introduces a curated set of Ansible development and testing tools.
These tools enable testing, linting, and building Ansible content.

The following packages are now included:

* `ansible-lint`: Playbook and role linter.
* `molecule`: Role and collection testing framework.
* `molecule-plugins`: Test drivers (Podman, Docker, Vagrant).
* `ansible-navigator`: TUI for playbook development and debugging.
* `ansible-builder`: Execution environment (container image) builder.
* `ansible-runner`: Ansible execution API (also a dependency of Navigator).
* `ansible-creator`: Provides commands to scaffold new Ansible projects and content.

// jsc#PED-15576
[#jsc-PED-15576]
=== IO scheduler distribution default changed

The distribution default has changed for a certain set of block devices: rotating disks that have only a single I/O queue. On {productnameshort}, such devices would previously be driven by the `bfq` I/O scheduler by default. Now we are using the same default as the kernel, which is `mq-deadline` for most devices, and `none` for some.

[#jsc-PED-15600]
=== New GCC warnings for Year 2038 (Y2K38) issues

To help identify and mitigate Year 2038 (Y2K38) 32-bit `time_t` rollover issues, GCC now provides new compile-time warnings.
These warnings highlight legacy 32-bit timestamp interactions in C/C++ code (such as file or network I/O using `int` types).
It is recommended to review these warnings and update affected code to use 64-bit structures where necessary.

[#jsc-PED-14664]
=== Immutable mode is unsupported for {sap} workloads

Running of the {sap} software stack is not supported in immutable mode:

* {sap}-specific packages including `saptune` and `Trento` are not supported in immutable mode.
* {sap} patterns are not supported in immutable mode.
* Ansible automation for {sap} is not supported in immutable mode.
* Execution of {hana}, {s4hana} and {nw} is not supported in immutable mode.

Note that this applies to traditional software.
{sap} software running in containers (like {sap} Edge Integration Cell) is supported in immutable mode.

[#jsc-PED-16106]
=== `update-alternatives` no longer used for PostgreSQL

To better support immutable systems and transactional updates, the `update-alternatives` mechanism is no longer used to set the default PostgreSQL version.
For more details on how to set the default PostgreSQL version, refer to the `README.SUSE` file provided in the `postgresql` main package.

// bsc#1268779
[#jsc-PED-16271]
=== Agama live image includes Combustion

To facilitate pre-installation configuration before launching the Agama installer, the Combustion tool is now included in the live installer image.
This provides a convenient and reliable way to apply complex setups repeatedly without typing commands manually, which also covers advanced scenarios that standard graphical tools cannot handle.

Combustion does not run automatically by default.
To run Combustion scripts, Combustion must be explicitly enabled by adding the `rd.systemd.wants=firstboot.target` boot option at the boot prompt.
Ignition is not included because its configuration mechanism is unsuitable for live installer media, and Combustion is better suited for pre-installation scripting.

[#jsc-PED-15142]
=== NVMeoF boot: network interfaces maintain standard names

For root-over-NVMeoF setups, in {productnameshort} 16.0 and prior releases, the network interfaces were renamed to `nbft0`, `nbft1`, and so on.
In {productnameshort} {this-version}, on new installations, network interfaces keep their standard names.


[#jsc-PED-15924]
=== Kernel switches to PREEMPT_LAZY preemption model

The upstream kernel community has moved away from conservative scheduler preemption models (`PREEMPT_NONE` and `PREEMPT_VOLUNTARY`), and these models have been removed in kernel 7.0 for architectures that support `PREEMPT_LAZY`.
To align with upstream changes, {productname} {this-version} switches the preemption model from `PREEMPT_VOLUNTARY` to `PREEMPT_LAZY` for all supported architectures, except for {ibmz} (`s390x`), which lacks architectural support.

The `PREEMPT_LAZY` model provides a less conservative approach to preemption, while still being suitable for throughput-oriented workloads.
If you experience performance issues with the new preemption model, you can optionally switch back to `PREEMPT_VOLUNTARY` by setting `preempt=voluntary` on the kernel command line.


[#bsc-1261338]
=== RAID configuration not supported in installer Web UI

RAID configuration is currently not supported through the installer Web UI.
As a workaround, you can configure RAID either manually via the command line or by using JSON or JSONNet storage profiles.
For more information, see https://agama-project.github.io/docs/user/reference/profile/storage.
RAID support in the installer Web UI is planned for a future release.


[#jsc-PED-15457]
=== Support for NTP configuration in early boot and the Agama installer

Network time synchronization is now supported during both the early boot phase and the installation process.
Specifying an NTP server IP address or hostname using the new `rd.ntp=<server>` kernel command-line parameter enables time synchronization before the installer launches, ensuring accurate log timestamps and correct HTTPS certificate validation.
The Agama installer supports NTP configuration through a dedicated `ntp` section in the installer profile or via input fields in the user interface.
Legacy AutoYaST `ntp-client` configurations are automatically converted into the native `ntp` configuration block on profile import.
The configured NTP settings are written to the target system to persist after installation.


include::../shared.adoc[tags=jscped-15932,leveloffset=+2]

include::../shared.adoc[tags=jscped-11986,leveloffset=+2]

[#jsc-PED-15636]
=== Multiple LSMs enabled by default

{selinux} is now used as the primary LSM (Linux Security Module) as compared to {apparmor} that was used previously.

Apart from {selinux}, we have also enabled:

* Yama
* Landlock
* Lockdown
* other virtual ones like bpf, ima, evm, capability

==== Yama

Yama is a global framework that collects system-wide DAC security protections that are not handled by the core kernel itself.
Individual processes can disable Yama for themselves.
The enablement of Yama disables the `ptrace` mechanism of processes by default, except in the following cases:

* Processes explicitly allow it themselves via `prctl(PR_SET_PTRACER)`.
* The tracer is a parent of the traced process (for example, when running `gdb program`).

Global control is managed via the `sysctl` parameter `/proc/sys/kernel/yama/ptrace_scope`, which sits on top of standard `ptrace` permissions.
It supports the following levels:

* `0`: Normal, classical `ptrace` is possible.
* `1`: Only a parent process can be traced.
* `2`: Only administrators with the `CAP_SYS_PTRACE` capability can use `ptrace`.
* `3`: No processes may be traced with `ptrace`.
Once this level is set, a system reboot is required to enable tracing again.

To enable `ptrace` system-wide again after the next reboot, install the `aaa_base-yama-enable-ptrace` package.

==== Landlock

Landlock is a local security framework where processes can voluntarily confine their own actions.
It provides scoped access-control (sandboxing) limited to file system and socket actions.
Refer to the `landlock` manual pages for more details.

==== Lockdown

Lockdown is a kernel-based lockdown method.
The kernel supports three lockdown states:

* `none`
* `integrity`: Maximum integrity protection, which avoids any kind of outside code injection into the kernel or physical RAM.
* `confidentiality`: Same as `integrity`, but additionally prevents any extraction of information (even by the `root` user) from other processes or physical RAM.

The lockdown level can be set during boot.
By default, the level is set to `none`, but for Secure Boot, `integrity` is the lowest default level.
During runtime, the lockdown level can only be increased, and cannot be decreased.


[#jsc-PED-14304]
=== Consistent location for kernel and initramfs across architectures

Previously, location of kernel or initrams would differ based on architecture.

Now these are stored in the same location regardless of architecture: [path]``boot/$arch/loader/``

// !STICKY
[#development-java-versions]
=== Supported Java Versions

The following table lists Java implementations available in {sles} {this-version}:

[cols="40%,20%,20%" options="header"]
|===
|Package Name
|Version
|Support

|`java-17-openjdk`
|17
|SUSE, L3, until 2027-10-31

|`java-21-openjdk`
|21
|SUSE, L3, until 2031-10-31

|`java-25-openjdk`
|25
|SUSE, L3, until 2033-10-31
|===


// == {x64}-specific changes

// Information in this section applies to the {x64} architecture.

[#aarch64]
== {arm}-specific changes ({aarch64})

include::../kernel-161-aarch64.adoc[leveloffset=+2]


[#ibm-z]
== {ibmz}-specific changes (s390x)

Information in this section applies to {z-productname}.
For more information, see https://www.ibm.com/docs/en/linux-on-systems?topic=distributions-suse-linux-enterprise-server

include::../shared.adoc[tag=jscped-15968,leveloffset=+2]

// == POWER-specific changes (ppc64le)

// Information in this section applies to {power-productname}.

// == {arm}-specific changes ({aarch64})

// include::../kernel-160-aarch64.adoc[leveloffset=+2]

[#virtualization]
== Virtualization

// Release notes for virtualization:
//    KVM, libvirt, ...

// bsc#1245454
* iSCSI boot support is disabled in OVMF images.


[#virtualization-qemu]
//jsc-PED-14599
=== QEMU

QEMU has been updated to version 11.0.0.
The full list of changes is available at https://wiki.qemu.org/ChangeLog/11.0.

Highlights include:
* Removed features: https://qemu-project.gitlab.io/qemu/about/removed-features.html
* Deprecated features: https://qemu-project.gitlab.io/qemu/about/deprecated.html

[#virtualization-libvirt]
// jsc-PED-14623
=== libvirt

`libvirt` has been updated to version 12.3.0.
This release includes incremental improvements and bug fixes (see https://libvirt.org/news.html#v12-3-0-2026-05-02).
`libvirt` now provides modular daemons.

[#virtualization-vmware]
=== VMware

==== open-vm-tools

`open-vm-tools` has been updated to version 13.1.0, addressing critical problems and bugs.
See the release notes at https://github.com/vmware/open-vm-tools/blob/stable-13.1.0/ReleaseNotes.md.

[#virtualization-confidential-computing]
=== Confidential Computing

==== `sevctl`

The `sevctl` package has been updated to version 0.6.2.

==== `snpguest`

The `snpguest` package has been updated to version 0.10.0.
The full list of changes is available at https://github.com/virtee/snpguest/compare/v0.9.1...v0.10.0.

==== `snphost`

The `snphost` package has been updated to version 0.7.0.

//jsc#PED-15646
[#intel-tdx-confidential-computing]
==== Intel TDX Confidential Computing

Intel TDX is supported in {productname} {this-version}.

As a technology preview, remote attestation is available via the following packages:

* `confidential-computing.sgx`
* `confidential-computing.tee.dcap.pccs`
* `guest-components`
* `suse-libsgx-prebuilt-signed`
* `trustee`

[#virtualization-other]
//jsc-PED-14624
=== Other tools

==== numatop

`numatop` is available in version 2.5, adding support for Intel GNR and SRF platforms.

==== numactl

`numactl` is shipped in version 2.0.19.
The full changelog is available at https://github.com/numactl/numactl/releases/tag/v2.0.19.

==== libguestfs

`libguestfs` has been updated to version 1.58.1.

==== virt-v2v

`virt-v2v` has been updated to version 2.10.0.
The code changes are available at https://github.com/libguestfs/virt-v2v/tree/v2.10.0.

- Implement `--parallel=N` for parallel disk copies.
- Update translations.
- Various fixes.

==== `virtiofsd`

The `virtiofsd` package has been updated to version 1.12.0.

==== `virt-manager`

`virt-manager` is now shipped in version 5.1.0.
Using VNC for remote viewing and editing XML configuration directly with the `virsh` command is recommended.
The full list of changes is available at https://github.com/virt-manager/virt-manager/releases/tag/v5.1.0.

==== virt-bridge-setup

`virt-bridge-setup` is a script designed to simplify network bridge creation on a specified interface using `nmcli`.
It was developed as a replacement for the automatic `yast2 virtualization` bridge creation and is particularly useful for setting up virtualization environments.

Important considerations:

* It supports IPv4 only.
* This is a simple script not intended for complex network scenarios (VLAN, bonding, etc.).
* Manual bridge setup is recommended for intricate configurations.
* The script should be run locally (not remotely) immediately after installation and before any custom network configurations.



[#removed-deprecated]
== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.


// [NOTE]
// .Package and module changes in {this-version}
// For more information about all package and module changes since the last version, see <<intro-package-changes>>.


// [#removed]
// === Removed features and packages

// The following features and packages have been removed in this release.


[#deprecated]
=== Deprecated features and packages

////
1. Deprecations that will be removed in an upcoming service pack of current SLE major version:
2. Deprecations that will be removed in the next SLE major version:
3. Deprecations that will be removed later or where removal timing is unclear:
////

The following features and packages are deprecated and will be removed in a future version of {productname}.

// jsc#PED-16439
* Support for AF_ALG sockets (the `CONFIG_CRYPTO_USER_API` kernel configuration) is deprecated in {productname} 16.1 and will be removed in {productname} 16.2.

// jsc#PED-13429
* The packages `qemu-ovmf-ia32` and `qemu-uefi-aarch32` have been deprecated in {productname} 16.1 and will be dropped in a future release.
This is because the `edk2` upstream community is ending support for IA-32 and AArch32 OVMF.
// jsc#PED-15579
* The `opa-fmgui` package has been deprecated since 15 SP4 and will be removed in {productnameshort} {next-version}.
// jsc#PED-15392
* `nodejs22` has been removed.
// jsc-PED-12744
* The 2MB OVMF image has been removed in {productname} 16.1.
// jsc#PED-15569
* The `openmpi4` package has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
// jsc#PED-15546
* The `mvapich2` package has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
// jsc#PED-15368
* The `dmraid` package (Device-Mapper Software RAID Support Tool) has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
Use `mdadm` instead to manage and monitor software RAID devices.
// jsc#PED-15527
* The `qib` driver has been deprecated in {productname} 16.1 and will be removed in {productname} 16.2.
// ===================================================================
