== What's new?

=== Comparison with {productname} 15 SP7

To read more about the differences and high-level changes between {productname} 16.0 and {productname} 15 SP7, see these documents:

* https://documentation.suse.com/sles/16.0/html/SLE-differences-faq/
* https://documentation.suse.com/sles/16.0/html/SLE-comparison/


== Support and lifecycle

{productname} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.

The current version ({this-version}) will be fully maintained and supported until 31 Jul 2034.

If you need additional time to design, validate and test your upgrade plans, Long Term Service Pack Support can extend the support duration.
You can buy an additional 12 to 36 months in twelve month increments.
This means that you can receive support up to Dec 2037.

For more information, see the pages link:https://www.suse.com/support/policy.html[Support Policy], link:https://www.suse.com/support/programs/long-term-service-pack-support.html[Long Term Service Pack Support], and link:https://documentation.suse.com/sles/16.0/html/SLE-packages-lifecycle/index.html[Lifecycles of SUSE Linux Enterprise Components
].


=== Support statement for {productname}

To receive support, you need an appropriate subscription with {suse}.
For more information, see {support-url}.

The following definitions apply:

L1::
Problem determination, which means technical support designed to provide compatibility information, usage support, ongoing maintenance, information gathering, and basic troubleshooting using the documentation.
L2::
Problem isolation, which means technical support designed to analyze data, reproduce customer problems, isolate the problem area, and provide a resolution for problems not resolved by Level{nbsp}1 or prepare for Level{nbsp}3.
L3::
Problem resolution, which means technical support designed to resolve problems by engaging engineering to resolve product defects which have been identified by Level{nbsp}2 Support.

For contracted customers and partners, {productname} is delivered with L3 support for all packages, except for the following:

* Technology Previews, see <<technology-preview>>
* Sound, graphics, fonts and artwork
* Packages that require an additional customer contract, see <<intro-support-external>>
* Some packages shipped as part of the module _Workstation Extension_ are L2-supported only
* Packages with names ending in `-devel` (containing header files and similar developer resources) will only be supported together with their main packages.

{suse} will only support the usage of original packages. That is, packages that are unchanged and not recompiled.

=== General support

To learn about supported features and limitations, refer to the following
sections in this document:

// * <<kernel>>
// * <<storage>>
// * <<virtualization>>
* <<removed-deprecated>>

[#intro-support-external]
// see fate#316990, bsc#1161529
==== Software requiring specific contracts

Certain software delivered as part of {productname} may require an external contract.
Check the support status of individual packages using the RPM metadata that can be viewed with `rpm` or `zypper`.

Currently, there are no major packages and groups of packages affected by this.


// see jsc#SLE-7191
==== Software under GNU AGPL

////
How to create a list:
1. Go to https://scc.suse.com/packages
2. Choose product, version, pick x86_64 architecture, click Search
3. Download as CSV
4. Open in LibreOffice
5. Select entire table, Data > Pivot Table > Insert or Edit, click OK
6. Drag all column headers to Row Fields, OK
7. In License header, search for "agpl", pick all of those; in Module header, select everything but Package Hub
////

{productname} {this-version} (and the {sle} modules) includes the following software that is shipped __only__ under a GNU AGPL software license:

* Ghostscript (including subpackages)
* `velociraptor` and `velociraptor-client`
* `zypp-boot-plugin`

{productname} {this-version} (and the {sle} modules) includes the following software that is shipped under multiple licenses that include a GNU AGPL software license:

* MySpell dictionaries and LightProof
* ArgyllCMS

[#technology-preview]
=== Technology previews

Technology previews are packages, stacks, or features delivered by SUSE to provide glimpses into upcoming innovations. Technology previews are included for your convenience to give you a chance to test new technologies within your environment. We would appreciate your feedback! If you test a technology preview, contact your SUSE representative and let them know about your experience and use cases. Your input is helpful for future development.

Technology previews come with the following limitations:

* Technology previews are still in development. Therefore, they may be functionally incomplete, unstable, or in other ways not suitable for production use.
* Technology previews are not supported.
* Technology previews may only be available for specific hardware architectures. Details and functionality of technology previews are subject to change. As a result, upgrading to subsequent releases of a technology preview may be impossible and require a fresh installation.
* Technology previews can be removed from a product at any time. This may be the case, for example, if SUSE discovers that a preview does not meet the customer or market needs, or does not comply with enterprise standards.

[#jsc-PED-10703]
=== Boot Loader Specification (BLS) support with systemd-boot (technology preview)

{productname} {this-version} includes systemd-boot as a technology preview for Boot Loader Specification (BLS) support on UEFI systems.

The following limitations apply to this technology preview:

* Available only for UEFI-based {x64} and {aarch64} architectures.
* Not available for {ibmz}, POWER, or BIOS-based systems.
* Switching from the traditional grub2 bootloader to systemd-boot is not supported during an upgrade.
* A fresh installation is required to use systemd-boot.

Full support is planned for a future release.


== Changes affecting all architectures

[#jsc-PED-16271]
=== Agama live image includes Ignition and Combustion

To facilitate pre-installation configuration before launching the Agama installer, the Ignition and Combustion tools are now included in the live installer image.
This provides a convenient and reliable way to apply complex setups repeatedly without typing commands manually, which also covers advanced scenarios that standard graphical tools cannot handle.

[#jsc-PED-15142]
=== NVMeoF boot: network interfaces maintain standard names

For root-over-NVMeoF setups, in {productnameshort} 16.0 and prior releases, the network interfaces were renamed to `nbft0`, `nbft1`, and so on.
In {productnameshort} {this-version}, on new installations, network interfaces keep their standard names.


[#jsc-PED-15924]
=== Kernel switches to PREEMPT_LAZY preemption model

The upstream kernel community has moved away from conservative scheduler preemption models (`PREEMPT_NONE` and `PREEMPT_VOLUNTARY`), and these models have been removed in kernel 7.0 for architectures that support `PREEMPT_LAZY`.
To align with upstream changes, {productname} {this-version} switches the preemption model from `PREEMPT_VOLUNTARY` to `PREEMPT_LAZY` for all supported architectures, except for {ibmz} (`s390x`), which lacks architectural support.

The `PREEMPT_LAZY` model provides a less conservative approach to preemption, while still being suitable for throughput-oriented workloads.
If you experience performance issues with the new preemption model, you can optionally switch back to `PREEMPT_VOLUNTARY` by setting `preempt=voluntary` on the kernel command line.


[#bsc-1261338]
=== RAID configuration not supported in installer Web UI

RAID configuration is currently not supported through the installer Web UI.
As a workaround, you can configure RAID either manually via the command line or by using JSON or JSONNet storage profiles.
For more information, see https://agama-project.github.io/docs/user/reference/profile/storage.
RAID support in the installer Web UI is planned for a future release.


include::../shared.adoc[tags=jscped-15932,leveloffset=+2]

include::../shared.adoc[tags=jscped-11986,leveloffset=+2]

[#jsc-PED-15636]
=== Multiple LSMs enabled by default

{selinux} is now used as the primary LSM (Linux Security Module) as compared to {apparmor} that was used previously.

Apart from {selinux}, we have also enabled:

* Yama - collects system-wide DAC security protections that are not handled by the core kernel itself
* Landlock - scoped access-control (that is, sandboxing)
* Lockdown - kernel image access prevention feature
* other virtual ones like bpf, ima, evm, capability


[#jsc-PED-14304]
=== Consistent location for kernel and initramfs across architectures

Previously, location of kernel or initrams would differ based on architecture.

Now these are stored in the same location regardless of architecture: [path]``boot/$arch/loader/``

// !STICKY
[#development-java-versions]
=== Supported Java Versions

The following table lists Java implementations available in {sles} {this-version}:

[cols="40%,20%,20%" options="header"]
|===
|Package Name
|Version
|Support

|`java-17-openjdk`
|17
|SUSE, L3, until 2027-10-31

|`java-21-openjdk`
|21
|SUSE, L3, until 2031-10-31

|`java-25-openjdk`
|25
|SUSE, L3, until 2033-10-31
|===


// == {x64}-specific changes

// Information in this section applies to the {x64} architecture.


[#ibm-z]
== {ibmz}-specific changes (s390x)

Information in this section applies to {z-productname}.
For more information, see https://www.ibm.com/docs/en/linux-on-systems?topic=distributions-suse-linux-enterprise-server

include::../shared.adoc[tag=jscped-15968,leveloffset=+2]

// == POWER-specific changes (ppc64le)

// Information in this section applies to {power-productname}.

// == {arm}-specific changes ({aarch64})

// include::../kernel-160-aarch64.adoc[leveloffset=+2]

[#removed-deprecated]
== Removed and deprecated features and packages

This section lists features and packages that were removed from {productname} or will be removed in upcoming versions.


// [NOTE]
// .Package and module changes in {this-version}
// For more information about all package and module changes since the last version, see <<intro-package-changes>>.


// [#removed]
// === Removed features and packages

// The following features and packages have been removed in this release.


[#deprecated]
=== Deprecated features and packages

////
1. Deprecations that will be removed in an upcoming service pack of current SLE major version:
2. Deprecations that will be removed in the next SLE major version:
3. Deprecations that will be removed later or where removal timing is unclear:
////

The following features and packages are deprecated and will be removed in a future version of {productname}.

// jsc#PED-13429
* The packages `qemu-ovmf-ia32` and `qemu-uefi-aarch32` have been deprecated in {productname} 16.1 and will be dropped in a future release.
This is because the `edk2` upstream community is ending support for IA-32 and AArch32 OVMF.
// jsc#PED-15579
* The `opa-fmgui` package has been deprecated since 15 SP4 and will be removed in {productnameshort} {next-version}.
// jsc#PED-15392
* `nodejs22` has been removed.
// jsc-PED-12744
* The 2MB OVMF image has been removed in {productname} 16.1.
// jsc#PED-15569
* The `openmpi4` package has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
// jsc#PED-15546
* The `mvapich2` package has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
// jsc#PED-15368
* The `dmraid` package (Device-Mapper Software RAID Support Tool) has been deprecated in {productname} 16.1 and will be dropped in {productname} 16.2.
Use `mdadm` instead to manage and monitor software RAID devices.
// ===================================================================
