include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#container]
=== Containers

// Release notes for containers:
//    LXC, Docker, Podman, ...

// Also see the following additional note:

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-PED-1805]
==== Podman upgrade from 3.4.x to 4.3.1

Podman 4.x is a major release with 60 new features and more than 50 bug fixes compared to Podman 3.
It also includes a complete rewrite of the network stack.

Podman 4.x brings a new container network stack based on https://github.com/containers/netavark[Netavark], the new container network stack and https://github.com/containers/aardvark-dns[Aardvark DNS server] in addition to the existing container network interface (CNI) stack used by Podman 3.x . The new stack brings 3 important improvement:

 * Better support for containers in multiple networks
 * Better IPv6 support
 * Better performance

To ensure that nothing break with this major change, the old CNI stack will remain the default on existing installations, while new installs will use Netavark.

New installations can opt to use CNI by explicitly specifying it via the `containers.conf` configuration file, using the `network_backend` field.

If you have run Podman 3.x before upgrading to Podman 4, Podman will continue to use CNI plugins as it had before.
There is a marker in Podman's local storage that indicates this.
In order to begin using Podman 4, you need to destroy that marker with `podman system reset`.
This will destroy the marker, all of the images, all of the networks, and all of the containers.

[WARNING]
Before testing Podman 4 and the new network stack, you will have to destroy all your current containers, images, and networks.
You must export/save any import containers or images on a private registry, or make sure that your Dockerfiles are  available for rebuilding and scripts/playbooks/states to reapply any settings, regenerate secrets, etc.

Last but not least CNI will be deprecated from upstream at a future date: https://github.com/containers/podman/tree/main/cni

For a complete overview of the changes, please check out the upstream https://github.com/containers/podman/releases/tag/v4.0.0[4.0.0] but also https://github.com/containers/podman/releases/tag/v4.1.1[4.1.1], https://github.com/containers/podman/releases/tag/v4.2.0[4.2.0] and https://github.com/containers/podman/releases/tag/v4.3.0[4.3.0] to be informed about all the new features and changes.



// !STICKY
[#jsc-SLE-15587]
==== `suse/sle15` container uses NDB as the database back-end for RPM

Starting with {sle} 15{nbsp}SP3, the `rpm` package in the `suse/sle15` container image no longer supports the BDB back-end (based on Berkeley DB) and switches to the NDB back-end.
Tools for scanning, diffing, and building container image using the `rpm` binary of the host for introspection can fail or return incorrect results if the host's version of `rpm` does not recognize the NDB format.

To use such tools, make sure that the host supports reading NDB databases, such as hosts with {sle} 15{nbsp}SP2 and later.
