include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#development]
=== Development

////
Also see the following additional note:

* <<#jsc-SLE-16764>>
////

// Release notes for development tool/library features:
//   JVM, Python, GCC, ...


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-PED-13352]
==== Support for Ansible interpreter

The Ansible packages (`ansible-core`) are included in {productname} 15 SP6 and newer.
Support is limited to any Ansible playbooks or roles that are provided by {suse} as part of {sles} or {suma} products, whether supplied directly (for example, via packages, ISO images, ready-to-run images) or dynamically generated by integrated tools within these products.


[#jsc-PED-3799]
// tag::python3module[]
==== Alternative modern Python 3 interpreter upgraded to Python 3.11

// bsc#1222226
[WARNING]
.Changing system Python is not supported
Changing the system Python interpreter (located at `/usr/bin/python3`) is not supported.
The recommended method of using non-system Python is an explicit shebang in the script file or using a virtual environment.

{slea} 15 comes with a complete stack of Python 3.6 (interpreter, setuptools, wheel, pip plus hundreds of  modules).
Python 3.6 is fully supported by {suse} throught the __complete__ lifecycle of {slea} 15.

However, there are very few `pip` installable modules that are still compatible with 3.6 or older.
Therefore, starting with {slea} 15 SP4, {suse} introduced a new __Python{nbsp}3__ Module.
It includes additional modern Python interpreter (plus `setuptool`, `wheel`, `pip` and pypi support, but no additional modules).
This new allows more flexibility in providing a fully supported more recent Python interpreter in {slea}.

Packages within the Python{nbsp}3 module can be installed alongside existing Python packages and they can coexist within the same system without impacting any ongoing Python 3.6 workloads.

In {slea} 15 SP5 the Python{nbsp}3 Module ships with Python 3.11.

In {slea} 15 SP4, which originally shipped with Python 3.10, Python 3.11 packages have been added in addition to the existing Python 3.10 packages.
If you are using Python 3.10 in {slea} 15 SP4 make sure to update the packages from the Python{nbsp}3 Module to version 3.11 before upgrading to {slea} SP5.

{slea} 15 SP3 was shipped with the alternative Python version 3.9 included in __Basesystem__ Module.
//Because Python 3.9 is no longer supported in {producta} {this-version}, when upgrading to either {slea} 15 SP4 or SP5 on a system using Python 3.9, the new Python{nbsp}3 Module is automatically activated, so no manual intervention is needed.

Python 3.11 is compatible with versions 3.10 and 3.9. Code written in 3.9 or 3.10 should run without or with only minimal changes in 3.11.
// end::python3module[]

===== Details

Although fully supported throughout the entire lifecycle of {slea} 15, Python 3.6 is no longer developed by the Python community and it won't any receive new functionality.
Providing a modern Python versions as an alternative allows you to migrate to the newer version and to benefit from increased performance, compatibility with the latest syntax and new standard library versions.
You will also be able to utilize contemporary modules provided by pypi.org.

The Python 3.11 interpreter and the SUSE provided Python modules will be supported in {slea} 15 until at least 31st of December 2027.
The interpreter will be regularly updated to the latest patch version.
The Python modules will remain stable unless there is a security vulnerabiltiy or other significant issues.
In such cases, the preferred approach will be to backport patches and maintain the released version.

* Added Python 3.11 interpreter and a basic set of modules (see the https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=15.4&arch=x86_64&query=python311&module=2405[module's package list] for details)
** All python 3.11 packages are prefixed with `python311-` to distinguish from the default (3.6) Python packages
** Comes with significant performance improvments compared to Python 3.6
** Compatible to Python 3.10 and 3.9
** Supported on SLE 15 until at least 2027-12-31
* The Python{nbsp}3 Module containing Python 3.11 will be activated by default
* The Python 3.6 interpreter and modules stay the default and remain supported throughout the {slea} 15 lifecycle.
* We will continue delivering new interpreters (along with the respective `setuptools`/`wheel`/`pip` and pypi support, but no additional modules) with the Python{nbsp}3 Module with each new service pack.

[#jsc-SLE-20308]
===== TCK compliance testing in {sle}

We run the TCK test suite provided by Oracle to ensure that our version of OpenJDK is in compliance with the Java specification.


// !STICKY
[#java-version]
==== Supported Java versions

The following Java implementations are available in {productname} {this-version}:

// relevant source: https://confluence.suse.com/display/SLE/Java
//             and: bsc#1171541

[cols="33%,17%,17%,33%" options="header"]
|===
|Name (Package Name)
|Version
|Module
|Support

|OpenJDK +
(`java-11-openjdk`)
|11
|Base System
|SUSE, L3, until 2026-12-31

|OpenJDK +
(`java-17-openjdk`)
|17
|Base System
|SUSE, L3, until 2028-06-30

|OpenJDK +
(`java-1_8_0-openjdk`)
|1.8.0
|Legacy
|SUSE, L3, until 2026-12-31

|IBM Java +
(`java-1_8_0-ibm`)
|1.8.0
|Legacy
|External, until 2025-04-30
|===
