include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#miscellaneous]
=== Miscellaneous

// Miscellaneous release notes go here

// This section contains release notes entries that do not fit elsewhere.
// Where possible, find a matching category.


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

// jsc#PED-229
* support firmware updates from LVFS using UEFI capsule update features

[#bsc-1247839]
==== Apache's Portable Runtime Library devel package renaming

These two packages have been renamed:

* `libapr1-devel` to `apr-devel`
* `libapr-util1-devel` to `apr-util-devel`


[#bsc-1233354]
==== `suseconnect -r` failure in Secure Boot mode

When system is booted in Secure Boot mode, due to outdated `qclib` and `s390-tools` packages, `suseconnect -r` fails with the following error:

[source]
----
ExecuteError: Cmd: [read_values -s], RC: 1,
Error: exit status 1,
Output: Error: Unable to open configuration, return_code =-2
----

To fix the issue, run the system in non-Secure Boot mode for the update to the latest SP, then update `s390-tools` and `qclib` to the latest version.
Deregister the system and register it again in Secure Boot mode.


[#jsc-PED-12703]
==== New systems-management module

A new module called _Systems Management Module_ has been added.
This module will include systems-management packages, such as Ansible.


[#bsc-1211550]
==== TigerVNC's `vncserver` has been removed

The `vncserver` wrapper script around Xvnc has been removed upstream.

See https://github.com/TigerVNC/tigervnc/blob/04f19667cd53becaab97d888c3cfb7246338a238/unix/vncserver/HOWTO.md[the official documentation] for information on using Xvnc in version 1.11.0 or newer.


[#jsc-PED-2653]
==== `cpuid` has been added

The `cpuid` package has been added.
It provides detailed information about the CPU.
For more information see http://etallen.com/cpuid.html.
