include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#network]
=== Networking

// Release notes for networking features:
//     Wicked, NetworkManager, Open VSwitch...


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-13591]
==== `frr` (FRRouting Routing daemon) has been added

The `frr` package has been added.
It manages TCP/IP based routing protocols.

FRR is a fork of Quagga, which has stopped development in 2018.
Its developers moved to the FRR project and thus Quagga will receive no further updates.

We recommend migrating to `frr`.
The configuration is mostly backward compatible, including the `vtysh` shell to configure the routing protocols.
However, there were several changes, improvements, and new functionality added to `frr`.

See https://frrouting.org/ for more information.


// !STICKY
[#network-samba]
==== Samba

// bnc#606288
The version of Samba shipped with {sles} {this-version} delivers integration with Windows Active Directory domains.
In addition, we provide the clustered version of Samba as part of {sleha} {this-version}.

[#network-nfs]
==== NFS

// !STICKY
[#network-nfs4]
===== NFSv4

// bnc#608543 and bnc#574572
NFSv4 with IPv6 is only supported for the client side.
An NFSv4 server with IPv6 is not supported.
