include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#security]
=== Security

// Release notes for security tool/library features:
//    new TLS standards in OpenSSL, new nmap feature, ...
//    (not: security bugs/fixes in applications)

// !STICKY
// related: FATE#323868 [removal info in FATE is incorrect, correction via mail from meissner, 2020-06-05]
[#jsc-SLE-9294]
==== TLS 1.1 and 1.0 are no longer recommended for use

The TLS 1.0 and 1.1 standards have been superseded by TLS 1.2 and TLS 1.3.
TLS 1.2 has been available for considerable time now.

{productname} packages using OpenSSL, GnuTLS, or Mozilla NSS already support TLS 1.3.
We recommend no longer using TLS 1.0 and TLS 1.1, as {suse} plans to disable these protocols in a future service pack.
However, not all packages, for example, Python, are TLS 1.3-enabled yet as this is an ongoing process.


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-PED-8000]
==== New 4096-bit signing key

{sle} 15 product family switched over from a RSA 2048-bit signing key to a new RSA 4096-bit key.
This change covers RPM packages, package repositories and ISO signatures.
For more information see https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-update-preparation.html#sec-update-preparation-update


[#jsc-PED-1891]
==== Replacement of `gpg` as recommended tool for file encryption

A new `rage-encryption` package has been added.
The package provides the `rage` executable.
`rage` is an implementation of the `age` file encryption format using Rust.

This replaces `gpg` as the preferred tool over `gpg` for file encryption.
The main reasons are that `gpg` has a history of security issues, and is well known for its complexity.
In comparison, `rage` focuses on usability and security.
It especially tries to make key handling as simple as handling SSH keys (essentially short lines of text), which it also supports.

For more information, see:

* https://github.com/str4d/rage
* https://age-encryption.org/v1
