
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#ha-tools]
== High-Availability Tools

This section list information related to the high-availability tools of {product}{nbsp}{this-version}.

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

// jsc#PED-13089
* Nutanix AHV fence agent has been added.

[#jsc-PED-12469]
=== `cpuid` has been updated

The `cpuid` package has been updated to version 20241021:

- Features since release 20230614:
  * Added recognition for some Intel Arrow Lake-U, Nova Lake, Core
    200S, Core 200V, Xeon 6 Sierra Forest models.
  * Removed KaiXian KX-7000.
  * Added synth decoding for Hygon Dhyana B1 & C2.
  * Added uarch synth decoding for (0,6),(5,5),11 Cooper Lake.
    The synth decoding was already present.
  * Added 0x23/1 sub-header: Architecture Performance Monitoring
    Counters Supported Bitmaps (0x23/1), and simplified fields.
  * Added 0x23/2 sub-header: Architecture Performance Monitoring
    Auto Counter Reload (ACR) Bitmaps (0x23/2), expanded on
    existing field descriptions, and added "can cause reloads" fields.
  * Added uarch decoding for (11,15),(1,0), which is mentioned
    with (11,15),(0,0) in the title of 58088 AMD 1Ah Models 00h-0Fh and
    Models 10h-1Fh ACPI v6.5 Porting Guide.
  * Expanded `br.xeon` test to include brands with "XEON", and
    `br.scalable` to include "BRONZE", "PLATINUM", etc. (all caps).
  * Updated (0,6),(11,7) to include Core i`*`-14000. Some CPUs
    having this branding, and it's not clear what's different from the
    Core i`*`-13000 versions.
Bug Fixes since release 20230614:
  * For AMD Zen CPUs, overhauled uarch & synth decoding to
    determine the CPU model from only the extended model & high bit of the
    model field.  Also, determine the stepping (revision) mechanically
    from the low-order 3 bits of the model and the stepping number.
    This should correctly identify retail Zen 5 Ryzen's.  This also
    corrects some stepping bugs from the Zen 1 era.
  * Fixed division-by-zero error in `decode_mp_synth` Intel leaf
    1/4 (zero fallback).
	This is meant for old, incomplete `cpuid -r dumps`, but even for
	hand-crafted dumps, determining 0 cores and then dividing by that 0
	is unacceptable.


[#jsc-PED-11875]
=== `hwloc` has been updated

The `hwloc` package has been updated to version 2.11.2:

* Add missing CPU info attrs for aarch64 on Linux.
* Use ACPI CPPC on Linux to get better information about cpukinds, at
least on AMD CPUs.
* `+hwloc-calc --cpuset-output-format+` systemd-dbus-api now allows. to
generate `+AllowedCPUs+` information for systemd slices. See the
`+hwloc-calc+` manpage for examples.
* API
** Add `+HWLOC_MEMBIND_WEIGHTED_INTERLEAVE+` memory binding policy on
Linux 6.9+.
*** `+weighted_interleave_membind+` is added to membind support bits.
*** The "`weighted`" policy is added to the `+hwloc-bind+` tool.
** Add `+hwloc_obj_set_subtype()+`.
* GPU support
** Don’t hide the GPU NUMA node on NVIDIA Grace Hopper.
** Get Intel GPU OpenCL device locality.
** Add bandwidths between subdevices in the `+LevelZero+`
`+XeLinkBandwidth+` matrix.
* Tools
** Option `+--best-memattr+` may now return multiple nodes. Additional
configuration flags may be given to tweak its behavior.
** `+hwloc-info+` has a new `+--get-attr+` option to get a single
attribute.
** `+hwloc-info+` now supports "`levels`", "`support`" and "`topology`"
special keywords for backward compatibility for hwloc 3.0.
** The `+--taskset+` command-line option is superseded by the new
`+--cpuset-output-format+` which also allows to export as list.
** `+hwloc-calc+` may now import bitmasks described as a list of bits
with the new `+--cpuset-input-format list+`.
* Misc
** The `+MemoryTiersNr+` info attribute in the root object now says how
many memory tiers were built.
** Fix the management of infinite cpusets in the bitmap printf/sscanf
API as well as in command-line tools.
** Add section "`Compiling software on top of hwloc’s C API`" in the
documentation with examples for GNU Make and CMake. Bug Fixes:
* Fix crash when manipulating cpukinds after topology duplication.
* Fix missing input target checks in memattr functions
* Fix a memory leak when ignoring NUMA distances on FreeBSD.
* Fix build failure on old Linux distributions without accessat().
* Fix non-Windows importing of XML topologies and CPUID dumps exported
on Windows.
* Some fixes in manpage EXAMPLES and split them into subsections.
* Fix bash completions
** Fix PCI Gen4+ link speed of NVIDIA GPU obtained from NVML.




[#haproxy-legacy-http]
=== HAProxy legacy HTTP mode removal

HAProxy 2.1 has removed support for the legacy HTTP mode.
It now supports the Native HTTP Representation only, also known as HTX.

Here is the list of proxy keywords which were deprecated in version 2.0 and that have been removed in version 2.4:

* `block`
* `clitimeout`
* `contimeout`
* `option http-tunnel`
* `option http-use-htx`
* `redisp`
* `redispatch`
* `reqadd`
* `reqallow`
* `reqdel`
* `reqdeny`
* `reqiallow`
* `reqidel`
* `reqideny`
* `reqipass`
* `reqirep`
* `reqitarpit`
* `reqpass`
* `reqrep`
* `reqtarpit`
* `rspadd`
* `rspdel`
* `rspdeny`
* `rspidel`
* `rspideny`
* `rspirep`
* `rsprep`
* `srvtimeout`
* `timeout clitimeout`
* `timeout contimeout`
* `timeout srvtimeout`
* `transparent`

You can run `haproxy -c -f /path/to/haproxy.conf` to see if you have any incompatible or deprecated settings.
To replace removed keywords:

* `block` - use the new `http-request deny` instead
* `clitimeout` - use `timeout client` instead
* `contimeout` - use `timeout connect`, `timeout queue`, or `timeout tarpit` instead
* `option http-tunnel` - this option has been removed because it cannot work in HTTP/2
* `option http-use-htx` - this option has been removed because the support for legacy HTTP mode has been removed
* `redisp`, `redispatch`, `reqadd`, `reqallow`, `reqdel`, `reqdeny`, `reqiallow`, `reqidel`, `reqideny`, `reqipass`, `reqirep`, `reqitarpit`, `eqpass`, `reqrep`, `reqtarpit` - these keywords need to be replaced by the `http-request` statement, see https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#4.2-http-request
* `rspadd`, `rspdel`, `rspdeny`, `rspidel`, `rspideny`, `rspirep`, `rsprep` - these keywords need to be replaced by the `http-response` statement, see https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#4.2-http-response
* `srvtimeout` - use `timeout server` instead
* `timeout clitimeout` - use `timeout client` instead
* `timeout contimeout` - use `timeout connect` instead
* `timeout srvtimeout` - use `timeout server` instead
* `transparent` - use `option transparent` instead

[#jsc-PED-960]
=== Relax-and-Recover (ReaR) 2.7

The `rear27a` package has been added.

For more information see the full changelog either online at https://github.com/rear/rear/blob/rear-2.7/doc/rear-release-notes.txt or in the `/usr/share/doc/packages/rear27a/rear-release-notes.txt` file.

[WARNING]
Do not upgrade ReaR or change the software used by ReaR without also checking that your existing disaster recovery procedure still works.
See also the _SUSE support for Relax-and-Recover_ and _Version upgrades with Relax-and-Recover_ sections in https://en.opensuse.org/SDB:Disaster_Recovery.