include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#miscellaneous]
=== Miscellaneous

// Miscellaneous release notes go here

// This section contains release notes entries that do not fit elsewhere.
// Where possible, find a matching category.


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-24988]
==== Enriched system visibility in the {sccfull}

{suse} is committed to helping provide better insights into the consumption of {suse} subscriptions regardless of where they are running or how they are managed; physical or virtual, on-prem or in the cloud, connected to SCC or {rmtfull}, or managed by {suma}.
To help you identify or filter out systems in SCC that are no longer running or decommissioned, {suseconnect} now features a daily “ping”, which will update system information automatically.

For more details see the documentation at https://susedoc.github.io/doc-unversioned/main/single-html/SLE-suseconnect-tracking/.