#!/usr/bin/env python3
"""
fetch-nvidia-kernel-patches.py

Extracts NVIDIA kernel patches from series.conf and patches.suse/ headers.
Supports output in AsciiDoc, plain text, and JSON formats.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


def git(*args, cwd=None):
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        errors="replace",
        check=False,
    )


def extract_header(lines, tag):
    """Extract words following the first occurrence of tag (case-insensitive)."""
    for line in lines:
        sline = line.lstrip()
        if sline.lower().startswith(tag.lower()):
            parts = sline.split(None, 1)
            return parts[1].strip() if len(parts) > 1 else ""
    return ""


def clean_subject(subj):
    """Strip [PATCH ...] prefix and clean up whitespace."""
    subj = re.sub(r"^\[PATCH[^\]]*\]\s*", "", subj, flags=re.IGNORECASE)
    return " ".join(subj.split())


def extract_patch_metadata(patch_path):
    """Parse patch file and extract commit, upstream version, references, and subject."""
    try:
        with open(patch_path, "r", encoding="utf-8", errors="replace") as f:
            lines = [f.readline() for _ in range(120)]
    except OSError:
        lines = []

    commit = extract_header(lines, "Git-commit:")
    upstream = extract_header(lines, "Patch-mainline:")
    references = extract_header(lines, "References:")
    subject = clean_subject(extract_header(lines, "Subject:"))

    return {
        "patch": str(patch_path),
        "commit": commit,
        "upstream": upstream,
        "references": references,
        "subject": subject,
    }


def format_asciidoc(patches):
    """Render patches as an AsciiDoc table."""
    lines = [
        "// Automatically generated by scripts/fetch-nvidia-kernel-patches.py. Do not edit manually.",
        '[cols="2,2,3,5", options="header"]',
        "|===",
        "| Commit | Upstream | Reference | Subject",
    ]
    for p in patches:
        short_commit = f"`{p['commit'][:12]}`" if p["commit"] else "-"
        upstream = p["upstream"] if p["upstream"] else "-"
        refs = p["references"] if p["references"] else "-"
        subj = p["subject"].replace("|", "\\|") if p["subject"] else "-"
        lines.append(f"| {short_commit} | {upstream} | {refs} | {subj}")
    lines.append("|===")
    return "\n".join(lines) + "\n"


def format_text(patches):
    """Render patches as aligned text."""
    lines = []
    for p in patches:
        commit = p["commit"][:12] if p["commit"] else "-"
        upstream = p["upstream"] if p["upstream"] else "-"
        refs = p["references"] if p["references"] else "-"
        lines.append(f"{commit:<14} {upstream:<10} {refs:<20} {p['subject']}")
    return "\n".join(lines) + "\n"


def get_series_patches(repo_path, base_rev, target_rev=None):
    """Get list of patch files added to series.conf between base_rev and target_rev."""
    rev_arg = f"{base_rev}..{target_rev}" if target_rev else base_rev
    diff = git("diff", rev_arg, "--", "series.conf", cwd=repo_path).stdout
    patches = []
    for line in diff.splitlines():
        if line.startswith("+") and not line.startswith("+++"):
            clean_line = line[1:].split("#")[0].strip()
            if clean_line and len(clean_line) > 5:
                patches.append(clean_line)
    return patches


def main():
    parser = argparse.ArgumentParser(description="Extract NVIDIA kernel patches from kernel-source.")
    parser.add_argument("base_rev", nargs="?", default="origin/SL-16.1", help="Base Git revision (default: origin/SL-16.1)")
    parser.add_argument("target_rev", nargs="?", default=None, help="Target Git revision (optional)")
    parser.add_argument("--repo-dir", default=".", help="Path to kernel-source repository checkout")
    parser.add_argument("--format", choices=["asciidoc", "text", "json"], default="text", help="Output format")
    parser.add_argument("-o", "--output", help="Output file path (default: stdout)")
    args = parser.parse_args()

    repo = Path(args.repo_dir)
    patch_names = get_series_patches(repo, args.base_rev, args.target_rev)

    records = []
    for name in patch_names:
        patch_file = repo / name
        records.append(extract_patch_metadata(patch_file))

    if args.format == "asciidoc":
        output = format_asciidoc(records)
    elif args.format == "json":
        output = json.dumps(records, indent=2)
    else:
        output = format_text(records)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
