tag::bsc1240989[]
[#bsc-1240989]
= Default user group assignment changed

Previously, all user accounts belonged to a single `users` group.

Now instead of being added to the common `users` group, each new user now gets their own primary group matching their username.
This is due to `USERGROUPS_ENAB` being enabled in `/usr/etc/login.defs`.
This change affects all new installations and upgraded systems that did not change the default `/etc/login.defs`.
This has several consequences:

* files created by new users are not group-readable by default
* configurations that used the primary `users` group as a condition do not work anymore
* configurations that used the primary or secondary `users` group as a condition need to have the `users` group manually added to these user accounts in order to continue to work, for example, to for `@users` in the sudoers file
* home directories inherited from a previous system need to standardize the GID of the files by running: `find "$HOME" -group users -exec chgrp myuser {} \;`, or `chgrp -R myuser "$HOME"` if you did not use any GID other than `users`
end::bsc1240989[]

tag::jscped12374[]
* `crun` has been removed. Use `runc` instead.
end::jscped12374[]

tag::jscped-11998[]
[#jsc-PED-11970]
= Added `tuned`

The `tuned` package contains a daemon that tunes system settings dynamically.
end::jscped-11998[]

tag::jscped-12210[]
[#jsc-PED-12210]
= SHA1 to be disabled or mark unapproved

Due to FIPS 140-3 certification requirements, the SHA1 cryptographic algorithm will be disabled or marked unapproved when running in FIPS mode.
end::jscped-12210[]

tag::jscped-12860[]
[#jsc-PED-12860]
= Minimum hardware requirements

{productname} {this-version} requires hardware to meet requirements on these architectures:

* For AMD64 and Intel* 64 systems: Microarchitecture level x86-64-v2 or higher.
* For IBM* Power LE systems: POWER10 or higher (see note below).
* For Arm64* systems: Armv8.0-A or higher.
* For IBM* Z systems: z14 or higher.

[NOTE]
POWER9 systems may work with {productnameshort} {this-version} but are not supported by IBM, the hardware vendor.

end::jscped-12860[]

tag::jscped-12354[]
= Resource agent removal

Some resource agents have been removed from the `resource-agent` package:

* `ldirectord`
* `sfex_`*
* HA-related part of IPVS
* `conntrack-tools` dependency from `ha_sles` pattern
end::jscped-12354[]

tag::jscped-4965[]
[#jsc-PED-4965]
= Password access as root via SSH disabled

Previously, it was possible to SSH as root using password-based authentication.
In {productnameshort} {this-version} only key-based authentication is allowed by default.
Systems upgraded to {this-version} from a previous version will carry over the old behavior.
New installations will enforce the new behavior.

Installing the package `openssh-server-config-rootlogin` restores the old behavior and allows password-based login for the root user.
end::jscped-4965[]

tag::jscped-12725[]
[#jsc-PED-12725]
= Switch to predictable network names

The persistent network naming scheme used in {productnameshort} 15 became legacy with the switch to the systemd predictable network names.
For complicated setups, we recommend using `systemd.link`.

For more information, see:

* https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
* https://www.freedesktop.org/software/systemd/man/latest/systemd.link.html

[NOTE]
In the future, when upgrading from {slm-short} to {productnameshort} {next-version} (so-called "SLE merge"), some systems will have `net.ifnames=0` set on their kernel command line (this is the case for new installations of {slm-short} 6.0 and 6.1).
This boot option will prevent the system from switching to the predictable naming scheme and it will need to be removed.
end::jscped-12725[]

tag::jscped-12739[]
= Switch to `mountfd` API in `util-linux`

The `util-linux` `mount` command has switched from the old string-based method to the new kernel `mountfd` API.
This change introduces new features but also comes with some minor incompatibilities.

There is a special case that cannot be handled by `mountfd` and needs to be handled by applications:

* `mountfd` discriminates between the physical mount layer and the virtual mount layer
* once the physical mount layer is read-only, read-write mount on the virtual layer is not possible

If the first mount is read-only, then the physical filesystem is mounted read-only, and later mounting of the same file system as read-write is not possible.
To solve this problem, the first mount needs to be read-only on the virtual layer only, keeping the physical layer read-write.
The userspace fix is simple. Instead of:

[source]
mount -oro

use

[source]
mount -oro=vfs

This will keep the physical layer read-write, but the virtual file system layer (and the userspace access) read-only.
end::jscped-12739[]
