tag::bsc1240989[]
[#bsc-1240989]
= Default user group assignment changed

Previously, all user accounts belonged to a single `users` group.

Now instead of being added to the common `users` group, each new user now gets their own primary group matching their username.
This is due to `USERGROUPS_ENAB` being enabled in `/usr/etc/login.defs`.
This change affects all new installations and upgraded systems that did not change the default `/etc/login.defs`.
This has several consequences:

* files created by new users are not group-readable by default
* configurations that used the primary `users` group as a condition do not work anymore
* configurations that used the primary or secondary `users` group as a condition need to have the `users` group manually added to these user accounts in order to continue to work, for example, to for `@users` in the sudoers file
* home directories inherited from a previous system need to standardize the GID of the files by running: `find "$HOME" -group users -exec chgrp myuser {} \;`, or `chgrp -R myuser "$HOME"` if you did not use any GID other than `users`
end::bsc1240989[]

tag::jscped12374[]
* `crun` has been removed. Use `runc` instead.
end::jscped12374[]

tag::jscped-11998[]
[#jsc-PED-11970]
= Added `tuned`

The `tuned` package contains a daemon that tunes system settings dynamically.
end::jscped-11998[]

tag::jscped-12210[]
[#jsc-PED-12210]
= SHA1 to be disabled or mark unapproved

Due to FIPS 140-3 certification requirements, the SHA1 cryptographic algorithm will be disabled or marked unapproved when running in FIPS mode.
end::jscped-12210[]

tag::jscped-12860[]
[#jsc-PED-12860]
= Minimum hardware requirements

{productname} {this-version} requires hardware to meet requirements on these architectures:

* For AMD64 and Intel* 64 systems: Microarchitecture level x86-64-v2 or higher.
* For IBM* Power LE systems: POWER10 or higher (see note below).
* For Arm64* systems: Armv8.0-A or higher.
* For IBM* Z systems: z14 or higher.

[NOTE]
POWER9 systems may work with {productnameshort} {this-version} but are not supported by IBM, the hardware vendor.

end::jscped-12860[]

tag::jscped-12354[]
= Resource agent removal

Some resource agents have been removed from the `resource-agent` package:

* `ldirectord`
* `sfex_`*
* HA-related part of IPVS
* `conntrack-tools` dependency from `ha_sles` pattern
end::jscped-12354[]

tag::jscped-4965[]
[#jsc-PED-4965]
= Password access as root via SSH disabled

Previously, it was possible to SSH as root using password-based authentication.
In {productnameshort} {this-version} only key-based authentication is allowed by default.
Systems upgraded to {this-version} from a previous version will carry over the old behavior.
New installations will enforce the new behavior.

Installing the package `openssh-server-config-rootlogin` restores the old behavior and allows password-based login for the root user.
end::jscped-4965[]

