tag::bsc1240989[]
[#bsc-1240989]
= Default user group assignment changed

Previously, all user accounts belonged to a single `users` group.

Now instead of being added to the common `users` group, each new user now gets their own primary group matching their username.
This is due to `USERGROUPS_ENAB` being enabled in `/usr/etc/login.defs`.
This change affects all new installations and upgraded systems that did not change the default `/etc/login.defs`.
This has several consequences:

* files created by new users are not group-readable by default
* configurations that used the primary `users` group as a condition do not work anymore
* configurations that used the primary or secondary `users` group as a condition need to have the `users` group manually added to these user accounts in order to continue to work, for example, to for `@users` in the sudoers file
* home directories inherited from a previous system need to standardize the GID of the files by running: `find "$HOME" -group users -exec chgrp myuser {} \;`, or `chgrp -R myuser "$HOME"` if you did not use any GID other than `users`
end::bsc1240989[]

