tag::jscped-15968[]
[#jsc-PED-15968]
= Secure Initial Program Load (IPL) support

IPL has the following minimum system requirements, depending on the boot device to be IPLed:

* NVMe disk: IBM LinuxONE III or newer.
* FC-attached SCSI disk: IBM LinuxONE III, IBM z15 or newer.
* ECKD DASD with CDL layout: IBM z16, LinuxONE 4 or newer.

If these requirements are not met, the system can be IPLed in non-secure mode only.
end::jscped-15968[]

tag::bsc1240989[]
[#bsc-1240989]
= Default user group assignment changed

Previously, all user accounts belonged to a single `users` group.

Now instead of being added to the common `users` group, each new user now gets their own primary group matching their username.
This is due to `USERGROUPS_ENAB` being enabled in `/usr/etc/login.defs`.
This change affects all new installations and upgraded systems that did not change the default `/etc/login.defs`.
This has several consequences:

* you cannot rely on group permissions to give access to other users
** the default umask of 022 still gives read permissions to everyone; to avoid this, set the umask to 027
* configurations that used the primary `users` group as a condition do not work anymore
* configurations that used the primary or secondary `users` group as a condition need to have the `users` group manually added to these user accounts in order to continue to work, for example, to for `@users` in the sudoers file
* home directories inherited from a previous system need to standardize the GID of the files by running: `find "$HOME" -group users -exec chgrp myuser {} \;`, or `chgrp -R myuser "$HOME"` if you did not use any GID other than `users`
end::bsc1240989[]

tag::jscped12374[]
* `crun` has been removed. Use `runc` instead.
end::jscped12374[]

tag::jscped-11970[]
[#jsc-PED-11970]
= `tuned` now installed by default

The `tuned` package is now installed by default.
It contains a daemon that tunes system settings dynamically.
end::jscped-11970[]

tag::jscped-12210[]
[#jsc-PED-12210]
= SHA1 to be disabled or mark unapproved

Due to FIPS 140-3 certification requirements, the SHA1 cryptographic algorithm will be disabled or marked unapproved when running in FIPS mode.
end::jscped-12210[]

tag::jscped-12860[]
[#jsc-PED-12860]
= Minimum hardware requirements

{productname} {this-version} requires hardware to meet requirements on these architectures:

* For AMD64 and Intel* 64 systems: Microarchitecture level x86-64-v2 or higher.
* For IBM* Power LE systems: POWER10 or higher (see note below).
* For Arm64* systems: Armv8.0-A or higher.
* For IBM* Z systems: z14 or higher.

[NOTE]
While {productnameshort} {this-version} can run on POWER9, this configuration is not supported.

end::jscped-12860[]

tag::jscped-12354[]
= Resource agent removal

Some resource agents have been removed from the `resource-agent` package:

* `ldirectord`
* `sfex_`*
* HA-related part of IPVS
* `conntrack-tools` dependency from `ha_sles` pattern
end::jscped-12354[]

tag::jscped-4965[]
[#jsc-PED-4965]
= Password access as root via SSH disabled

Previously, it was possible to SSH as root using password-based authentication.
In {productnameshort} {this-version} only key-based authentication is allowed by default.
Systems upgraded to {this-version} from a previous version will carry over the old behavior.
New installations will enforce the new behavior.

Installing the package `openssh-server-config-rootlogin` restores the old behavior and allows password-based login for the root user.
end::jscped-4965[]

tag::jscped-12725[]
[#jsc-PED-12725]
= Switch to predictable network names

The persistent network naming scheme used previously became legacy with the switch to the systemd predictable network names.
For complicated setups, we recommend using `systemd.link`.

For more information, see:

* https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
* https://www.freedesktop.org/software/systemd/man/latest/systemd.link.html

[NOTE]
In the future, when upgrading from {slm-short} to {productnameshort} {next-version} (so-called "SLE merge"), some systems will have `net.ifnames=0` set on their kernel command line (this is the case for new installations of {slm-short} 6.0 and 6.1).
This boot option will prevent the system from switching to the predictable naming scheme and it will need to be removed.
end::jscped-12725[]

tag::jscped-12739[]
= Switch to `mountfd` API in `util-linux`

The `util-linux` `mount` command has switched from the old string-based method to the new kernel `mountfd` API.
This change introduces new features but also comes with some minor incompatibilities.

There is a special case that cannot be handled by `mountfd` and needs to be handled by applications:

* `mountfd` discriminates between the physical mount layer and the virtual mount layer
* once the physical mount layer is read-only, read-write mount on the virtual layer is not possible

If the first mount is read-only, then the physical filesystem is mounted read-only, and later mounting of the same file system as read-write is not possible.
To solve this problem, the first mount needs to be read-only on the virtual layer only, keeping the physical layer read-write.
The userspace fix is simple. Instead of:

[source]
mount -oro

use

[source]
mount -oro=vfs

This will keep the physical layer read-write, but the virtual file system layer (and the userspace access) read-only.
end::jscped-12739[]

tag::jscped-8258[]
[#jsc-PED-8258]
= Simplified SBD management

A new `crm sbd` command has been added in order to simplify SBD management.

It can:

* display the real-time SBD status and the static SBD configuration
* manage the configuration file for both disk-based and diskless SBD scenarios, and the on-disk metadata for the disk-based scenario

// jsc#PED-12514
There is also a `crm maintenance` command which can help with advanced tasks like kernel crashdump configuration procedure.
end::jscped-8258[]

tag::jscped-13118[]
= nmap deprecation notice

The nmap project has moved to a new source license that makes future releases of nmap incompatible with our product.

In {productnameshort} {this-version}, we are shipping the latest version of nmap released under the old license.
In an upcoming release we will switch to an alternative tool.
end::jscped-13118[]

tag::jscped-12715[]
[#jsc-PED-12715]
= Removal of 32-bit support

{productname} {this-version} only supports 64-bit binaries.
Support for 32-bit binaries (or 31-bit binaries on {ibmz}) has been removed.

This means that statically-linked 32-bit binaries (or 31-bit binaries on {ibmz}) and container images cannot be run anymore.
32-bit syscalls are still enabled by default on arm64, and can be enabled on x86_64 via the kernel parameter `ia32_emulation`.
On other architectures it's disabled without any option to enable it.
end::jscped-12715[]


tag::jscped-13633[]
[#jsc-PED-13633]
= SAP Host Agent PAM configuration fixed during migration

Older SAP Host Agent installations may have written PAM configuration for `sapstartsrv` using compatibility links (`pam_unix_auth.so`, `pam_unix_acct.so`, `pam_unix_session.so`, `pam_unix_passwd.so`) that no longer exist in {productname} {this-version}.

The migration tool replaces all occurrences of `pam_unix_{auth,acct,session,passwd}.so` with `pam_unix.so` in all files in `/etc/pam.d/` during migration from {productname} 15 to {productname} {this-version}.

end::jscped-13633[]

tag::jscped-11986[]
[#jsc-PED-11986]
= SSSD: support for running as unprivileged user

SSSD has been updated to version 2.10, which adds support for running as
an unprivileged user instead of root. This allows containerized deployments
to comply with security requirements that limit root privileges within
containers.

By default, SSSD runs as root with the `sssd` supplementary group, which
provides access to SSSD-owned files. To switch to unprivileged mode, create
a systemd service override:

[source,bash]
----
sudo systemctl edit sssd.service
----

Add the following:

[source,ini]
----
[Service]
User=sssd
Group=sssd
SupplementaryGroups=
----

Then reload and restart the service:

[source,bash]
----
sudo systemctl daemon-reload
sudo systemctl restart sssd
----

Note that running as an unprivileged user requires filesystem support for
POSIX capabilities. On filesystems that do not support capabilities
(such as NFS), SSSD must continue to run as root.

end::jscped-11986[]

tag::jscped-15932[]
[#jsc-PED-15932]
= Kiwi KubeVirt containerdisk format

Kiwi now supports a new `containerdisk` format for building KubeVirt-compatible
container images from OEM disk builds.

The new format combines qcow2 disk image creation with OCI container packaging
in a single workflow.
The resulting container image contains the disk image at `/disk` and includes
the necessary KubeVirt metadata.

The disk format (e.g. qcow2, raw, vmdk) and target container transport (e.g.
docker://, oci://, obs://) are configurable via the format parameter.

Example format syntax: `format="oci:qcow2:docker://registry.example.com/kubevirt-disk:latest"`
end::jscped-15932[]

tag::jscped-12923[]
[#jsc-PED-12923]
= Default log levels for dracut have changed

The default log levels for `dracut` have been adjusted to reduce console verbosity while maintaining full troubleshooting details in the system log.

* Standard/console output log level has been reduced from `4` (info) to `3` (warnings).
Standard boots and package operations (such as `zypper` updates) will now print only warnings and errors to the terminal.
* Syslog/journal log level has been increased from `0` (suppress) to `4` (info).
This ensures that detailed system initialization logs continue to be written to the system journal and remain fully accessible for diagnostics.
end::jscped-12923[]
