include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#container]
=== Containers

// Release notes for containers:
//    LXC, Docker, ...

Also see the following additional note:

* <<#jsc-SLE-10977>>

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-PED-24123]
==== Adding Helm to SLE Containers Module

Installing and deploying Rancher and {slea} applications delivered as containers (like {rmtfull}), require specific tool and setup.

Helm is the de-facto package manager for Kubernetes, allowing to define, install and upgrade Kubernetes application.

{suse} is providing and supporting helm as part of {slesa}, for the following use case:

* installation of Rancher
* installation of {slea} applications throught helm charts (like RMT) when deploying them on k8s


[#jsc-PED-1805]
==== Podman upgrade from 3.4.x to 4.3.1

Podman 4.x is a major release with 60 new features and more than 50 bug fixes compared to Podman 3.
It also includes a complete rewrite of the network stack.

Podman 4.x brings a new container network stack based on https://github.com/containers/netavark[Netavark], the new container network stack and https://github.com/containers/aardvark-dns[Aardvark DNS server] in addition to the existing container network interface (CNI) stack used by Podman 3.x . The new stack brings 3 important improvement:

 * Better support for containers in multiple networks
 * Better IPv6 support
 * Better performance

To ensure that nothing break with this major change, the old CNI stack will remain the default on existing installations, while new installs will use Netavark.

New installations can opt to use CNI by explicitly specifying it via the `containers.conf` configuration file, using the `network_backend` field.

If you have run Podman 3.x before upgrading to Podman 4, Podman will continue to use CNI plugins as it had before.
There is a marker in Podman's local storage that indicates this.
In order to begin using Podman 4, you need to destroy that marker with `podman system reset`.
This will destroy the marker, all of the images, all of the networks, and all of the containers.

[WARNING]
Before testing Podman 4 and the new network stack, you will have to destroy all your current containers, images, and networks.
You must export/save any import containers or images on a private registry, or make sure that your Dockerfiles are  available for rebuilding and scripts/playbooks/states to reapply any settings, regenerate secrets, etc.

Last but not least CNI will be deprecated from upstream at a future date.

For a complete overview of the changes, please check out the upstream https://github.com/containers/podman/releases/tag/v4.0.0[4.0.0] but also https://github.com/containers/podman/releases/tag/v4.1.1[4.1.1], https://github.com/containers/podman/releases/tag/v4.2.0[4.2.0] and https://github.com/containers/podman/releases/tag/v4.3.0[4.3.0] to be informed about all the new features and changes.


[#jsc-SLE-22133]
==== {slea} BCI minimal and micro container images

The current {slea} container images were not small enough for cloud-native applications.
Even though they had fewer packages compared to a regular {slea} system, they still included many that were not required.
These extra packages increased the size of the image and, most importantly, its attack surface.

As a solution, a minimal and micro container images based on the {suse} BCI (Base Container Image) have been made available.
See the https://registry.suse.com/[SUSE registry] for more information.

[NOTE]
=====
The minimal container does not include the `zypper` package but it includes the `rpm` package.
That means:

* applications can be deployed into the container in the RPM format
* there is no simple way to install dependencies in the container except for manually copying all the RPM packages and installing them
=====

The micro container does not include the `zypper` nor the `rpm` packages.


[#jsc-SLE-22144]
==== {slea} BCI language container images

These are container images providing language SDKs and runtimes.
The language container contains and is updated with the same version of the particular language that is in the respective Service Pack of {slesa}.
The following containers are now available:

// jsc#SLE-22437
* Ruby
// jsc#SLE-19182
* Python
* Node
* Go
* Java

See the https://registry.suse.com/[SUSE registry] for more information.


[#jsc-SLE-12431]
==== Rootless containers

By default, Podman requires root privileges.

You can use Podman without root privileges for enhanced security.
For more information, see https://documentation.suse.com/container/all/html/Container-guide/index.html#sec-podman-rootless-containers-tricks.


[#jsc-SLE-17280]
==== LXC containers have been deprecated
System containers using LXC have been deprecated and will be removed in {product} 15 SP4.
This includes the following packages:

* `libvirt-lxc`
* `virt-sandbox`

As a replacement, we recommend commonly used alternatives like Docker or Podman.


// !STICKY
[#jsc-SLE-15587]
==== `suse/sle15` container uses NDB as the database back-end for RPM

Starting with {sle} 15{nbsp}SP3, the `rpm` package in the `suse/sle15` container image no longer supports the BDB back-end (based on Berkeley DB) and switches to the NDB back-end.
Tools for scanning, diffing, and building container image using the `rpm` binary of the host for introspection can fail or return incorrect results if the host's version of `rpm` does not recognize the NDB format.

To use such tools, make sure that the host supports reading NDB databases, such as hosts with {sle} 15{nbsp}SP2 and later.
