
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#database]
=== Databases

// Release notes for databases:
//    PostgreSQL, MariaDB, ...


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

Also see the following additional notes:

* <<#bsc-1178616>>.

[#jsc-SLE-20675]
==== PostgreSQL 14 has been added

PostgreSQL 14 has been added to {product}.
For information about changes between PostgreSQL 14 and 13, see the https://www.postgresql.org/docs/14/release-14.html[upstream release notes].


[#jsc-SLE-22245]
==== `mariadb-galera` has been added

The `mariadb-galera` package has been added.
This package contains configuration files and scripts that are needed for running MariaDB Galera Cluster.


[#jsc-SLE-20555]
==== `unixODBC` package drivers not for production

Drivers in the `unixODBC` package are not suitable for production use.
The drivers are provided for test purposes only.
We have added a reference to the package's README file with information about third-party `unixODBC` drivers that are suitable for production use (https://www.unixodbc.org/drivers.html).


[#jsc-SLE-17703]
==== The ODBC driver location has changed
Previously in {producta} 12, the `postgresql10-odbc` package was located in `/usr/pgsql-10/lib/psqlodbcw.so`.
In {producta} {this-version}, the `psqlODBC-10` package is located in `/usr/lib64/psqlodbcw.so`.

For some more information, see: https://bugzilla.suse.com/show_bug.cgi?id=1169697.

[#jsc-SLE-17030]
==== PostgreSQL 13 has been added

PostgreSQL 13 has been added to {product}.
For information about changes between PostgreSQL 13 and 12, see the upstream release notes:

* https://www.postgresql.org/docs/13/release-13.html

[WARNING]
.REINDEX is required
====
If you migrate a PostgreSQL server to {producta} {this-version}, a REINDEX is required before using the database productively again to avoid database corruptions. See https://support.scc.suse.com/s/kb/After-upgrading-a-PostgreSQL-server-to-SLES-15-SP3-a-REINDEX-is-required for details.
====

//jsc#SLE-15782
PostgreSQL 10 is deprecated and has been moved to the Legacy module.


[#jsc-SLE-12561]
==== PostgreSQL JDBC Driver has been added

The PostgreSQL JDBC Driver has been added.
This includes the following packages:

* jdbc-postgresql-42.2.16
* ongress-scram-1.0.0-beta.2


[#jsc-SLE-16269]
==== MariaDB has been updated to version 10.5

The `mariadb` package has been updated to 10.5.
For more information about upgrading from 10.4 to 10.5, see https://mariadb.com/kb/en/upgrading-from-mariadb-104-to-mariadb-105/.
