include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#ibm-z]
== {ibmz}-specific changes (s390x)

Information in this section applies to {z-product} {this-version}.
For more information, see https://www.ibm.com/support/knowledgecenter/en/linuxonibm/liaaf/lnz_r_suse.html

[#ibm-z-hardware]
=== Hardware


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

There were the following hardware-related changes:

* support has been added for IPL and re-IPL from local PCI NVMe storage
** currently a workaround is required for installation, see https://www.suse.com/support/kb/doc/?id=000020258
* support has been added for IBM z14 instructions in Valgrind
* the following new commands have been added to the the `qclib` package:
** `zhypinfo` - displays the virtualization stack
** `zname` - displays information on the hardware platform
* s390x CPU topology masks have been made consistent with all other architectures
* improved performance of re-IPL by not clearing memory
* improved performance of the GNU C Library's `libm` math library by using {ibmz} instructions
* the OpenBLAS library has been optimized with IBM z13 and IBM z14 instructions


[#ibm-z-network]
=== Networking


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


[#bsc-1153309]
==== Degraded performance on RoCE ConnectX-4 hardware

Using default settings of {product} 15{nbsp}SP1, 15{nbsp}SP2, and 15{nbsp}SP3, the performance of RoCE ConnectX-4 hardware on IBM{nbsp}z14 and IBM{nbsp}z15 systems is degraded compared to when used under {product} 15{nbsp}GA.

To improve performance to the same level as with {product} 15{nbsp}GA, set the following flag for all RoCE ethernet interfaces: `ethtool --set-priv-flags DEVNAME rx_striding_rq`.
This needs to be done for each RoCE interface and at each boot.


==== qeth: Converged HiperSockets/Ethernet Interface

Support for HiperSockets Converged Interface functionality has been added.
This provides a converged interface that forms a single LAN based on HiperSockets and OSA/RoCE.
This feature only supports a single registered MAC address for now.


==== SMC-R: Link failover support

Provides Link Group failover support which enables HA setups and makes the zLinux implementation reach full protocol compliance.


==== SMC-Dv2 support

SMC-Dv2 lifts the limitation to traffic within a single IP subnet only that SMC-D had, allowing traffic to peers in any IP subnet.
It also simplifies ISM device configuration.


==== `smc-tools`: Integrate SMC-R Link Group (LG) support

SMC-R LG support has been fully integrated into the `smc-tools` package through proper userspace tooling.


[#ibm-z-performance]
=== Performance


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


There were the following performance-related changes:

* use z15 instructions for the kernel's zlib implementation which is used, for example, for Btrfs compression
* when placed at the beginning of a function, kprobes will use the ftrace infrastructure, which increases performance


[#ibm-z-security]
=== Security


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


There were the following miscellaneous security-related changes:

* the `zkey` tool from `s390-tools` has been extended to import keys and recreate a repository based on keys generated by the EKMF web enterprise key management system
* self-test has been added to the `paes_s390` module to allow loading and using the PAES cipher if the kernel FIPS flag is switched on
* The `cpacfstats` tool from `s390-tools` has been enhanced to display Elliptic Curve Cryptography (ECC) CPU-MF counters


==== openCryptoki

There were the following openCryptoki-related changes:

* the `pkcstok_migrate` tool has been added
** the tool is able to convert all token data including PINs from using PINs encrypted with the method of v3.11 and earlier to being encrypted with a FIPS 140-2 compliant method
** it allows to migrate old key repositories to use data structures that support FIPS 140-2 compliant methods
* enhancements introduced with IBM z15 have been added, including Dilithium signing (quantum-safe support), and the Reencrypt function to the openCryptoki EP11 token
* support has been added for new identifiers and the PKCS #11 Baseline Provider Profile
* the `p11sak` tool has been added for generating, listing and deleting token keys in an openCryptoki token repository


==== Support for EP11 secure keys

The `pkey` module and the `zkey` tool have been extended to support EP11 secure keys.
This allows the use if protected keys derived from EP11 secure keys with `dm-crypt.`


==== Enhanced error handling for `zcrypt` device driver

The error handling for the `zcrypt` device driver has been enhanced, for example, by adding a device offline state.
This allows to distinguish between devices being offline due to external events and devices configured to be offline.


[#ibm-z-storage]
=== Storage


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


==== zdsfs: Coordinated read access

The zdsfs tool from `s390-tools` can now read from z/OS data sets while the containing DASD volume is online in z/OS.


==== Support for querying FICON link IBM Fibre Channel Endpoint Security

You can now find out if a FICON DASD is accessed using authenticated or encrypted links via the new sysfs `fc_security` attribute.


==== Support for querying FCP link IBM Fibre Channel Endpoint Security

You can now find out if an FCP remote port is accessed using authenticated or encrypted links, both in the running system and through kernel logs.


[#ibmz-virtualization]
=== Virtualization

//The following new features are supported in {product} {this-version} under KVM:


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


==== Added {ibmz} LPAR fence agent `fence_ibmz` for Pacemaker

An {ibmz} LPAR fence agent has been added for KVM setups with high-availability requirements which are often based on Corosync/Pacemaker.


==== Enhanced hardware diagnosis data of guest kernel

KVM now makes available additional data to improve hardware diagnoses for guest kernels.

==== `kvm_stat`: Improvements to sampling and logging

The sampling and logging capabilities of `kvm_stat` have been refined to provide improved RAS capabilities for both test/development and production environments.


==== Enablement of channel path handling for `vfio-ccw`

Improved handling of channel paths in `vfio-ccw` has been added.
For example, this includes passing through channel-path operations and notifying of channel path changes.


==== Transparent CCW IPL from DASD (`vfio-ccw`) has been enabled

The existing support for native CCW IPL required the setting of a per-device property to enforce unlimited prefetch.
This feature removes the necessity to specify the additional property and thus enables Linux IPL from `vfio-ccw` attached DASDs transparently.


==== Enable host key document verification

The tool `genprotimg` from the package `s390-tools` can now be used for host-key document verification.
This removes the extra manual verification step that was needed before.


==== Support for `virtio-fs` on {ibmz}


`virtio-fs` can now share a host file system with a guest.


==== Support for libvirt node device for vfio-ap matrix device

Enable and simplify the passthrough of crypto devices through use of libvirt mediated device management.


==== Support for DASD in libvirt node device driver

Enable and simplify the passthrough of DASD devices through use of libvirt mediated device management.


==== Implementation of full set of zPCI function properties

All properties of host PCI devices are now passed down to the guest, except for properties that are overridden by the user.
This improves the support for all PCI devices except network adapters.


[#ibm-z-misc]
=== Miscellaneous


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


==== Server Time Protocol (STP) leap second handling

When using STP, leap seconds will now be handled correctly.
