
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#miscellaneous]
=== Miscellaneous

// Miscellaneous release notes go here

// This section contains release notes entries that do not fit elsewhere.
// Where possible, find a matching category.


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

// jsc#SLE-23810
* `collectd`: enabled the `dpdkevent` and `dpdk_telemetry` plugins
// jsc#SLE-23733
* repackaged Strongswan to make plugins optional

[#bsc-1247839]
==== Apache's Portable Runtime Library devel package renaming

These two packages have been renamed:

* `libapr1-devel` to `apr-devel`
* `libapr-util1-devel` to `apr-util-devel`


[#jsc-SLE-20079]
==== `ssh-import-id` GitHub support

The `ssh-import-id` now supports importing public SSH keys from GitHub.


[#jsc-SLE-21224]
==== `adcli` now supports setting password expiry

The `adcli` command now supports the `--dont-expire-password` parameter.

This parameter sets or unsets the `DONT_EXPIRE_PASSWORD` flag in the `userAccountControl` attribute to indicate if the machine account password should expire or not.
By default `adcli` will set this flag while joining the domain which corresponds to the default behavior of Windows clients.


[#jsc-SLE-17630]
==== `zram` can help with installation on low-memory devices

`zram` is a kernel module for creating compressed block devices in RAM.
Because of the compression it can be more efficient than using RAM directly.
This can help with installation on devices with low amount of RAM.

`zram` is disabled by default.
It can be enabled by adding the `zram=1` parameter to the Linuxrc cmdline.
This moves the root filesystem and swap to RAM.
`zram`-based swap is removed when another type of swap is enabled.

See https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html for more information.


[#jsc-SLE-23233]
==== `blog` has been updated

The `blog` package has been updated to version 2.26.
This boot logging tool is part of https://github.com/bitstreamout/showconsole.


[#jsc-SLE-24988]
==== Enriched system visibility in the {sccfull}

{suse} is committed to helping provide better insights into the consumption of {suse} subscriptions regardless of where they are running or how they are managed; physical or virtual, on-prem or in the cloud, connected to SCC or {rmtfull}, or managed by {suma}.
To help you identify or filter out systems in SCC that are no longer running or decommissioned, {suseconnect} now features a daily “ping”, which will update system information automatically.

For more details see the documentation at https://documentation.suse.com/subscription/suseconnect/single-html/SLE-suseconnect-visibility/.


[#jsc-SLE-17502]
==== Access to logs via the `audit` group

The `audit` group has been added.

Its purpose is a better separation of permissions for access to audit logs.
With this change, users can be given access to logs without the need to change `sudo` rules.


[#bsc-1181658]
==== Mounting multipath devices via `by-label`

In {this-version}, mounting multipath devices using `by-label` mounts might fail during boot.

To resolve this, the `multipath` module needs to manually added to the initial RAM disk:

. Create a new file called `999-multipath.conf` in `/etc/dracut.conf.d/` with the following content: `add_dracutmodules+=multipath`
. Re-generate the initial RAM disk with this command: `dracut /boot/initrd-$(uname -r)`.
