include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#security]
=== Security

// Release notes for security tool/library features:
//    new TLS standards in OpenSSL, new nmap feature, ...
//    (not: security bugs/fixes in applications)

[#jsc-PED-8000]
==== New 4096-bit signing key

{sle} 15 product family switched over from a RSA 2048-bit signing key to a new RSA 4096-bit key.
This change covers RPM packages, package repositories and ISO signatures.
For more information see https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-update-preparation.html#sec-update-preparation-update


[#jsc-SLE-20292]
==== Security Content Automation Protocol (SCAP) Security Guide has been added

The `scap-security-guide` package has been added.

This package contains XCCDF (Extensible Configuration Checklist Description Format), OVAL (Open Vulnerability and Assessment Language), CPE (Common Platform Enumeration), and DS (Data Stream) files to run a compliance test on {producta}.


[#jsc-SLE-23623]
==== `libpwquality-tools` has been added

The `libpwquality-tools` package has been added.
It includes the following applications:

* `pwmake` - simple tool for generating random relatively easily pronounceable passwords
* `pwscore` - simple configurable tool for checking quality of a password


[#jsc-SLE-17756]
==== strongSwan now with enabled network namespaces

The strongSwan package included in {producta} {this-version} has been compiled with support for Linux network namespaces.


[#jsc-SLE-12226]
==== `dm-crypt` target supports synchronous encryption for increased performance

By default, `dm-crypt` performs data encryption and decryption through an asynchronous thread.
Starting with {slea} {this-version}, the target supports synchronous operation which is controlled with no-read-workqueue and no-write-workqueue options.
The options can be supplied through the `/etc/crypttab` file.
See the `crypttab(5)` man page for more information.


[#jsc-SLE-16780]
==== ClamAV has been updated to version 0.103

ClamAV 0.103 provides better on-access scanning and improvements that reduce the attack surface.


[#jsc-SLE-17366]
==== `tpm2-tss` has been updated to version 2.3.3

The `tpm2-tss` package has been updated to version 2.3.3.


[#jsc-SLE-15840]
==== Information about {we} security policies has been added

{slesa} and {sleda} have different security policies but installing the {we} on {slesa} does not change this. This is not mentioned anywhere.

Now, when installing the {we} in {product} {this-version}, you will be informed that the {slesa} security policies still apply.


// !STICKY
// related: FATE#323868 [removal info in FATE is incorrect, correction via mail from meissner, 2020-06-05]
[#jsc-SLE-9294]
==== TLS 1.1 and 1.0 are no longer recommended for use

The TLS 1.0 and 1.1 standards have been superseded by TLS 1.2 and TLS 1.3.
TLS 1.2 has been available for considerable time now.

{product} packages using OpenSSL, GnuTLS, or Mozilla NSS already support TLS 1.3.
We recommend no longer using TLS 1.0 and TLS 1.1, as {suse} plans to disable these protocols in a future service pack.
However, not all packages, for example, Python, are TLS 1.3-enabled yet as this is an ongoing process.


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////
