
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#storage]
=== Storage and file systems

// Release notes for storage tool/library features:
//   Btrfs, CFS, ext3, Snapper, ntfs-3g, ceph, ... (including kernel file systems)

Also see the following additional note:

* <<#jsc-SLE-15765>>
* {yast} supports management of Btrfs subvolume quotas

////
==== Example entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#bsc-1188762]
==== Change in handling `/dev/by-id/wwn-` device links

Device symbolic links that use the `/dev/by-id/wwn-` format has changed since {previous-version} due to an upstream bugfix in `systemd`.

To avoid problems when upgrading from {previous-version}, use one of the other symbolic links to devices, for example `/dev/by-id/scsi-`.


[#jsc-SLE-17091]
==== Support for NVMe over Fabrics (NVMe-oF) in `dracut` has been added

A module has been added to `dracut` to support installation and booting to NVMe-oF-based storage.


[#jsc-SLE-16031]
==== `snapper` Btrfs snapshot cleanup

Previously, cleaning up deleted snapshots could lead to a sudden burst of activity for the Btrfs qgroup.
This could cause I/O delays, system hangs, UI freezing, or even running out of memory.

With this change, `snapper` can make Btrfs skip qgroup accounting for snapshot cleanup if the snapshot is too large, avoiding the problems above.

Even though this will mark the qgroup as inconsistent, `snapper` will detect it and trigger a qgroup rescan automatically.
That means you do not have to do anything to correct that.


[#bsc-1198083]
==== Btrfs RAID 1 not fully supported

In case of a disk failure, the remaining disk needs to be mounted with the `degraded` option manually:

[source,bash]
mount -odegraded,ro


[#jsc-SLE-9186]
==== `bcache-tools` has been added

The package `bcache-tools` has been added.
It provides tools for analyzing `bcache` devices.


[#jsc-SLE-16156]
==== exFAT tools have been added

The package `exfatprogs` has been added to {product} {this-version}.
It provides the utilities for working with exFAT file systems.


[#jsc-SLE-17365]
==== Per-inode DAX flag

In previous {product} releases, the DAX mode (direct access mode for Ext4 and XFS) was either enabled or disabled for the whole storage volume with the `dax` mount option.

{product} 15 SP3 adds the possibility to enable DAX on individual files.
The corresponding file system mount options are `dax={always, never, inode}`.
The old `dax` option corresponds to the new `dax=always` option.
This option reflects in the content of the `/proc/mounts` file.

For {product} 15 SP3, there is a transitional change to show `dax,dax=always` in `/proc/mounts` for compatibility with applications that detect DAX by the presence of the standalone `dax` option.
Future {product} releases will remove this transitional behavior, and the option will be shown as `dax=<option>` in `/proc/mounts`.


[#jsc-SLE-13586]
==== Serialization of Btrfs operations

Certain operations cannot be performed concurrently on a Btrfs file system, namely: balancing, device removal, device addition, and file-system resizing.
In previous releases, when attempting to perform these operations concurrently, they conflicted, one operation failed, and a message was added to the kernel log.

The Btrfs utilities (package `btrfsprogs`) now provide conflict reporting and allow serializing these exclusive operations using the `--enqueue` option.
For more information, see the man pages from the `btrfsprogs` package.


// !STICKY
[#file-system-comparison]
==== Comparison of supported file systems


{sle} was the first enterprise Linux distribution to support journaling file systems and logical volume managers in 2000.
Later, we introduced XFS to Linux, which allows for reliable large-scale file systems, systems with heavy load, and multiple parallel reading and writing operations.
With {sle} 12, we started using the copy-on-write file system Btrfs as the default for the operating system, to support system snapshots and rollback.

The following table lists the file systems supported by {sle}.

__Support status:__ {sup} supported / {uns} unsupported

[cols="25,^15,^15,^15,^15" options="header"]
|===
|Feature
|Btrfs
|XFS
|Ext4
|OCFS 2^1^

|Supported in product
|{slea}
|{slea}
|{slea}
|{haa}

|Data/metadata journaling
|N/A^2^
|{uns} / {sup}
|{sup} / {sup}
|{uns} / {sup}


|Journal internal/external
|N/A^2^
|{sup} / {sup}
|{sup} / {sup}
|{sup} / {uns}

|Journal checksumming
|N/A^2^
|{sup}
|{sup}
|{sup}

|Subvolumes
|{sup}
|{uns}
|{uns}
|{uns}

|Offline extend/shrink
|{sup} / {sup}
|{uns} / {uns}
|{sup} / {sup}
|{sup} / {uns}^3^

|Inode allocation map
|B-tree
|B+-tree
|Table
|B-tree

|Sparse files
|{sup}
|{sup}
|{sup}
|{sup}

|Tail packing
|{uns}
|{uns}
|{uns}
|{uns}

|Small files stored inline
|{sup} (in metadata)
|{uns}
|{sup} (in inode)
|{sup} (in inode)

|Defragmentation
|{sup}
|{sup}
|{sup}
|{uns}

|Extended file attributes/ACLs
|{sup} / {sup}
|{sup} / {sup}
|{sup} / {sup}
|{sup} / {sup}

|User/group quotas
|{uns} / {uns}
|{sup} / {sup}
|{sup} / {sup}
|{sup} / {sup}

|Project quotas
|{uns}
|{sup}
|{sup}
|{uns}

|Subvolume quotas
|{sup}
|N/A
|N/A
|N/A

|Data dump/restore
|{uns}
|{sup}
|{uns}
|{uns}

|Block size default
4+|4{nbsp}KiB^4^

|Maximum file system size
|16{nbsp}EiB
|8{nbsp}EiB
|1{nbsp}EiB
|4{nbsp}PiB

|Maximum file size
|16{nbsp}EiB
|8{nbsp}EiB
|1{nbsp}EiB
|4{nbsp}PiB
|===


^1^ OCFS 2 is fully supported as part of the {sleha}.

^2^ Btrfs is a copy-on-write file system.
Instead of journaling changes before writing them in-place, it writes them to a new location and then links the new location in.
Until the last write, the changes are not "committed".
Because of the nature of the file system, quotas are implemented based on subvolumes (`qgroups`).

^3^ To extend an OCFS 2 file system, the cluster must be online but the file system itself must be unmounted.

^4^ The block size default varies with different host architectures.
64{nbsp}KiB is used on POWER, 4{nbsp}KiB on other systems.
The actual size used can be checked with the command `getconf _PAGE_SIZE_`.

*Additional notes*

Maximum file size above can be larger than the file system's actual size because of the use of sparse blocks.
All standard file systems on {sles} have LFS, which gives a maximum file size of 2^63^{nbsp}bytes in theory.

The numbers in the table above assume that the file systems are using a 4{nbsp}KiB block size which is the most common standard.
When using different block sizes, the results are different.

In this document:

* 1024{nbsp}Bytes = 1{nbsp}KiB
* 1024{nbsp}KiB = 1{nbsp}MiB;
* 1024{nbsp}MiB = 1{nbsp}GiB
* 1024{nbsp}GiB = 1{nbsp}TiB
* 1024{nbsp}TiB = 1{nbsp}PiB
* 1024{nbsp}PiB = 1{nbsp}EiB.

See also https://physics.nist.gov/cuu/Units/binary.html.

// bsc#1073261
Some file system features are available in {sles} {this-version} but are not supported by {suse}.
By default, the file system drivers in {sles} {this-version} will refuse mounting file systems that use unsupported features (in particular, in read-write mode).
To enable unsupported features, set the module parameter `allow_unsupported=1` in `/etc/modprobe.d` or write the value `1` to `/sys/module/_MODULE_NAME_/parameters/allow_unsupported`.
However, note that setting this option will render your kernel and thus your system unsupported.


// !STICKY
[#file-system-btrfs-feature]
==== Supported Btrfs features

The following table lists supported and unsupported Btrfs features across multiple {slsa} versions.

__Support status:__ {sup} supported / {uns} unsupported

// Table according to bsc-979501, this attachment: https://bugzilla.suse.com/attachment.cgi?id=687340
[cols="22,^13,^13,^13,^13,^13,^13" options="header"]
|===
|Feature
|{slsa} 11 SP4
|{slsa} 12 SP5
|{slsa} 15 GA
|{slsa} 15 SP1
|{slsa} 15 SP2
|{slsa} 15 SP3

|Copy on write
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Free space tree (Free Space Cache v2)
|{uns}
|{uns}
|{uns}
|{sup}
|{sup}
|{sup}

|Snapshots/subvolumes
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Swap files
|{uns}
|{uns}
|{uns}
|{sup}
|{sup}
|{sup}

|Metadata integrity
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Data integrity
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Online metadata scrubbing
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Automatic defragmentation
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|Manual defragmentation
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|In-band deduplication
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|Out-of-band deduplication
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Quota groups
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Metadata duplication
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Changing metadata UUID
|{uns}
|{uns}
|{uns}
|{sup}
|{sup}
|{sup}

|Multiple devices
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|RAID 0
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|RAID 1
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup} (See <<bsc-1198083>>)

|RAID 5
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|RAID 6
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|RAID 10
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Hot add/remove
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Device replace
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|Seeding devices
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|Compression
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Big metadata blocks
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Skinny metadata
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Send without file data
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Send/receive
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}

|Inode cache
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}
|{uns}

|Fallocate with hole punch
|{uns}
|{sup}
|{sup}
|{sup}
|{sup}
|{sup}
|===


[#jsc-SLE-22663]
==== XFS V4 format file systems have been deprecated

Customers who have created XFS file system on {slea} 11 or prior will see the following message:
```
Deprecated V4 format (crc=0) will not be supported after September 2030
```

While the file system will work and be supported until the date mentioned, it is best to re-create the file system:

1. Backup all the data to another drive or partition
2. Create the file system on the device
3. Restore the data from the backup

To find out whether XFS filesystem has V4, run the following command:

```
xfs_info <mounted-filesystem>
```

Then check for the presence of the `crc=1` string.
