:this-version: 16.0
:idprefix: v160_
:doc-url: https://documentation.suse.com/sles-sap/16.0

== {productname} Version {this-version}

These release notes apply to {productname} {this-version}.

=== Changes affecting all architectures (Beta2)

[#bsc-1238590]
==== Not possible to SSH after installation

After installation of {productname}, SSH is not enabled by default.

To enable SSH during installation, provide a SSH public key for the `root` user.

[#jsc-DOCTEAM-1848]
==== Configuring network interfaces during installation

Currently, the installer does not allow for setting up network interfaces using the UI.
However, in the meantime you can use dracut-like command-line options, for example:

[source]
ifname=<interface>:<MAC>
ip=<interface>:dhcp

Additionally, the `inst.copy_network` is not available in Beta4.

// include all SLES release notes as well
// include SLES attributes to properly resolve product names
include::../sles/attributes.adoc[]
include::../sles/version160.adoc[]

[NOTE]
This behavior differs between {sles} and {slessap}.
In {sles}, SSH is enabled by default during installation even if public key for `root` is not provided.
