include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#instUpgrade]
== Installation and Upgrade

{product} can be deployed in several ways:

* Physical machine
* Virtual host
* Virtual machine
* System containers
* Application containers

[#instUpgrade-installation]
=== Installation

This section includes information related to the initial installation of {product} {this-version}.

.Installation Documentation
[IMPORTANT]
====
The following release notes contain additional notes regarding the installation of {product}.
However, they do not document the installation procedure itself.

// disclaimer beta
ifeval::["{lifecycle}" == "beta"]
For installation documentation, see the __Deployment Guide__ at {doc-url-beta}/SLES-deployment/html/ (draft version).
endif::[]
// disclaimer maintained
ifeval::["{lifecycle}" == "maintained"]
For installation documentation, see the __Deployment Guide__ at {doc-url}/singlehtml/book_sle_deployment/book_sle_deployment.html.
endif::[]
// disclaimer unmaintained (same as maintained)
ifeval::["{lifecycle}" == "unmaintained"]
For installation documentation, see the __Deployment Guide__ at {doc-url}/singlehtml/book_sle_deployment/book_sle_deployment.html.
endif::[]
====

// Installation-related release notes go here

[#jsc-SLE-7078]
==== Setting CPU Mitigations

The Linux kernel gained a boot option that controls the mitigations
for recently discovered CPU vulnerabilities.

The installer now allows setting the mitigations level directly during
the installation of the system, independently of whether the system is
being installed manually or via AutoYaST.

The mitigations level can be set to "off", "automatic" or "automatic with
disabled Simultaneous Multithreading".


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#instUpgrade-upgrade]
=== Upgrade-Related Notes

This section includes upgrade-related information for {product} {this-version}.

.Upgrade Documentation
[IMPORTANT]
====
The following release notes contain additional notes regarding the upgrade of {product}.
However, they do not document the upgrade procedure itself.

// disclaimer beta
ifeval::["{lifecycle}" == "beta"]
For upgrade documentation, see the __Deployment Guide, Chapter Upgrading SUSE Linux Enterprise__ at {doc-url-beta}/book_sle_deployment/data/cha_update_sle.html (draft version).
endif::[]
// disclaimer maintained
ifeval::["{lifecycle}" == "maintained"]
For upgrade documentation, see the __Deployment Guide, Chapter Upgrading SUSE Linux Enterprise__ at {doc-url}/html/SLES-all/part-update.html.
endif::[]
// disclaimer unmaintained (same as maintained)
ifeval::["{lifecycle}" == "unmaintained"]
For upgrade documentation, see the __Deployment Guide, Updating and Upgrading SUSE Linux Enterprise__ at {doc-url}/html/SLES-all/part-update.html.
endif::[]
====

// Upgrade-related release notes go here

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

==== Make Sure the Current System Is Up-To-Date Before Upgrading

Upgrading the system is only supported from the most recent patch level.
Make sure the latest system updates are installed by either running `zypper patch` or by starting the YaST module Online-Update.
An upgrade on a system not fully patched may fail.


==== Skipping Service Packs Requires LTSS

Skipping service packs during an upgrade is only supported if you have a Long Term Service Pack Support contract.
Otherwise you first need to upgrade to {previous-sp} before upgrading to {this-sp}.

// JeOS-specific content is in a seperate file
include::jeos.adoc[]

[#instUpgrade-more]
=== For More Information

For more information, see <<all-architecture>> and the sections relating to your respective hardware architecture.
