include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#systemZ]
== {ibmz}-Specific Features & Fixes (s390x)

Information in this section pertains to the version of {product} {this-version} for the {ibmz} architecture.
For more information, see https://www.ibm.com/docs/en/linux-on-systems?topic=distributions-suse-linux-enterprise-server

[#systemZ-hardware]
=== Hardware

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#systemZ-hardware-valgrindz13]
==== Valgrind IBM z13 Support

Valgrind now includes instruction support for IBM z13 instructions.
This enables debugging and validation of binaries built and optimized for IBM z13.
In particular this covers the vector instruction set extensions introduced with IBM z13.

[#systemZ-hardware-binutilsz15]
==== Support for IBM z15 in binutils and glibc

Binutils and glibc have been updated to support instructions introduced with IBM z15.

[#systemZ-hardware-zlibz15]
==== Compression Improvements for zlib

The zlib library has been updated to exploit the IBM z15 compression capabilities.

[#systemZ-hardware-gzipz15]
==== Compression Improvements for gzip

The gzip tool has been updated to exploit the IBM z15 compression capabilities.

[#systemZ-hardware-perfz15]
==== Performance Counters for IBM z15 (CPU-MF)

For optimized performance tuning the CPU-measurement counter facility now supports counters, including the MT-diagnostic counter set, that were originally introduced with IBM z14.

[#systemZ-hardware-NVME]
==== Collecting NVMe-Related Debug Data

To debug NVMe devices, the debug data gets collected and added to the dbginfo.sh script.

[#systemZ-hardware-PCI]
==== PCI Error Reporting Tool

Defective PCIe devices are now reported via error notification events that include health information of the adapters.


[#systemZ-network]
=== Network

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#systemZ-network-osa7S]
==== OSA-Express7S Adapters are now Supported

With the OSA 7 network cards a link speed of 25Gb/s is supported.

[#systemZ-network-tcpsegmentation]
==== Full-blown TCP Segmentation Offload

TCP segmentation offload is now supported on both layer 2 and layer 3 and is extended to IPv6.

[#systemZ-network-MAC]
==== Handle Provisioned MAC Addresses

You can now use provisioned MAC addresses for devices supported with IBM z14 and later hardware.


[#systemZ-performance]
=== Performance

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#systemZ-performance-auxtrace]
==== Synthesize perf Events/Samples from CPU-MF auxtrace Data

Enhance perf tool to synthesize perf diagnostic events and samples saved in the auxtrace buffer.
The auxtrace buffer contains basic- and diagnostic sampling data entries.

[#systemZ-performance-perfPMU]
==== CPU-MF/perf: Export Sampling Data for Post-Processing

Enhance the hardware sampling in the perf PMU driver to export additional information for improved perf tool post processing.
Display address and function name where sample was taken.

[#systemZ-performance-network]
==== Network Performance Improvements

Enhanced performance for OSA and Hipersockets via code improvements and exploitation of further kernel infrastructure.


[#systemZ-security]
=== Security

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#systemZ-security-chacha20]
==== SIMD Implementation of Chacha20 in OpenSSL

This enables support for TLS 1.3 via the Chacha20 cipher suite providing good performance using SIMD instructions.

[#systemZ-security-poly1305]
==== SIMD Implementation of Poly1305 in OpenSSL

This enables support for TLS 1.3 via the Poly1305 cipher suite providing good performance using SIMD instructions.

[#systemZ-security-CPACF]
==== Support of CPACF Hashes in ep11 Token in openCryptoki and libica

Provides improved performance for applications computing many digital signatures using EP11 like Blockchain.

[#systemZ-security-protectedKeys]
==== In-kernel Crypto: Support for Protected Keys Generated by random in the paes Module

This feature can generate volatile protected keys.
This allows, for example, the secure encryption of swap volumes without the need for a CryptoExpress adapter

[#systemZ-security-zcryptstats]
==== New Tool `zcryptstats` to Extract Crypto Measurement Data

Added a new tool `zcryptstats` to the s390-tools package to to obtain and display measurement data from crypto adapters for capacity planning.

[#systemZ-security-zcrypt]
==== Support Multiple zcrypt Device Nodes

The cryptographic device driver can now provide and maintain multiple zcrypt device nodes.
These nodes can be restricted in terms of cryptographic adapters, domains, and available IOCTLs.

[#systemZ-security-openCryptoki]
==== openCryptoki ep11 Enhancements

Support new functions and new mechanisms introduced for ep11 with IBM z14.

[#systemZ-security-openCryptokiToken]
==== Enhanced openCryptoki Support

Enhanced openCryptoki ep11 token to support m_*Single functions from ep11 lib.

[#systemZ-security-libica]
==== libica: CPACF Enhancements

Enhanced libica to support NIST curves as provided by CPACF MSA-9.

[#systemZ-security-opensslibmca]
==== openssl-ibmca: CPACF Enhancements

Enhanced openssl-ibmca to support NIST curves as provided by CPACF MSA-9.

[#systemZ-security-zcryptDD]
==== zcrypt DD: APQN Tags Allow Deterministic Driver Binding

Provides deterministic hot-plugging semantics to enable the virtualization and unique determination of crypto adapters in KVM environments even if the associated hardware gets intermittently lost and reconnected.



[#systemZ-storage]
=== Storage

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#systemZ-storage-zdsfs]
==== zdsfs: Online VTOC Refresh

A Linux application can now access new data sets that were created after zdsfs was mounted without the need to remount zdsfs.

[#systemZ-storage-persistentDeviceConf]
==== Persistent Device Configuration

The following SUSE-supplied commands are now deprecated:

* `ctc_configure`
* `dasd_configure`
* `qeth_configure`
* `zfcp_disk_configure`
* `zfcp_host_configure`

These commands will be removed in a future release.

With {product} {this-version}, as an intermediate step, these scripts have been modified to use the IBM-supplied commands `chzdev` and `lszdev`.

If you are using the SUSE-supplied scripts, discontinue their use and directly use the commands
`chzdev` and `lszdev` provided by IBM in the package s390-tools.

[#systemZ-storage-CCW]
==== Enable Raw Track Access Without Prefix CCW

The DASD driver makes use of the Prefix CCW when accessing a DASD in raw track access mode.
On some systems (e.g. zPDT), support for the Prefix CCW is not available.
As a result, the raw track access mode cannot be used on those systems.

By enabling raw track access mode on zPDT, customers can easily move their Linux system volumes between zPDT and LPAR, allowing for greater flexibility during deployment of new setups.

[#systemZ-storage-IFCC]
==== Configurable IFCC Handling  (Interface Control Check) for DASDs

Provides a possibility to direct IFCC messages to the kernel log again in addition to the actual path handling.
Enables to switch off the actual handling of repeated IFCCs (i.e. removing paths) so that only IFCC messages are written to the log when thresholds are exceeded.

[#systemZ-storage-DIF]
==== Split DIF and DIX Boot Time Controls

Enables the user to separately configure DIF and DIF+DIX integrity protection mechanisms for zFCP-attached SCSI devices.

[#systemZ-storage-portSpeed]
==== scsi: zfcp: Add Port Speed Capabilities

Provides the possibility to display port speed capabilities for SCSI devices.


[#systemZ-virtualization]
=== Virtualization

The following new features are supported in {product} {this-version} under KVM:

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-6498]
==== Avoid Boot Failures After Changing Disks

On {product} {this-ga} virtual machines wopuld no longer boot after changing disks.
In most cases this could be solved by changing dracut's persistent_policy to `by-path` and then rebuild the initrds.
There {product} {this-version} `persistent_policy=by-path` is the new default for dracut.

[#systemZ-virtualization-diagnose]
==== Enhanced Hardware Diagnose Data for the Linux Kernel

Provide improved problem determination capabilities by passing Linux kernel information to hardware diagnose data.

[#systemZ-virtualization-passthrough]
==== zPCI Passthrough Support for KVM

Allow KVM to pass control over ROCE Express host devices to a KVM guest
enabling workloads that require direct access to PCI functions.

[#systemZ-virtualization-bootloader]
==== Interactive Bootloader

Enable to interactively select boot entries to recover misconfigured KVM guests.

[#systemZ-virtualization-hugePages]
==== Huge Pages

Allow KVM guests to use huge page memory backing for improved memory performance for workloads running with large memory footprints.

[#systemZ-virtualization-crashData]
==== Expose Detailed Guest Crash Information to the Hypervisor

Provides additional debug data for operating system failures that occur within a KVM guest.

[#systemZ-virtualization-z14ZR1]
==== New CPU Model IBM z14 ZR1

Provide the CPU model for the IBM z14 ZR1 to enable KVM guests to exploit new hardware features on the z14 ZR1.

[#systemZ-virtualization-z15]
==== New CPU Model IBM z15

Provide the CPU model for the IBM z15 to enable KVM guests to exploit new hardware features on the z15.

[#systemZ-virtualization-secureBoot]
==== Secure Linux Boot Toleration

Linux operating system images using a secure boot on-disk format can now be run in KVM without modifications required, lowering the overall administrative overhead.

[#systemZ-virtualization-ECKD]
==== IPL Support for ECKD DASDs

KVM guests can now IPL from ECKD DASDs attached via CCW passthrough, which is
provided as a technology preview in {product} {this-version}.

[#systemZ-virtualization-cryptoExpress]
==== Dedicated CryptoExpress Adapter Domains for KVM Guests

Allows KVM to dedicate domains of CryptoExpress adapters as passthrough devices to a KVM guest such that the guest can direct crypto requests directly to the IBM Z firmware without the hypervisor being able to observe the communication of the guest with the device.



[#systemZ-misc]
=== Miscellaneous

[#jsc-SLE-11600]
==== `CONFIG_NUMA_EMU` turned off

Turned off `CONFIG_NUMA_EMU` for s390x, which was also removed upstream because of limited benefit, to improve serviceability.


[#jsc-SLE-6927]
==== Kernel Parameter `resume` Removed

On {sle} the `resume=...` kernel parameter was enabled by default on all platforms.
With {product} {this-version} it is no longer enabled on s390x, because it is
not used on the IBM Z platform.



////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////



