include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#intro-techpreview]
=== Technology Previews

Technology previews are packages, stacks, or features delivered by {suse}
which are not supported.
They may be functionally incomplete, unstable or in other ways not suitable
for production use.
They are included for your convenience and give you a chance to test new technologies within an enterprise environment.

Whether a technology preview becomes a fully supported technology later depends on customer and market feedback.
Technology previews can be dropped at any time and {suse} does not commit to providing a supported version of such technologies in the future.

Give your {suse} representative feedback about technology previews, including your experience and use case.

////
  ** clear statement of TP (no support)
  ** Title of the TP ** full description of the TP
  ** link to official documentation (external)
  ** link to SUSE's documentation
////

[#intro-techpreview-all]
==== Technology Previews for All Architectures

[#bsc-1176440]
===== `schedutil`
`schedutil` is a CPU frequency scaling governor that makes decisions based on the utilization data provided by the scheduler, as opposed to other governors that use CPU idle time, such as `ondemand`.
It was introduced in the Linux kernel version 4.7.
However, it is only viable for production use together with an optimization called `util_est` (short for "utilization estimation") that makes it much more responsive.
This optimization is only available in Linux kernel version 4.17 and newer.
For this reason it is only offered as technology preview in {slea} {this-version}.


[#intro-techpreview-x86-64]
==== Technology Previews for AMD64/Intel 64 64-Bit (x86_64)

[#jsc-SLE-11270]
===== KVM Nested Virtualization

KVM Nested Virtualization is available in SLE 12 SP5 as a technology preview.
For more information, see https://www.kernel.org/doc/html/latest/virt/kvm/nested-vmx.html[the Linux kernel documentation].


[#jsc-SLE-4878]
===== Crystal Ridge: [HMEM] Hot Plug Device DAX Back Into the Kernel

Hotplug support for NVDIMM as a normal memory is provided as a technology preview.



