[#changes]
== New Features, Changes & Fixes

Information in this section applies to all architectures supported by
{product} {this-version} unless noted otherwise.

////
[#jsc-SLE-1234]
=== Example entry

Example text
////

[#jsc-PED-407]
=== Silence `KillMode=None` messages

The log level of the deprecation warnings regarding `killmode=None` have been reduced.
Instead of `warning`, they are now logged at the `debug` log level.


// jsc#DOCTEAM-167
[#bsc-1154168]
=== `CPE_NAME` has been changed in `/etc/os-release`

The `CPE_NAME` variable in `/etc/os-release` has been changed.
For more information, see https://www.suse.com/support/kb/doc/?id=7023490.


// [#new-packages-SAP]
// === Added Packages

// The following packages have been added to {product} with {this-version}:

// * TBD

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
=== Example Entry

Issue explanation
	
////

[#jsc-SLE-24988]
=== Enriched system visibility in the {sccfull}

{suse} is committed to helping provide better insights into the consumption of {suse} subscriptions regardless of where they are running or how they are managed; physical or virtual, on-prem or in the cloud, connected to SCC or {rmtfull}, or managed by {suma}.
To help you identify or filter out systems in SCC that are no longer running or decommissioned, {suseconnect} now features a daily “ping”, which will update system information automatically.

For more details see the documentation at https://documentation.suse.com/subscription/suseconnect/single-html/SLE-suseconnect-visibility/.


[#bsc-1197511]
=== SAP native systemd support

In the past for Linux the systemV init service `sapinit` was starting the SAP Host Agent and all the `sapstartsrv` processes listed in `/usr/sap/sapservices`.
A real systemd integration was not available.

Now the native integration of SAP Host Agent is started via the `saphostagent.service` unit.
Adaptations to the `saphostagent.service` unit must be done by adding a so-called drop-in file.

For any native integrated SAP instance a systemd unit with name schema `SAP<SID>_<INO>` (for example, `SAPEN1_10`) is added.
Adaptations should be done using a drop-in file.
It is highly recommended to still use the `sapcontrol` functions which guarantees also the functionality of cluster integration like the `sap-suse-cluster-connector`.

Before you start your new installation or update to the native systemd integration, make sure you update the resource agent packages to the newest available versions.
The native SAP systemd integration is supported starting with the following package versions for {product} {this-ga}:

* resource-agents 4.8.0+git30.d0077df0-8.11.1
* sapstartsrv-resource-agents 0.9.0+git.1645795466.55a8cca-1.12.1
* SAPHanaSR 0.155.0
* SAPHanaSR-ScaleOut 0.181.0

For details please refer to the manual pages `ocf_suse_SAPStartSrv(7)`, `SAPHanaSR(7)`, and `SAPHanaSR-ScaleOut(7)`.