
include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#authentication]
=== Authentication

// Release notes for authentication tools:
//   Active Directory, LDAP, Kerberos, Samba, ...

////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////


[#jsc-SLE-7187]
==== 389 Directory Server (389-ds) Administrative Tools

The various tools available in the `lib389` package to administrate the `389-ds` server are now available in {sles}.


// based on content from FATE#323362 and FATE#323453
[#jsc-SLE-16552]
==== 389 Directory Server Is the Primary LDAP Server, the OpenLDAP Server Is Deprecated

The OpenLDAP server (package `openldap2`, part of the __Legacy__ {slea} module) is deprecated and will be removed from {product} 15{nbsp}SP4.
The OpenLDAP client libraries are widely used for LDAP integrations and and are compatible with 389 Directory Server.
Hence, the OpenLDAP client libraries and command-line tools will continue to be supported on {producta} {this-ga} to provide an easier transition for customers that currently use the OpenLDAP Server.

To replace OpenLDAP server, {producta} includes 389 Directory Server.
389 Directory Server (package `389-ds`) is a fully-featured LDAPv3-compliant server suited for modern environments and for very large LDAP deployments.
389 Directory Server also comes with command-line tools of its own.

For information about setting up and upgrading to 389 Directory Server
in the SLES 15 SP2 Security Guide, chapter LDAP{mdash}A Directory Service.
