include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#network]
=== Networking

// Release Notes for networking features:
//     Wicked, NetworkManager, Open VSwitch...

In addition to the notes in this section, also see the following networking-related notes:

* <<jsc-SLE-7687>>


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////

[#jsc-SLE-8958]
==== `apache2-mod_auth_mellon` has been added

The `apache2-mod_auth_mellon` package has been added.
It is an authentication service that implements the SAML 2.0 federation protocol.
It grants access based on the attributes received in assertions generated by a IdP server.


[#jsc-SLE-22733]
==== `apache2` has been updated

The `apache2` package has been updated to version 2.4.51.


[#jsc-SLE-6952]
==== `gssproxy` Has Been Added

The `gssproxy` package, previously available in the _Package Hub_, has now been added to the _Basesystem Module_.


[#jsc-SLE-12395]
==== WireGuard userland tools have been added

The package `wireguard-tools` version 1.0.20200827 has been added.
It contains userland tools for the kernel WireGuard module.

WireGuard is a secure, fast, and easy-to-use VPN that uses modern cryptography.
For more information, see https://www.wireguard.com.


[#jsc-SLE-11203]
==== `net-snmp` has been updated

The `net-snmp` package has been updated to version 5.8.
It provides tools and libraries relating to the Simple Network Management Protocol.


// related: bsc#1156884, jsc#SLE-7188
[#jsc-SLE-11223]
==== Time Synchronization Configuration Using {suse}'s NTP Pool

Because the default NTP zone names are not meant to be used by vendors, `chrony` can not be pre-configured by {suse} to synchronize time using these.
This makes it harder to configure and also prevents using time synchronization during first boot.

To resolve this, a {suse} NTP pool has been created (`suse.pool.ntp.org`) and {producta} 15{nbsp}SP3 configures `chrony` to use it by default.

The following packages have been added:

* `chrony-pool-suse`
* `chrony-pool-empty`

These packages configure `chrony` to use the {suse} or an empty NTP server pool by default, respectively.


[#jsc-SLE-7472]
==== Apache: Support for Key IDs in `SSLCertificateKeyFile` in `mod_ssl`

The Apache module `mod_ssl` now includes a backported patch to enable support for Key IDs (via a PKCS#11 URL) in the `SSLCertificateKeyFile` Directive.


[#network-samba]
==== Samba

// bnc#606288
The version of Samba shipped with {sles} {this-version} delivers integration with Windows Active Directory domains.
In addition, we provide the clustered version of Samba as part of {sleha} {this-version}.


[#network-nfs4]
==== NFSv4

// bnc#608543 and bnc#574572
NFSv4 with IPv6 is only supported for the client side.
An NFSv4 server with IPv6 is not supported.


// related: FATE#323868 [removal info in FATE is incorrect, correction via mail from meissner, 2020-06-05]
[#jsc-SLE-9294]
==== More Services Support TLS 1.3 {mdash} TLS 1.1 and 1.0 Are No Longer Recommended for Use

The TLS 1.0 and 1.1 standards have been superseded by TLS 1.2 and TLS 1.3.
TLS 1.2 has been available for considerable time now.

Packages using GnuTLS and Mozilla NSS already supported TLS 1.3 in earlier {sle} 15 service packs.
Starting with {sle} 15{nbsp}SP2, we also enable TLS 1.3 in packages that use OpenSSL.

We recommend no longer using TLS 1.0 and TLS 1.1, as {suse} plans to disable these protocols in a future service pack.
However, not all packages, for example, Python, are TLS 1.3-enabled yet as this is an ongoing process.


[#jsc-SLE-11184]
==== New GeoIP Database Sources

The GeoIP database allows approximately geo-locating users by their IP address.
In the past, the company MaxMind made such data available for free in its GeoLite Legacy databases.
On January 2, 2019, MaxMind discontinued the GeoLite Legacy databases, now offering only the newer GeoLite2 databases for download.
To comply with new data protection regulation, since December 30, 2019, GeoLite2 database users are required to comply with an additional usage license.
This change means users now need to register for a MaxMind account and obtain a license key to download GeoLite2 databases.
For more information about these changes, see the link:https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/[MaxMind blog].

Previous versions of {product} included the `GeoIP` package of tools that are only compatible with GeoLite Legacy databases.
With {product} 15 SP2, we introduce the following new packages to deal with the changes to the GeoLite service:

* `libmaxminddb`: A library for working with the GeoLite2 format.

* `geoipupdate`: The official Maxmind tool for downloading GeoLite2 databases.
To use this tool, set up the configuration file with your MaxMind account details.
This configuration file can also be generated on the Maxmind web page.
For more information, see https://dev.maxmind.com/geoip/geoip2/geolite2/.

* `geolite2legacy`: A script for converting GeoLite2 CSV data to the GeoLite Legacy format.

* `geoipupdate-legacy`: A convenience script that downloads GeoLite2 data, converts it to the GeoLite Legacy format, and stores it in `/var/lib/GeoIP`.
With this script, applications developed for use with the legacy `geoip-fetch` tool will continue to work.

The following {product} packages use GeoIP data in the GeoLite2 format:

* `bind`
* `nginx`
* `wireshark`


[#bsc-1174181]
==== Intel* Omni-Path Architecture (OPA) Host Software

Intel Omni-Path Architecture (OPA) host software is fully supported in {product} {this-version}.
Intel OPA provides Host Fabric Interface (HFI) hardware with initialization and setup for high performance data transfers (high bandwidth, high message rate, low latency) between compute and I/O nodes in clustered environments.
For documentation about installing Intel Omni-Path Architecture, see: https://cdrdv2.intel.com/v1/dl/getContent/627110.


[#jsc-SLE-11632]
==== Wireshark Has Been Updated to Version 3.2

Wireshark has been updated from version 2.4, now at its end of life upstream, to version 3.2.
The new version brings the following changes:

* Added Support for new GeoIP databases (<<jsc-SLE-11184>>)
* Added Support for 111 new protocols, including WireGuard, LoRaWAN, TPM 2.0, 802.11ax, and QUIC
* Added Swedish and Ukrainian UI translations
* Improved support for existing protocols such as HTTP/2
* Improved analytics functionality
* Improved usability
* Security fixes
