include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#packagehub]
=== {ph}

// Release Notes for Package Hub:

{ph} brings open-source software packages from {opensuse} to {sles} and {sled}.

Usage of software from {ph} is not covered by {suse} support agreements.
At the same time, usage of software from {ph} does not affect the support status of your {sle} systems.
{ph} is available at no additional cost and without an extra registration key.


[#bsc-1171243]
=== Vendor Change During Migration for Packages

KDE Plasma 5 is a desktop environment which can be installed from {ph}.
Some package dependencies were moved from {slea} to {ph}.
Therefore, you may need to agree to a vendor change of these packages from {suse} to {opensuse} during migration between service packs.
This means that under normal circumstances manual interaction is required.

To accept the vendor change automatically during migration, use the following command:

[source]
----
zypper migration --allow-vendor-change
----


[#jsc-ECO-2878]
==== {nvidia} Compute module

The repositories for {nvidia} CUDA are available as the __{nvidia} Compute__ module for x86-64 and AArch64.
These repositories are provided by {nvidia} and the software in them is not supported by {suse}.
All software in these repositories is licensed under the third-party https://docs.nvidia.com/cuda/eula/index.html[{nvidia} CUDA EULA].

The __{nvidia} Compute__ module is not enabled by default when installing {product}.
During installation, the module can be selected manually from the __Extension and Modules__ screen in {yast}.
Within an installed system, you can add it as follows:
Run `yast registration` from a shell as root, select __Select Extensions__, search for __NVIDIA Compute Module__ and continue with __Next__.
Verify and accept the {nvidia} repository GPG key.


[IMPORTANT]
.Do not use the `SUSEConnect` tool to add this repository
====
Do not try to add this module with the `SUSEConnect` CLI tool.
`SUSEConnect` is not yet capable of handling third-party repositories.
====

[IMPORTANT]
.Combining __Workstation Extension__ and __{nvidia} Compute__ module is unsupported
====
The __Workstation Extension__ module includes some of the same drivers for {nvidia} graphics cards as the __{nvidia} Compute__ module.
However, their package versions may differ.
As {suse} package management installs the latest package versions by default, enabling both modules at the same time can lead to a system with a mixture of packages from both modules.

Such a setup can result in drivers not working as expected and is not supported by {suse}.
====


[#bsc-1117531]
=== Package Dependencies to Other Modules

When installing packages from {ph}, you may need to activate additional {slea} modules to solve dependency issues.
