include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[#systemsManagement]
=== Systems Management

// Release Notes for system management tools:
//    YaST, Zypper, AutoYaST, KIWI, SUSEconnect, Salt, ...

[#jsc-PED-7978]
==== Effective user limits in systemd setup

Before, the lookup of the effective session limit in a systemd setup was not trivial.
Now these new properties have been added:

* `EffectiveMemoryMax`
* `EffectiveMemoryHigh`
* `EffectiveTasksMax`


[#jsc-SLE-9106]
==== Timeout support `systemd`-style mounts in `fstab`

Entries specified in `/etc/fstab` that use `systemd` for mounting can now specify setting a timeout.
To specify a timeout for an entry, add the `x-systemd.mount-timeout` option.

See the https://www.freedesktop.org/software/systemd/man/systemd.mount.html#x-systemd.mount-timeout=[documentation] for more information.


// jsc#DOCTEAM-174
[#bsc-1182237]
==== `systemd` units in `/usr/local` not activating

Units or software installed in `/usr/local` do not activate at early boot stages.
To work around this, add the `x-systemd.initrd` mount option to the `/usr/local` mount in `/etc/fstab`.


[#jsc-SLE-9103]
==== {yast} NTP Client Module and systemd-timer

Starting with {product} {this-version}, the {yast} module for NTP client configuration configures the systemd-timer (instead of the cron daemon) to execute cronie if it is not configured to run as a daemon and still performs a regular time sync.

[#jsc-SLE-7753]
==== Networking Technologies Removed from the {yast} Network Module

The following networking technologies are no longer supported by the {yast} module
for network configuration:

- PCMCIA
- token ring
- FDDI
- myrinet
- arcnet
- xp (IA64-specific)
- ESCON ({ibmz}-specific)

[#jsc-SLE-9077]
==== {yast} sysctl Settings Location

Starting with {product} {this-version}, {yast} writes sysctl settings to a separate file called
`/etc/sysctl.d/70-yast.conf`.

This helps reduce conflicts with applications that override system settings.

[#jsc-SLE-9171]
==== New Zypper Options

Unlike other Zypper commands, `zypper download` did not allow specifying the
repository to download a package from.

With this release, it is possible to specify the repository the same way as
with other commands using the `--repo` option (or its alias `--from`).

[#jsc-SLE-10500-1]
==== Changes for Snapper Plug-in for Zypper

The Snapper plug-in for Zypper has been rewritten from Python to C.
This includes along a different implementation of regular expressions.

If you use regular expressions in `/etc/snapper/zypp-plugin.conf`, they may stop working correctly in some cases.
This is true for regular expressions that rely on syntax that differs between the previous Python implementation and the new POSIX implementation.

In general, using wildcards instead of regular expressions is strongly recommended.


[#jsc-SLE-10500-2]
==== xfs_scrub_all Has Been Removed

The script for scrubbing all XFS file systems in the system has been removed from the distribution.
The {slea} kernel does not support XFS scrubbing, meaning it could only be used with a custom kernel.


[#jsc-SLE-9109]
==== Extended Package Search in YaST

The {yast} software management module can only install packages from enabled modules or repositories.
In the past, finding out which module needed to be enabled for a specific package could be tricky.
In {slea}{nbsp}{this-version}, if the system is registered against {scc}, the software management module you can now search for packages from disabled modules.


[#jsc-SLE-6762]
==== File Name of Archives Generated by `supportconfig` Has Changed

Archive files created by `supportconfig` now use the file name prefix `scc_` instead of `nts`.


[#bsc-1171343]
==== {autoyast} Will Not Propose Insecure Settings When Cloning a System

In past versions of {slea}, when cloning a system, {autoyast} used relatively permissive settings for package signature handling.
{autoyast} would accept unsigned files, files without checksum, and use unknown and untrusted GPG keys.
These default settings could be a security risk.

In {slea}{nbsp}{this-version}, {autoyast} uses stricter signature handling settings by default.
If needed, adjust those settings manually.

For more information, see the link:{doc-url}/single-html/SLES-autoyast/#CreateProfile-General-signature[{autoyast} Guide].


[#jsc-SLE-7743]
==== Support for IP Filtering in systemd

Support for IP filtering, as described in http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html is now available in systemd on {product} {this-version}.


[#jsc-SLE-10123]
==== Default TasksMax Limit Disabled in systemd

The `TasksMax` limit for both user and system slices has been removed because it caused issues with large database or JVM workloads.


[#jsc-SLE-12433]
==== Salt Has Been Updated to Version 3000

Salt has been upgraded to upstream version 3000, plus a number of patches, backports and enhancements by {suse}.
In particular, CVE-2020-11651 and CVE-2020-11652 fixes are included in our release.

As part of this upgrade, cryptography is now managed by the Python-M2Crypto library (which is itself based on the well-known OpenSSL library).

We intend to regularly upgrade Salt to more recent versions.

For more details about changes in your manually-created Salt states, see the link:https://docs.saltstack.com/en/latest/topics/releases/3000.html[Salt 3000 upstream release notes].

Salt 3000 is the last version of Salt which will support the old syntax of the `cmd.run` module.


[#jsc-SLE-7690]
==== Support for System V init.d Scripts Is Deprecated

systemd in {product} {this-version} automatically converts System V `init.d` scripts to service files.
Support for System V init.d scripts is deprecated and will be removed with the next major version of {product}.
systemd, as shipped with the next major version of {product} will also stop converting System V `init.d` scripts to service files.

To prepare for this change, use the automatically generated systemd service files directly instead of using System V `init.d` scripts.
To do so, copy the generated service files to `/etc/systemd/system`.
To then control the associated services, use `systemctl`.

The automatic conversion provided by systemd (specifically, `systemd-sysv-generator`) is only meant to ensure backward compatibility with System V init.d scripts.
To take full advantage of systemd features, it can be beneficial to manually rewrite the service files.

This deprecation also causes the following changes:
+
--
// jsc#SLE-7192
** The `/etc/init.d/halt.local` initscript is deprecated.
Use systemd service files instead.
// jsc#SLE-10912
** `rc__SERVICE__` controls of systemd services are deprecated.
Use systemd service files instead.
// jsc#SLE-9004
** `insserv.conf` is deprecated.
--


////
[#<UNIQUEID e.g. bsc-1111 or jsc-SLE-111>]
==== Example Entry

Challenge (regular paragraph)

Resolution (regular paragraph)
////
